export interface LifeChallenge {
  id: string;
  title: string;
  subtitle: string;
  feelsLike: string;
  whereItShowsUp: string[];
  triggerPatterns: string[];
  hiddenStrength: string;
  whatHelps: string[];
  journalQuestion: string;
  affirmation: string;
  astrologicalRoots: string;
}

export const CHALLENGE_LIBRARY: LifeChallenge[] = [
  {
    id: "fear_rejection",
    title: "Fear of Rejection",
    subtitle: "The armor that keeps love out while trying to keep pain out.",
    feelsLike: "A constant low-level vigilance around whether you are wanted, whether your presence is welcome, and whether the people you care about might suddenly withdraw. Rejection, when it comes, confirms a story that was already running; approval provides temporary relief but never quite settles the underlying question.",
    whereItShowsUp: ["Holding back in relationships to avoid being the first one to care more", "People-pleasing as protection from being rejected", "Difficulty taking risks that might result in visible failure", "Testing relationships to see if people will really stay"],
    triggerPatterns: ["Being excluded from plans or not being invited", "Someone taking longer than usual to respond", "Criticism or feedback that feels personal", "The beginning of a new relationship where vulnerability is required"],
    hiddenStrength: "Those who have deeply lived the fear of rejection often develop an extraordinary sensitivity to others — they know what it feels like to be on the outside looking in, and that knowing produces genuine empathy and inclusivity. The wound of rejection, when integrated, becomes the gift of making others feel genuinely welcome.",
    whatHelps: ["Distinguishing between 'being rejected' and 'this particular thing not working out'", "Building a steady inner relationship with yourself that doesn't require external validation to feel stable", "Taking small relational risks and noticing that most of them don't end in catastrophe", "Examining early experiences that created the original belief about being rejectable"],
    journalQuestion: "What is the earliest memory you have of feeling genuinely unwanted — and what did that experience teach you to believe about yourself?",
    affirmation: "My belonging does not depend on anyone's permission.",
    astrologicalRoots: "Saturn-Moon aspects, Moon in Aries square Saturn, or South Node in the 7th house often accompany a deep familiarity with rejection's wound. These placements suggest someone who has been learning, across time, what genuine security from within feels like.",
  },
  {
    id: "self_doubt",
    title: "Self-Doubt",
    subtitle: "The inner critic that mistakes its volume for authority.",
    feelsLike: "A persistent internal voice that questions whether you are capable, worthy, or good enough — and that conveniently finds evidence for this view in even ordinary situations. Successes feel lucky or temporary; mistakes feel confirming. The doubt is often invisible to others, who frequently see more capability than the inner critic reports.",
    whereItShowsUp: ["Procrastinating on projects because you fear they won't be good enough", "Downplaying your contributions in groups or conversations", "Comparing your behind-the-scenes with others' highlight reels", "Difficulty accepting genuine praise"],
    triggerPatterns: ["Beginning something new where the outcome is uncertain", "Making a mistake in a visible context", "Being asked to take on a role that feels bigger than current self-concept", "Receiving both praise and criticism simultaneously"],
    hiddenStrength: "Self-doubt, when it is not allowed to disable action, can be the engine of unusually high-quality work. The person who doubts themselves often checks and rechecks, seeks feedback, and improves with genuine humility. When the doubt is used for refinement rather than paralysis, it produces excellence that pure confidence rarely achieves.",
    whatHelps: ["Tracking evidence of actual capability — keeping a 'wins' record that the inner critic can't easily dismiss", "Differentiating between healthy self-assessment and self-attack", "Acting in spite of the doubt rather than waiting for it to resolve", "Examining whose voice the inner critic sounds most like"],
    journalQuestion: "If your inner critic had a face, whose face would it wear — and what did you learn to believe about yourself from that person?",
    affirmation: "I am more capable than my fear is willing to admit.",
    astrologicalRoots: "Saturn in the 1st house, Chiron conjunct the Sun, or Neptune-Moon aspects often correspond with a deeply internalized questioning of one's own worth and capacity. These are placements that can produce profound humility — and the journey is learning to distinguish genuine humility from false diminishment.",
  },
  {
    id: "relationship_patterns",
    title: "Repeating Relationship Patterns",
    subtitle: "The tendency to find the same dynamic in different people.",
    feelsLike: "A recurring sense of déjà vu in relationships — the partner, friend, or colleague looks different but the dynamic feels eerily familiar. There may be awareness of the pattern while still feeling unable to choose differently. The pull toward the familiar dynamic can feel stronger than the rational intention to change.",
    whereItShowsUp: ["Repeatedly attracting partners who are emotionally unavailable", "Cycles of idealization followed by disappointment", "Consistently giving more than receiving in relationships", "Attracting people who need fixing or rescuing"],
    triggerPatterns: ["The beginning of a new relationship where excitement overrides discernment", "Feeling deeply seen or understood by someone who later proves unavailable", "The moment a relationship begins to feel safe and ordinary rather than charged"],
    hiddenStrength: "People who have worked through repeating relationship patterns typically develop an extraordinary depth of relational wisdom. They come to understand the unconscious dynamics of connection in ways that those who have had simpler relationship histories cannot access. This understanding, when integrated, makes them exceptional partners and friends.",
    whatHelps: ["Identifying the pattern explicitly, including your own contribution", "Examining what early attachment experience the pattern mirrors", "Slowing the pace of new relationships to allow more information to surface", "Therapy specifically oriented toward attachment patterns"],
    journalQuestion: "What is the dynamic you keep finding in relationships — and can you find the first time you experienced that dynamic in childhood?",
    affirmation: "I choose consciously the love that is genuinely good for me.",
    astrologicalRoots: "Venus-Pluto or Venus-Saturn aspects, the South Node in the 7th house, or Chiron in Libra/the 7th often accompany deeply rooted relationship patterns. These placements suggest someone whose soul's work includes transforming the unconscious blueprint of what love looks and feels like.",
  },
  {
    id: "procrastination",
    title: "Procrastination",
    subtitle: "The avoidance that masquerades as 'not the right time.'",
    feelsLike: "The uncomfortable combination of wanting to move forward and being unable to begin — punctuated by guilt, sometimes by bursts of frantic last-minute action, and always by the low-grade anxiety of knowing the thing hasn't been done. The delay often feels protective in the moment and punishing later.",
    whereItShowsUp: ["Important creative projects that are perpetually 'almost ready to begin'", "Conversations that need to happen but keep being postponed", "Health and wellness practices that start tomorrow", "Career moves or applications that sit in draft"],
    triggerPatterns: ["The awareness that the work will reveal something about one's ability (or perceived lack of it)", "Projects that feel too big to begin from the beginning", "Work that is linked to deep personal meaning and therefore feels highest-stakes", "Unclear next steps that make 'begin' feel undefined"],
    hiddenStrength: "What is labeled procrastination is often actually a longer incubation period — the creative and psychological preparation that happens underground before something is ready to be brought forward. Many procrastinators do their most creative thinking precisely during the period they're not producing. When the block is resolved, what emerges often reflects the depth of that preparation.",
    whatHelps: ["Breaking tasks into the smallest possible next action", "Separating the meaning of the work from the evaluation of the worker", "Using body-forward approaches: setting a timer, changing location, starting anywhere", "Examining whether the delay is fear-based or genuinely strategic"],
    journalQuestion: "What are you most afraid will be revealed if you actually complete this — about yourself, your capability, or what comes next?",
    affirmation: "Beginning is the act of courage — the rest follows.",
    astrologicalRoots: "Mars-Neptune aspects, Saturn in the 6th house, or 12th house stelliums often correlate with procrastination patterns. These configurations can create a gap between inspiration and manifestation that requires very deliberate and compassionate bridging.",
  },
  {
    id: "boundaries",
    title: "Boundary Challenges",
    subtitle: "The difficulty of saying where you end and others begin.",
    feelsLike: "A recurring experience of overextending, over-giving, or saying yes when every part of you wanted to say no — followed by resentment, exhaustion, or the disconcerting realization that your own needs have become invisible, even to yourself.",
    whereItShowsUp: ["Difficulty saying no without excessive guilt or explanation", "Taking on others' emotional weight as your own responsibility", "Relationships where your needs are consistently secondary", "Physical or emotional exhaustion from giving beyond your actual capacity"],
    triggerPatterns: ["Someone expressing need or disappointment", "The risk of conflict if a limit is set", "Situations that trigger the fear of being seen as selfish or unkind", "Relationships with people whose needs are louder than one's own"],
    hiddenStrength: "People who struggle with boundaries often possess an extraordinary capacity for empathy and care — they feel others' needs genuinely and completely. When this capacity is paired with the skill of appropriate boundary-setting, it produces a quality of relationship that is both deeply caring and genuinely sustainable. The boundary is what makes the love possible.",
    whatHelps: ["Distinguishing between kindness and self-abandonment", "Practicing small 'no's in low-stakes contexts before attempting the larger ones", "Noticing the body's signals of boundary violation before the mind registers it", "Understanding that boundaries are a form of self-respect, not selfishness"],
    journalQuestion: "What do you believe will happen to a relationship if you say no — and where did you learn to believe that?",
    affirmation: "My limits are the shape of my love — not the end of it.",
    astrologicalRoots: "Neptune in the 1st house, Pisces rising, or Moon-Neptune conjunctions often correspond with porous boundaries and the deep empathic absorption of others' emotional states. These placements carry beautiful gifts of compassion that mature into wisdom when the art of self-preservation is learned alongside them.",
  },
  {
    id: "burnout",
    title: "Burnout",
    subtitle: "When the fire that drove you has consumed itself.",
    feelsLike: "An absence rather than a presence — the energy, motivation, and meaning that used to be available simply isn't there anymore. Tasks that once felt purposeful now feel exhausting. The performance continues but the person behind it is running on empty. Numbness, cynicism, and the inability to be genuinely present are the hallmarks.",
    whereItShowsUp: ["Career or creative work that once felt meaningful but now feels mechanical", "Physical symptoms of depletion: chronic fatigue, lowered immunity, sleep disruption", "Emotional withdrawal from people and activities that once brought joy", "The inability to experience genuine rest even when circumstances allow it"],
    triggerPatterns: ["Extended periods of high output without adequate recovery", "Work where the personal cost is invisible or dismissed by others", "Environments that reward maximum effort while providing minimum support", "The identity fusion of 'what I do' and 'who I am'"],
    hiddenStrength: "Burnout, when honestly faced, often becomes the catalyst for a genuine re-evaluation of what matters — something that the driven, high-functioning person in normal circumstances could not have accessed. The collapse creates the space for something more sustainable, more authentic, and more genuinely nourishing to be rebuilt.",
    whatHelps: ["Treating recovery as a genuine priority rather than a luxury", "Examining whether the source of the exhaustion is external overload, internal drive, or both", "Reconnecting to intrinsic motivation by asking what would be done even without recognition or reward", "Addressing the underlying belief that value is contingent on productivity"],
    journalQuestion: "When did you last feel genuinely rested and replenished — and what would it take to give yourself that kind of restoration now?",
    affirmation: "I am not what I produce — I am valuable in my being.",
    astrologicalRoots: "Sun-Pluto squares, Mars conjunct Saturn, or 6th house stelliums often correspond with the drive-toward-burnout pattern. These placements carry enormous capacity for sustained effort and meaningful contribution — and the growth edge is learning to honor the body's and soul's need for regenerative rest alongside the drive.",
  },
  {
    id: "money_stress",
    title: "Money Stress",
    subtitle: "Where finances carry the weight of deeper questions about security and worth.",
    feelsLike: "A background anxiety that rarely fully turns off — the constant awareness of whether there is enough, punctuated by anxiety when unexpected expenses arrive and rarely fully relieved by financial improvement. Money stress often carries a story beneath it: about safety, about value, about whether one deserves abundance.",
    whereItShowsUp: ["Financial decisions made from fear rather than strategy", "Avoiding looking at financial reality because of the anxiety it triggers", "Work choices driven by security fears rather than genuine fit", "Difficulty spending on oneself even when resources are available"],
    triggerPatterns: ["Unexpected expenses or financial setbacks", "Comparison to others' apparent financial ease", "The approach of financial obligations", "Periods when income is uncertain or irregular"],
    hiddenStrength: "Those who have genuinely navigated financial difficulty often develop a depth of resourcefulness, practical wisdom, and relationship with what actually matters that those who have always had security may not fully access. The experience of scarcity, when it doesn't create permanent contraction, can produce an unusual appreciation for genuine abundance.",
    whatHelps: ["Separating financial reality from the story about what that reality means about you", "Building a simple, clear picture of financial reality rather than avoiding it", "Addressing underlying beliefs about worthiness and abundance", "Distinguishing between emergency financial management and long-term financial flourishing"],
    journalQuestion: "What story do you carry about money and security — and where did you inherit that story?",
    affirmation: "Abundance flows to those who believe they deserve it — and I am learning to believe.",
    astrologicalRoots: "Saturn or Pluto in the 2nd house, Venus-Pluto aspects, or challenging South Node placements in earth signs often accompany complex relationships with money and material security. These configurations suggest a soul working through deep questions about self-worth and what it means to have and to hold.",
  },
  {
    id: "clarity",
    title: "Lack of Clarity",
    subtitle: "Standing at the crossroads with too many possibilities and no clear compass.",
    feelsLike: "A fog of too many possibilities, competing desires, or conflicting voices that prevents clear direction from emerging. The indecision is often experienced not as emptiness but as an overwhelm of options — too many things feeling important, too many paths seeming viable, with no obvious way to choose.",
    whereItShowsUp: ["Difficulty making significant decisions, even when the options are reasonably clear", "Changing direction frequently without completing any one path", "Seeking guidance from many sources and then being more confused by the variety", "A chronic sense of 'not knowing what I want'"],
    triggerPatterns: ["Significant life decisions where any choice forecloses others", "Periods of genuine life transition when the old map no longer applies", "Circumstances where multiple people have competing strong opinions", "Times of significant inner change when the old values no longer feel fully accurate"],
    hiddenStrength: "Those who struggle most with clarity often do so because they genuinely feel the full weight of complexity — they cannot oversimplify because they actually see multiple legitimate perspectives and possibilities. When direction does emerge from this fullness, it tends to be considered, nuanced, and genuine rather than impulsive.",
    whatHelps: ["Moving from the question 'what do I want?' to the question 'what matters most?'", "Making the smallest possible next decision rather than trying to resolve everything at once", "Spending time in genuine quiet — clarity rarely comes from more thinking, but from less", "Identifying which voice is yours and which voices belong to others"],
    journalQuestion: "If you already knew the answer — if a clear voice inside you knew exactly what was right — what would it say?",
    affirmation: "I trust the quiet knowing that exists beneath the noise.",
    astrologicalRoots: "Mercury-Neptune aspects, a mutable grand cross, or heavy Pisces/12th house emphasis often accompany clarity challenges. These configurations suggest a highly permeable, impressionable quality of consciousness that can struggle to locate its own center — and the journey is developing the capacity to trust the quiet voice beneath the noise.",
  },
  {
    id: "perfectionism",
    title: "Perfectionism",
    subtitle: "The pursuit of excellence that tips into the fear of being flawed.",
    feelsLike: "An internal standard that is always slightly ahead of what you can actually produce — so that no matter how good the work is, it never quite reaches the place where it feels genuinely finished, genuinely good enough, or genuinely safe to release. The standard protects against criticism but also against completion.",
    whereItShowsUp: ["Work that is perpetually 'almost ready' but never quite done", "Excessive revision that passes the point of improvement into avoidance", "Difficulty delegating because no one else will do it quite the same way", "Self-criticism that is disproportionate to the actual imperfection"],
    triggerPatterns: ["Situations with public visibility where the stakes of being seen as inadequate feel high", "Feedback, even gentle, that confirms an imperfection", "Creative work where the standard of comparison is very high", "New areas of learning where beginner-hood is unavoidable"],
    hiddenStrength: "Perfectionism is often the shadow side of genuine excellence — a commitment to quality and mastery that can produce remarkable work when it is in its healthy expression. When the perfectionist learns to direct their high standards toward aspiration rather than self-punishment, they often become among the finest craftspeople in their domain.",
    whatHelps: ["Distinguishing between the standard of excellence and the standard of impossibility", "Practicing 'good enough' in contexts where the stakes are genuinely low", "Examining whose approval the perfectionism was originally seeking", "Understanding that the work you never release helps no one"],
    journalQuestion: "What does 'good enough' feel like in your body — and what is the earliest memory you have of someone implying that what you produced wasn't adequate?",
    affirmation: "Done and imperfect is more powerful than perfect and imagined.",
    astrologicalRoots: "Virgo placements — particularly Sun, Moon, or Mercury in Virgo — combined with Saturn aspects often create the perfectionist pattern. These placements carry a genuine gift for discernment and quality; the shadow is the inner critic that mistakes its high standards for the whole truth of a person's worth.",
  },
  {
    id: "people_pleasing",
    title: "People-Pleasing",
    subtitle: "The strategy that keeps everyone happy except you.",
    feelsLike: "A constant monitoring of others' emotional states and an impulse to manage them — to smooth over discomfort, to be whatever the room needs, to ensure no one is upset in ways that might be traceable to you. There is often a deep tiredness beneath this that is hard to acknowledge because the strategy feels like kindness.",
    whereItShowsUp: ["Saying yes when you mean no, and then resenting it", "Adjusting your opinions in the presence of strong personalities", "Finding it difficult to maintain a position when someone is visibly displeased", "Taking responsibility for others' emotional reactions to things you've said or done"],
    triggerPatterns: ["Someone expressing disappointment or disapproval, especially someone whose approval matters", "Conflict that seems likely to make someone think poorly of you", "Situations where your truth and others' comfort are in opposition", "New relationships where the need to be liked overrides honest self-expression"],
    hiddenStrength: "The people-pleaser's deep attunement to what others need, when it is freed from the obligation to always provide it, becomes a genuine superpower of social intelligence and empathy. The skill is not the problem — it is the compulsiveness that has attached to it. When the choice to care for others becomes genuinely voluntary, it is one of the most beautiful capacities a person can have.",
    whatHelps: ["Noticing the difference between genuine desire to help and fear-based compliance", "Building a relationship with your own opinions, preferences, and desires as something worth knowing and expressing", "Practicing the small, honest 'no' that doesn't require explanation", "Understanding that allowing others to experience disappointment is an act of respect, not cruelty"],
    journalQuestion: "Whose approval are you most afraid of losing — and what do you believe would happen to the relationship if they saw all of who you really are?",
    affirmation: "My truth is worth speaking — even when someone is uncomfortable hearing it.",
    astrologicalRoots: "Libra placements, particularly Moon or Sun in Libra, Venus-Neptune aspects, or significant 12th house emphasis often correspond with people-pleasing patterns. These configurations carry a genuine gift for diplomacy and emotional attunement; the journey is learning that authentic connection requires showing up as yourself rather than as whoever the situation seems to require.",
  },
  {
    id: "fear_of_change",
    title: "Fear of Change",
    subtitle: "Choosing the familiar cage over the uncertain open sky.",
    feelsLike: "A strong pull toward the known, even when the known is not working — the preference for the devil you know over the devil you don't, even when the devil you don't know might actually turn out to be an angel. Transition periods, even positive ones, feel destabilizing and threatening in ways that seem disproportionate to others.",
    whereItShowsUp: ["Staying in situations (jobs, relationships, places) past the point where they serve you", "Rationalizing delay when a change has already been decided internally", "Experiencing significant anxiety during even welcome transitions", "Placing high value on stability even at the cost of growth"],
    triggerPatterns: ["The approach of a significant transition even when it was chosen", "Unexpected changes that arrive without being prepared for", "Situations where the outcome of a change is genuinely uncertain", "Times when someone close is also in change and the collective instability feels overwhelming"],
    hiddenStrength: "The depth of attachment to the known, when worked through rather than surrendered to, often produces an unusual appreciation for what is genuinely worth preserving amid change. People who have faced and integrated fear of change often become extraordinary anchors for others during turbulent times — because they have learned, at cost, what is actually stable.",
    whatHelps: ["Building trust in your capacity to navigate the unknown through small, chosen changes", "Distinguishing between legitimate caution and fear-based avoidance", "Examining what specifically feels threatening about the change", "Finding the parts of yourself that are unchanging, regardless of outer circumstances"],
    journalQuestion: "What is the change you most know you need to make — and what are you most afraid you would have to face if you made it?",
    affirmation: "I have navigated every change that has come to me so far — and I will navigate what comes next.",
    astrologicalRoots: "Fixed sign emphasis — particularly Taurus, Scorpio, Leo, or Aquarius placements — Saturn in the 1st or 4th house, or strong 2nd house emphasis often correspond with deep resistance to change. These configurations carry extraordinary gifts of loyalty, stability, and endurance; the growth edge is learning that the thing that makes you reliable also makes you slow to adapt, and that adaptation is not the same as betrayal of values.",
  },
  {
    id: "emotional_avoidance",
    title: "Emotional Avoidance",
    subtitle: "The art of staying comfortable by staying on the surface.",
    feelsLike: "A particular comfort with thoughts, logic, activity, and practical matters — combined with discomfort, impatience, or a blank quality when emotions are required. Feelings may be present but quickly routed away from consciousness through busyness, rationalization, humor, or distraction. There can be a sense of watching oneself from a slight distance.",
    whereItShowsUp: ["Moving quickly from feeling to analysis, skipping the actual feeling", "Discomfort in conversations that require emotional depth or vulnerability", "Using intellectual frameworks to manage what is actually an emotional experience", "Relationships where intimacy is intellectual but not emotionally vulnerable"],
    triggerPatterns: ["Being asked how you feel rather than what you think", "Situations requiring vulnerability with someone whose response cannot be predicted", "Grief, loss, or disappointment that cannot be logically resolved", "Others expressing strong emotion in close proximity"],
    hiddenStrength: "Emotional avoidance, when it is the product of a highly developed thinking function rather than pure suppression, often indicates someone with genuine intellectual and analytical gifts. When the emotional world is eventually allowed access to this intelligence, the result can be remarkable — someone capable of both deep feeling and the insight to make meaning from it.",
    whatHelps: ["Body-forward practices that access emotion through sensation rather than thought: breathwork, movement, somatic therapy", "Giving emotions names without immediately needing to solve or explain them", "Distinguishing between the discomfort of unfamiliar emotional territory and actual danger", "Finding safe people with whom to practice staying in the feeling longer"],
    journalQuestion: "What is the feeling you are most reluctant to feel fully — and what do you believe would happen if you actually let yourself feel it?",
    affirmation: "My emotions are messengers, not threats — and I am safe enough to hear what they're saying.",
    astrologicalRoots: "Strong air sign emphasis (Gemini, Libra, Aquarius), Aquarius Moon, or Saturn-Moon aspects often correspond with emotional avoidance patterns. These configurations carry real gifts of mental clarity and objectivity; the growth edge is discovering that emotional experience doesn't threaten the intellect — it enriches it.",
  },
];
