export interface CompatibilityAspect {
  planetA: string;
  planetB: string;
  aspect: string;
  strengthCategory: "bonding" | "passion" | "growth" | "communication" | "stability";
  tensionCategory?: "power" | "friction" | "avoidance" | "intensity";
  meaning: string;
  communicationEffect: string;
  emotionalEffect: string;
  adviceAngle: string;
  isSynastryHighlight: boolean;
}

export const COMPATIBILITY_ASPECTS: CompatibilityAspect[] = [
  // Venus-Moon
  {
    planetA: "Venus",
    planetB: "Moon",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "One of the most tender and emotionally nourishing connections in synastry. Venus brings beauty, affection, and aesthetic sensibility directly into the other's emotional core. Both people feel genuinely comfortable and cared for in each other's presence.",
    communicationEffect: "Conversations feel warm and affirming. There's a natural gentleness in how these two speak to each other — even difficult topics are addressed with care.",
    emotionalEffect: "Deep emotional resonance and mutual nurturing. Both people feel seen and cherished at a level that bypasses the need for explanation.",
    adviceAngle: "Honor the tenderness this connection creates. Don't take the ease for granted — it is rarer than it looks.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Venus",
    planetB: "Moon",
    aspect: "square",
    strengthCategory: "growth",
    tensionCategory: "friction",
    meaning: "The affection is real but the love languages differ significantly. What feels caring to one person may feel smothering, intrusive, or indifferent to the other. Both people want connection but their expressions of it create inadvertent friction.",
    communicationEffect: "Mismatches in tone can make conversations about emotional needs feel like criticism rather than care.",
    emotionalEffect: "Alternating periods of warmth and disconnect — as if the emotional dial is perpetually slightly out of tune.",
    adviceAngle: "Get explicit about your love languages. The care between you is real — it simply needs translation.",
    isSynastryHighlight: false,
  },
  // Venus-Mars
  {
    planetA: "Venus",
    planetB: "Mars",
    aspect: "conjunction",
    strengthCategory: "passion",
    meaning: "Magnetic, powerful attraction that is both physical and emotional. The Venusian person feels wanted; the Martian person feels magnetically drawn. This is the classic romantic and sexual attraction overlay — the connection that makes people say 'there's just something about them.'",
    communicationEffect: "Communication is charged and magnetic — even ordinary conversations can feel flirtatious and alive.",
    emotionalEffect: "Intense desire combined with genuine affection. The passion can be consuming, which is its greatest gift and its greatest vulnerability.",
    adviceAngle: "Build the friendship alongside the passion. The attraction is real — depth and commitment will make it sustainable.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Venus",
    planetB: "Mars",
    aspect: "trine",
    strengthCategory: "passion",
    meaning: "Passionate, harmonious attraction that flows easily without the volatility of a square. These two bring out each other's romantic and creative best without the intensity tipping into difficulty.",
    communicationEffect: "Playful, warm, and naturally affectionate. Conversations carry an undercurrent of mutual appreciation.",
    emotionalEffect: "Sustained warmth and desire — the passion doesn't require drama to stay alive.",
    adviceAngle: "The ease of this connection is a gift worth investing in. It creates space for genuine depth to develop.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Venus",
    planetB: "Mars",
    aspect: "square",
    strengthCategory: "passion",
    tensionCategory: "friction",
    meaning: "Undeniable chemistry and tension that runs through the connection — attraction that is also frustrating, desire that is also combative. The square creates a push-pull dynamic that can be exhausting and irresistible in equal measure.",
    communicationEffect: "Conversations about wants and needs can easily escalate — both people feel their desires are real and potentially incompatible.",
    emotionalEffect: "Electrifying passion combined with genuine conflict. The intensity can feel addictive.",
    adviceAngle: "Learn to distinguish between productive friction and destructive conflict. The passion is real — but it requires maturity to channel.",
    isSynastryHighlight: true,
  },
  // Sun-Moon
  {
    planetA: "Sun",
    planetB: "Moon",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "One of the most significant and meaningful synastry aspects. The Sun person feels like home to the Moon person; the Moon person's emotional needs and instincts feel deeply in sync with the Sun person's identity. This is the aspect of deep mutual recognition.",
    communicationEffect: "A quality of being known by each other that doesn't require explanation — conversation feels like coming home.",
    emotionalEffect: "The Moon person feels emotionally nourished and recognized. The Sun person feels their identity affirmed and appreciated in a way that goes deeper than admiration.",
    adviceAngle: "This is the connection that makes people believe in soulmates. Honor it with the maturity and investment it deserves.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Sun",
    planetB: "Moon",
    aspect: "opposition",
    strengthCategory: "bonding",
    meaning: "A mirror aspect — each person sees in the other something they carry in shadow. There is magnetic attraction rooted in the sense of complementarity. These people can be extraordinarily well-matched if each can see their own reflection honestly.",
    communicationEffect: "Fascinating and sometimes frustrating — like talking to a version of yourself that chose the other direction.",
    emotionalEffect: "Alternating identification and projection. Deep connection and occasional bewilderment at how different they feel from each other.",
    adviceAngle: "Neither of you is wrong — you are complementary. The growth is in learning from the other's different way of being.",
    isSynastryHighlight: true,
  },
  // Sun-Sun
  {
    planetA: "Sun",
    planetB: "Sun",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "Two people with the same Sun sign — deeply understanding of each other's core nature, rhythms, and values. The familiarity can be immediately comfortable and also illuminate blindspots that each carries in their shared sign.",
    communicationEffect: "Instant understanding of how the other fundamentally operates — which can feel validating and occasionally like looking in a mirror that shows what you'd rather not see.",
    emotionalEffect: "A feeling of being genuinely known and understood at the identity level.",
    adviceAngle: "Celebrate what you share — and be curious about the differences in how the same sign expresses in two unique people.",
    isSynastryHighlight: false,
  },
  {
    planetA: "Sun",
    planetB: "Sun",
    aspect: "trine",
    strengthCategory: "stability",
    meaning: "Sharing the same elemental expression creates natural ease and mutual understanding. These people fundamentally 'get' each other — how they approach life, what energizes them, and what drains them are all naturally compatible.",
    communicationEffect: "Easy and natural — rarely do they have to translate themselves for each other.",
    emotionalEffect: "A sense of comfortable recognition — like recognizing a member of your own tribe.",
    adviceAngle: "Ease can create complacency. Consciously seek growth through differences as well as celebrating the natural harmony.",
    isSynastryHighlight: false,
  },
  {
    planetA: "Sun",
    planetB: "Sun",
    aspect: "square",
    strengthCategory: "growth",
    tensionCategory: "friction",
    meaning: "Different modalities creating productive friction — both people are activated by each other's way of being in the world, which produces tension and also the spark of genuine engagement.",
    communicationEffect: "Lively and sometimes combative — these two often see things very differently.",
    emotionalEffect: "Mutual activation and occasional exasperation. The friction is real and so is the chemistry.",
    adviceAngle: "The person who challenges you most may also be developing you most. Curiosity about the difference matters more than winning.",
    isSynastryHighlight: false,
  },
  // Moon-Moon
  {
    planetA: "Moon",
    planetB: "Moon",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "Sharing the same Moon sign means sharing the same emotional language — the same comfort needs, the same instinctive responses, the same way of processing feeling. This creates profound mutual understanding and, potentially, mirroring of both strengths and patterns.",
    communicationEffect: "Emotional communication is nearly effortless — each person intuitively understands the other's emotional needs.",
    emotionalEffect: "Deep emotional attunement and safety. The risk is co-reinforcing rather than growing beyond shared patterns.",
    adviceAngle: "The depth of mutual understanding here is precious. Also bring in the complementary perspectives that make growth possible.",
    isSynastryHighlight: false,
  },
  {
    planetA: "Moon",
    planetB: "Moon",
    aspect: "trine",
    strengthCategory: "bonding",
    meaning: "Shared elemental emotional expression — these people feel emotions in the same basic register. Home feels like home with each other.",
    communicationEffect: "Emotionally comfortable and easy to be vulnerable with.",
    emotionalEffect: "A sense of natural emotional attunement without having to explain oneself.",
    adviceAngle: "Build on this foundation of ease — but ensure you are both also growing.",
    isSynastryHighlight: false,
  },
  // Venus-Venus
  {
    planetA: "Venus",
    planetB: "Venus",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "Shared taste, values, and aesthetic sensibility create an immediate sense of resonance. These people instinctively appreciate the same things and express affection in mutually recognizable ways.",
    communicationEffect: "Warm and appreciative — conversations about what you love flow naturally.",
    emotionalEffect: "A deep sense of being valued and understood in how you express and receive love.",
    adviceAngle: "The shared values here are a strong foundation. Use them to build something genuinely meaningful together.",
    isSynastryHighlight: false,
  },
  // Mercury-Mercury
  {
    planetA: "Mercury",
    planetB: "Mercury",
    aspect: "conjunction",
    strengthCategory: "communication",
    meaning: "These people think in the same register — similar speeds of processing, similar communication styles, similar humor. Conversations feel effortless and stimulating.",
    communicationEffect: "Almost telepathic at times — they finish each other's sentences and reach the same conclusions simultaneously.",
    emotionalEffect: "The feeling of being genuinely mentally met — which is its own form of intimacy.",
    adviceAngle: "Mental compatibility is a powerful glue. Also invest in the emotional and physical layers of connection.",
    isSynastryHighlight: false,
  },
  {
    planetA: "Mercury",
    planetB: "Mercury",
    aspect: "square",
    strengthCategory: "communication",
    tensionCategory: "friction",
    meaning: "Different communication styles that can feel like speaking different languages — one is direct where the other is indirect, or one talks to think while the other thinks before talking.",
    communicationEffect: "Misunderstandings are more frequent and can be more frustrating because both people feel they are communicating clearly.",
    emotionalEffect: "Occasional frustration and the rewarding sense when genuine understanding is achieved despite the difference.",
    adviceAngle: "The communication difference is real — learn each other's styles explicitly rather than assuming the other communicates the same way you do.",
    isSynastryHighlight: false,
  },
  // Sun-Venus
  {
    planetA: "Sun",
    planetB: "Venus",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "The Venusian person genuinely appreciates and is charmed by the Sun person's identity. The Sun person feels seen and celebrated. This is the aspect of genuine mutual appreciation.",
    communicationEffect: "Warm, admiring, and genuinely appreciative — each person brings out the other's best in conversation.",
    emotionalEffect: "The Sun person feels genuinely cherished. The Venus person feels genuinely inspired.",
    adviceAngle: "This is a gift of genuine admiration that can sustain a relationship through difficulty. Honor it.",
    isSynastryHighlight: true,
  },
  // Moon-Mars
  {
    planetA: "Moon",
    planetB: "Mars",
    aspect: "conjunction",
    strengthCategory: "passion",
    meaning: "Intense emotional and physical connection — the Martian person activates something deep and primal in the Moon person. This can be powerfully bonding or activating of emotional reactivity, depending on the developmental level of both people.",
    communicationEffect: "Conversations can quickly become emotionally charged — in both the exciting and the volatile sense.",
    emotionalEffect: "Deep emotional activation. The Moon person may feel simultaneously protected and overwhelmed.",
    adviceAngle: "The intensity here is real and needs conscious channeling. Learn to distinguish passion from reactivity.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Moon",
    planetB: "Mars",
    aspect: "square",
    strengthCategory: "growth",
    tensionCategory: "friction",
    meaning: "Emotionally activating and friction-producing — the Martian person's directness can feel aggressive to the Moon person; the Moon person's emotional sensitivity can feel overwhelming to the Mars person.",
    communicationEffect: "Emotional conversations can escalate quickly, with both people feeling they are the more reasonable one.",
    emotionalEffect: "Alternating periods of passionate connection and emotional reactivity.",
    adviceAngle: "The tension between these planets requires mutual sensitivity. Mars must learn to be gentler; Moon must learn to express needs directly.",
    isSynastryHighlight: false,
  },
  // Saturn-Moon
  {
    planetA: "Saturn",
    planetB: "Moon",
    aspect: "conjunction",
    strengthCategory: "stability",
    tensionCategory: "power",
    meaning: "A karmic, serious connection in which the Saturnian person either provides genuine stability to the Moon person or activates their deepest fears around emotional security. This aspect can produce lasting commitment and also significant emotional difficulty.",
    communicationEffect: "The Moon person may feel restricted or judged in emotional expression. The Saturn person may feel pulled by needs they can't fully meet.",
    emotionalEffect: "Deep emotional seriousness — this relationship teaches both people something essential about emotional maturity and boundaries.",
    adviceAngle: "Examine whether the Saturn person's structure is genuinely supporting the Moon person's emotional needs or inadvertently suppressing them.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Saturn",
    planetB: "Moon",
    aspect: "trine",
    strengthCategory: "stability",
    meaning: "Saturn's structure meets the Moon's emotional needs in a supportive way — the reliability and consistency that the Moon person deeply needs is provided naturally by the Saturnian person.",
    communicationEffect: "Conversations are honest and grounded — there is a reliability to how these two speak to each other.",
    emotionalEffect: "The Moon person feels genuinely secure. The Saturn person feels their steadiness is genuinely appreciated.",
    adviceAngle: "The stability here is a genuine gift. Ensure it doesn't tip into predictability at the expense of warmth and spontaneity.",
    isSynastryHighlight: true,
  },
  // Saturn-Venus
  {
    planetA: "Saturn",
    planetB: "Venus",
    aspect: "conjunction",
    strengthCategory: "stability",
    tensionCategory: "power",
    meaning: "A serious and potentially long-lasting romantic connection that carries both the gift of commitment and the challenge of emotional restriction. The Saturn person either provides the loving structure the Venus person needs, or inadvertently limits their expression of love.",
    communicationEffect: "Serious and earnest — these two don't do superficial. The depth of conversation is one of this connection's greatest gifts.",
    emotionalEffect: "The Venus person may feel their warmth is valued but also constrained. The Saturn person may struggle with the softness the Venus person needs.",
    adviceAngle: "The commitment potential here is real. The growth is in ensuring the structure Saturn brings creates safety rather than limitation.",
    isSynastryHighlight: true,
  },
  // Jupiter-Sun
  {
    planetA: "Jupiter",
    planetB: "Sun",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "The Jupiter person genuinely inspires, expands, and believes in the Sun person. This is the connection of the encouraging teacher — the Sun person feels bigger, more capable, and more optimistic in the presence of the Jupiter person.",
    communicationEffect: "Expansive, encouraging, and energizing — conversations tend to inspire rather than deflate.",
    emotionalEffect: "The Sun person feels genuinely seen in their potential. The Jupiter person feels purposefully placed in this person's life.",
    adviceAngle: "One of the most genuinely uplifting connections in synastry. Ensure the encouragement is grounded in reality.",
    isSynastryHighlight: true,
  },
  // Pluto-Venus
  {
    planetA: "Pluto",
    planetB: "Venus",
    aspect: "conjunction",
    strengthCategory: "passion",
    tensionCategory: "intensity",
    meaning: "One of the most intense synastry overlays — the Venus person undergoes profound transformation through this relationship, and the Pluto person holds enormous influence over the Venus person's feelings about themselves. This connection is rarely neutral.",
    communicationEffect: "Conversations can reach extraordinary depth — or become power-laden and manipulative. The line between the two requires vigilance.",
    emotionalEffect: "The Venus person may feel consumed, transformed, or both. Jealousy, obsession, and deep love often coexist.",
    adviceAngle: "The depth here is real. Ensure the power dynamic remains mutual and conscious — Pluto's influence on Venus requires careful tending.",
    isSynastryHighlight: true,
  },
  {
    planetA: "Pluto",
    planetB: "Venus",
    aspect: "trine",
    strengthCategory: "passion",
    meaning: "Transformative love that deepens over time without the volatility of a hard aspect. The Venus person is positively transformed by the depth and intensity the Pluto person brings.",
    communicationEffect: "Deep, honest, and probing — conversations reveal rather than conceal.",
    emotionalEffect: "A love that genuinely changes both people in lasting ways.",
    adviceAngle: "This depth is genuinely rare. Honor it with the vulnerability and honesty it calls for.",
    isSynastryHighlight: false,
  },
  // Pluto-Moon
  {
    planetA: "Pluto",
    planetB: "Moon",
    aspect: "conjunction",
    strengthCategory: "bonding",
    tensionCategory: "intensity",
    meaning: "An intensely deep and potentially transformative connection at the emotional roots. The Pluto person touches the Moon person's deepest emotional patterns — this can be profoundly healing or can activate old wounds.",
    communicationEffect: "Conversations can reach the deepest emotional levels — or become psychologically loaded and power-tinged.",
    emotionalEffect: "The Moon person feels both exposed and understood at a level that can be overwhelming. Obsession and deep love are often intertwined.",
    adviceAngle: "This connection requires psychological awareness from both people. The depth is extraordinary — the responsibility that comes with it is equally so.",
    isSynastryHighlight: true,
  },
  // Neptune-Venus
  {
    planetA: "Neptune",
    planetB: "Venus",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "Romantic idealization at its most potent — this connection feels fated, transcendent, and sometimes more dream than reality. The Venus person sees the Neptune person as magical, mysterious, and potentially messianic. The Neptune person carries the projection without always being able to live up to it.",
    communicationEffect: "Beautiful, evocative, and sometimes unclear. Communication here needs grounding or misunderstandings multiply.",
    emotionalEffect: "Deeply romantic and occasionally illusory. The love is real — the perception of who the other person actually is may not be.",
    adviceAngle: "Allow yourself to love the real person, not only the dream. Neptune connections that survive the disillusionment of reality often become the most genuinely beautiful.",
    isSynastryHighlight: true,
  },
  // Chiron-Moon
  {
    planetA: "Chiron",
    planetB: "Moon",
    aspect: "conjunction",
    strengthCategory: "growth",
    tensionCategory: "intensity",
    meaning: "This connection directly activates the other's core emotional wound — sometimes the most healing connection possible, sometimes the most activating. Both people sense a quality of deep, old recognition in this meeting.",
    communicationEffect: "Conversations can touch places in both people that aren't usually accessible — this is both its gift and its demand.",
    emotionalEffect: "The Moon person may feel their deepest vulnerability both seen and potentially stirred. Healing and difficulty often arrive together.",
    adviceAngle: "This connection has profound healing potential when both people are ready to engage with what it activates. It requires care, consciousness, and mutual commitment.",
    isSynastryHighlight: true,
  },
  // Sun-Ascendant
  {
    planetA: "Sun",
    planetB: "Ascendant",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "The Sun person shines a light on the Ascendant person's identity — there is a quality of genuine recognition and visibility that makes the Ascendant person feel truly seen. The Sun person feels like they belong with the Ascendant person.",
    communicationEffect: "Natural and easy — these people present themselves authentically with each other.",
    emotionalEffect: "A feeling of genuine recognition — the Ascendant person feels more themselves in the Sun person's presence.",
    adviceAngle: "This connection supports the Ascendant person's ongoing becoming. Honor the visibility it creates.",
    isSynastryHighlight: true,
  },
  // Venus-Ascendant
  {
    planetA: "Venus",
    planetB: "Ascendant",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "The Venus person finds the Ascendant person deeply attractive — often immediately. The Ascendant person feels genuinely appreciated and seen as beautiful or valuable by the Venus person.",
    communicationEffect: "Gracious and warm — the Venus person naturally brings out the Ascendant person's most appealing self.",
    emotionalEffect: "The Ascendant person feels attractive and valued. The Venus person feels drawn toward someone who represents what they find beautiful.",
    adviceAngle: "The beauty this connection activates is real. Build depth alongside the initial attraction.",
    isSynastryHighlight: true,
  },
  // Moon-Ascendant
  {
    planetA: "Moon",
    planetB: "Ascendant",
    aspect: "conjunction",
    strengthCategory: "bonding",
    meaning: "The Moon person feels emotionally at home with the Ascendant person — almost immediately. The Ascendant person carries something that speaks to the Moon person's deepest emotional needs.",
    communicationEffect: "Warm, comfortable, and emotionally immediate — like being with someone you've known forever.",
    emotionalEffect: "Deep emotional ease and a natural sense of safety in each other's presence.",
    adviceAngle: "This sense of emotional home is precious. Nurture it with consistent care and attention.",
    isSynastryHighlight: true,
  },
];
