export interface EventRule {
  eventType: string;
  planet?: string;
  titlePattern: string;
  significanceBase: number;
  significanceModifiers: {
    conjunctsNatalSun: number;
    conjunctsNatalMoon: number;
    conjunctsNatalRising: number;
    inKeyHouse: number;
  };
  category: "love" | "communication" | "career" | "inner_work" | "emotional_reset" | "major_change" | "expansion";
  plainEnglishMeaning: string;
  suggestedActionStyle: string;
  cautionNote: string;
  durationNote: string;
}

export const EVENT_RULES: EventRule[] = [
  {
    eventType: "retrograde",
    planet: "Mercury",
    titlePattern: "Mercury Retrograde in {sign}",
    significanceBase: 3,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 1,
      conjunctsNatalRising: 2,
      inKeyHouse: 1,
    },
    category: "communication",
    plainEnglishMeaning: "Mercury, the planet of communication and technology, appears to move backward from Earth's perspective. This three-week period is famous for misunderstandings, technology glitches, travel delays, and the resurfacing of past conversations or contacts. It's not a time of bad luck — it's a time for review, revision, and reflection rather than new launches.",
    suggestedActionStyle: "review and revise before proceeding",
    cautionNote: "Avoid signing important contracts, launching major new projects, or making large technology purchases if possible. Double-check all communications before sending.",
    durationNote: "Approximately 3 weeks, plus a 2-week 'shadow' period before and after when the effects are beginning or fading.",
  },
  {
    eventType: "retrograde",
    planet: "Venus",
    titlePattern: "Venus Retrograde in {sign}",
    significanceBase: 4,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 2,
      inKeyHouse: 2,
    },
    category: "love",
    plainEnglishMeaning: "Venus retrograde happens every 18 months and asks us to revisit what we value and how we love. Old relationships or relationship patterns from the past often resurface. This is not usually a good time for new romantic commitments but is excellent for deepening existing relationships or gaining clarity about what you truly want in love and life.",
    suggestedActionStyle: "reflect on values and relationships before committing",
    cautionNote: "Avoid major cosmetic procedures, significant purchases, or rushing into new romantic commitments during this period.",
    durationNote: "Approximately 6 weeks.",
  },
  {
    eventType: "retrograde",
    planet: "Mars",
    titlePattern: "Mars Retrograde in {sign}",
    significanceBase: 4,
    significanceModifiers: {
      conjunctsNatalSun: 3,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 3,
      inKeyHouse: 2,
    },
    category: "inner_work",
    plainEnglishMeaning: "Mars retrograde, happening every two years, redirects our drive and ambition inward for reassessment. This is a period when external action and assertion become less effective — energy is better spent reviewing projects, strategies, and the nature of your desires rather than pushing forward.",
    suggestedActionStyle: "reassess before acting; conserve energy strategically",
    cautionNote: "Avoid starting new major initiatives, making impulsive decisions, or engaging in unnecessary conflict. Physical energy may be lower — honor rest.",
    durationNote: "Approximately 10 weeks.",
  },
  {
    eventType: "retrograde",
    planet: "Jupiter",
    titlePattern: "Jupiter Retrograde in {sign}",
    significanceBase: 3,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 1,
      conjunctsNatalRising: 2,
      inKeyHouse: 1,
    },
    category: "inner_work",
    plainEnglishMeaning: "Jupiter retrograde is a quieter period for outward expansion, turning growth and philosophical exploration inward. This is a time for reviewing beliefs, revisiting philosophical questions, and consolidating gains from the previous expansion phase rather than seeking new territory.",
    suggestedActionStyle: "review beliefs and consolidate inner growth",
    cautionNote: "Avoid overextending financially or making large speculative bets. Inner abundance deserves as much attention as outer expansion.",
    durationNote: "Approximately 4 months per year.",
  },
  {
    eventType: "retrograde",
    planet: "Saturn",
    titlePattern: "Saturn Retrograde in {sign}",
    significanceBase: 3,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 2,
      inKeyHouse: 2,
    },
    category: "inner_work",
    plainEnglishMeaning: "Saturn retrograde turns the planet of discipline and structure inward, creating a period of internal review of responsibilities, commitments, and the structures of your life. Issues that were being delayed or avoided often become unavoidable. This is a time for honest reckoning with what is truly being built.",
    suggestedActionStyle: "review commitments and inner discipline",
    cautionNote: "Old responsibilities and limitations may resurface for final processing. This is the time to address, not avoid, what Saturn is revealing.",
    durationNote: "Approximately 4.5 months per year.",
  },
  {
    eventType: "full_moon",
    planet: undefined,
    titlePattern: "Full Moon in {sign}",
    significanceBase: 3,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 3,
      conjunctsNatalRising: 2,
      inKeyHouse: 2,
    },
    category: "emotional_reset",
    plainEnglishMeaning: "The Full Moon marks the culmination and completion of a cycle that began at the New Moon two weeks prior. Emotions run high, what has been building comes to the surface, and situations that were in progress reach a natural peak. The sign the Full Moon occupies describes the themes that are being illuminated and completed.",
    suggestedActionStyle: "release, complete, and acknowledge what has come to fullness",
    cautionNote: "Emotional reactivity is naturally heightened during Full Moons. Give yourself more breathing room before responding to charged situations.",
    durationNote: "The exact Full Moon lasts 1-2 days, with the energy building and releasing over about a week.",
  },
  {
    eventType: "new_moon",
    planet: undefined,
    titlePattern: "New Moon in {sign}",
    significanceBase: 3,
    significanceModifiers: {
      conjunctsNatalSun: 3,
      conjunctsNatalMoon: 3,
      conjunctsNatalRising: 2,
      inKeyHouse: 2,
    },
    category: "expansion",
    plainEnglishMeaning: "The New Moon marks the beginning of a new lunar cycle and is the most potent time for setting intentions, planting seeds, and initiating what you want to grow over the coming month. The sign the New Moon occupies describes the area of life that is most supported for new beginnings.",
    suggestedActionStyle: "set intentions and initiate new beginnings",
    cautionNote: "Intentions set at New Moons tend to manifest over a 6-month arc through the Full Moon in the same sign. Be thoughtful about what you seed.",
    durationNote: "The exact New Moon lasts 1-2 days; the intentions set here are active for the next 28-day lunar cycle and fully manifest at the Full Moon in the same sign 6 months later.",
  },
  {
    eventType: "eclipse",
    planet: undefined,
    titlePattern: "Lunar Eclipse in {sign}",
    significanceBase: 5,
    significanceModifiers: {
      conjunctsNatalSun: 3,
      conjunctsNatalMoon: 3,
      conjunctsNatalRising: 3,
      inKeyHouse: 2,
    },
    category: "major_change",
    plainEnglishMeaning: "Lunar eclipses are supercharged Full Moons that mark significant turning points — endings, completions, and revelations that have a particularly lasting impact. Situations that have been building for months often reach a sudden culmination. The house and sign of the eclipse describe the life area undergoing significant change.",
    suggestedActionStyle: "observe and release; do not force outcomes during eclipses",
    cautionNote: "Eclipses are powerful and often bring events that couldn't have been predicted or controlled. The wisdom is in releasing resistance to what is unfolding rather than forcing a particular outcome.",
    durationNote: "Eclipses occur in pairs approximately every 6 months. Their effects can be felt weeks before and after the exact date, with lasting impact for 6 months to a year.",
  },
  {
    eventType: "eclipse",
    planet: undefined,
    titlePattern: "Solar Eclipse in {sign}",
    significanceBase: 5,
    significanceModifiers: {
      conjunctsNatalSun: 3,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 3,
      inKeyHouse: 2,
    },
    category: "major_change",
    plainEnglishMeaning: "Solar eclipses are supercharged New Moons that open doors to significant new chapters — new beginnings that are more fated and lasting than ordinary New Moon initiations. The old chapter is closing; a new one is beginning, often suddenly. The house and sign of the eclipse describe where your life is being reset and reinitiated.",
    suggestedActionStyle: "allow new chapters to begin; trust what is opening",
    cautionNote: "Solar eclipses can bring sudden changes of direction that weren't planned. The invitation is to trust the opening rather than trying to control it.",
    durationNote: "Effects felt for 6 months to a year following the eclipse.",
  },
  {
    eventType: "ingress",
    planet: "Jupiter",
    titlePattern: "Jupiter Enters {sign}",
    significanceBase: 4,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 2,
      inKeyHouse: 3,
    },
    category: "expansion",
    plainEnglishMeaning: "Jupiter moving into a new sign marks a year-long shift in the area of life receiving the planet's gifts of expansion, optimism, and opportunity. The new sign describes the flavor and focus of this growth phase — what areas of life are most ripe for expansion, learning, and good fortune over the coming year.",
    suggestedActionStyle: "initiate and invest in the themes of the new sign",
    cautionNote: "Jupiter expands whatever it touches — including excess and overextension. Seize opportunities with wisdom and boundaries.",
    durationNote: "Jupiter spends approximately 1 year in each sign.",
  },
  {
    eventType: "ingress",
    planet: "Saturn",
    titlePattern: "Saturn Enters {sign}",
    significanceBase: 5,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 2,
      inKeyHouse: 2,
    },
    category: "inner_work",
    plainEnglishMeaning: "Saturn moving into a new sign marks a 2.5-year period of testing, structure-building, and maturation in the life areas the sign governs. This is one of the most significant collective astrological shifts — the themes of the sign are where discipline, accountability, and the long game are most required over the coming years.",
    suggestedActionStyle: "build structures patiently; commit to long-term effort in the new sign's areas",
    cautionNote: "Saturn's entry into a new sign can initially feel like restriction or increased responsibility in its themes. The difficulty is the material from which something lasting is built.",
    durationNote: "Saturn spends approximately 2.5 years in each sign.",
  },
  {
    eventType: "ingress",
    planet: "Pluto",
    titlePattern: "Pluto Enters {sign}",
    significanceBase: 5,
    significanceModifiers: {
      conjunctsNatalSun: 3,
      conjunctsNatalMoon: 2,
      conjunctsNatalRising: 3,
      inKeyHouse: 3,
    },
    category: "major_change",
    plainEnglishMeaning: "Pluto's ingress into a new sign is a generational shift — a decades-long transformation of the collective structures, power dynamics, and deep psychological themes associated with the sign. This marks the beginning of a period where those themes undergo fundamental, often difficult, but ultimately regenerative transformation.",
    suggestedActionStyle: "align with transformation; face what needs to change in the sign's domains",
    cautionNote: "Pluto's transformations are rarely comfortable and often feel like loss before they feel like renewal. Resistance tends to make the process harder.",
    durationNote: "Pluto spends between 12 and 31 years in each sign.",
  },
  {
    eventType: "station",
    planet: "Mercury",
    titlePattern: "Mercury Stations {direction} in {sign}",
    significanceBase: 3,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 1,
      conjunctsNatalRising: 2,
      inKeyHouse: 1,
    },
    category: "communication",
    plainEnglishMeaning: "When Mercury stations — appears to pause in the sky before changing direction — its themes become intensified and concentrated. Communication, information, and mental processing feel particularly significant during these days. Something that needs to be said or understood is at a pivotal point.",
    suggestedActionStyle: "pay close attention to communication and information; speak and listen carefully",
    cautionNote: "The station period is often the most intense part of the retrograde cycle — important communications, realizations, or technology issues often cluster here.",
    durationNote: "A station lasts approximately 1-3 days but carries its intensity for about a week.",
  },
  {
    eventType: "aspect",
    planet: "Jupiter",
    titlePattern: "Jupiter {aspect} Saturn",
    significanceBase: 4,
    significanceModifiers: {
      conjunctsNatalSun: 2,
      conjunctsNatalMoon: 1,
      conjunctsNatalRising: 1,
      inKeyHouse: 2,
    },
    category: "expansion",
    plainEnglishMeaning: "Jupiter and Saturn in aspect represent the cosmic negotiation between expansion and limitation — the interplay of vision and practical reality. This aspect marks a moment when the desire to grow and the need to be sustainable are in direct conversation. It's an excellent time for grounded, realistic goal-setting.",
    suggestedActionStyle: "build ambitious structures with practical foundations",
    cautionNote: "Neither pure optimism nor pure caution serves this moment — the integration of both is what produces lasting results.",
    durationNote: "Jupiter-Saturn aspects occur over several weeks and are most powerful when exact.",
  },
];
