export interface TasseographySymbol {
  symbol: string;
  alternateNames: string[];
  themes: string[];
  positiveMeaning: string;
  shadowMeaning: string;
  domains: string[];
  reflectionQuestion: string;
  locationModifier: {
    nearHandle: string;
    oppositeHandle: string;
    nearRim: string;
    nearBottom: string;
  };
}

export const COFFEE_SYMBOLS: TasseographySymbol[] = [
  {
    symbol: "bird",
    alternateNames: ["dove", "eagle", "feather", "wings", "flying creature"],
    themes: ["freedom", "news", "aspiration", "communication", "elevation"],
    positiveMeaning: "A bird brings news of freedom, fresh perspective, or good news traveling toward you. It signals the soul's desire to rise above current limitations and see from a higher vantage point.",
    shadowMeaning: "A bird trapped or fallen may suggest feeling caged, or an important message that has been ignored or missed.",
    domains: ["communication", "personal", "travel"],
    reflectionQuestion: "Where in your life are you being called to rise above a current limitation and see from a higher perspective?",
    locationModifier: {
      nearHandle: "News or freedom related to home, close relationships, or personal life is imminent.",
      oppositeHandle: "A message or opportunity coming from a distance — from someone or somewhere outside your immediate circle.",
      nearRim: "Good news or an uplift in energy is approaching soon — within days or weeks.",
      nearBottom: "A long-standing desire for freedom or a message from the distant past is surfacing.",
    },
  },
  {
    symbol: "snake",
    alternateNames: ["serpent", "winding line", "coil"],
    themes: ["wisdom", "transformation", "hidden knowledge", "betrayal risk", "kundalini energy"],
    positiveMeaning: "The snake carries ancient wisdom — transformation through shedding what no longer serves, access to hidden knowledge, and the power of instinctual intelligence.",
    shadowMeaning: "May signal a deceptive person in the environment, or a situation where hidden motives are at play. Examine who around you may not be showing their full truth.",
    domains: ["personal", "love", "career"],
    reflectionQuestion: "What old identity, belief, or relationship are you being asked to shed so something new can emerge?",
    locationModifier: {
      nearHandle: "The transformation or deceptive dynamic is close to home — within your immediate environment.",
      oppositeHandle: "A more distant person or situation holds this energy — watch for it in professional or wider social contexts.",
      nearRim: "A transformation or revelation is approaching quickly.",
      nearBottom: "Deep-rooted patterns or ancient wisdom is being stirred — something that has long been hidden is ready to emerge.",
    },
  },
  {
    symbol: "heart",
    alternateNames: ["two curves", "valentine shape", "love symbol"],
    themes: ["love", "affection", "emotional truth", "commitment", "romance"],
    positiveMeaning: "The heart is one of the most welcome symbols — it signals love, affection, and emotional fulfillment. It may indicate a deepening of a current relationship or the arrival of new love.",
    shadowMeaning: "A broken or fractured heart shape suggests heartbreak, grief, or the need to heal before opening again.",
    domains: ["love", "personal", "family"],
    reflectionQuestion: "What does your heart truly long for that you have not yet allowed yourself to fully claim?",
    locationModifier: {
      nearHandle: "Love in your immediate environment — within current close relationships or home.",
      oppositeHandle: "Love coming from outside your current circle — a new connection approaching.",
      nearRim: "Romantic or emotional developments are near — pay attention to feelings arising in the next weeks.",
      nearBottom: "A deep longing for love that has been buried or an old love energy resurfacing.",
    },
  },
  {
    symbol: "star",
    alternateNames: ["five-pointed star", "asterisk", "starburst", "sparkle"],
    themes: ["hope", "guidance", "wishes", "destiny", "illumination"],
    positiveMeaning: "The star is among the most auspicious symbols — it brings hope, divine guidance, and the reassurance that you are moving in the right direction. Wishes made now carry particular power.",
    shadowMeaning: "A faint or unclear star may suggest that the direction you seek is there but requires more clarity or patience to discern.",
    domains: ["personal", "career", "love"],
    reflectionQuestion: "What star are you secretly wishing upon, and what one step would bring you closer to it?",
    locationModifier: {
      nearHandle: "Guidance and fortunate timing are present in your immediate life circumstances.",
      oppositeHandle: "A distant aspiration or outside source of guidance is activating.",
      nearRim: "Illumination and hope are arriving soon.",
      nearBottom: "A deep, long-held hope or wish is at the foundation of current life themes.",
    },
  },
  {
    symbol: "moon",
    alternateNames: ["crescent", "half-circle", "lunar shape"],
    themes: ["intuition", "cycles", "mystery", "femininity", "subconscious"],
    positiveMeaning: "The moon invites trust in intuition, cyclical change, and the deeper emotional currents moving beneath the surface. What is unseen is still active.",
    shadowMeaning: "The moon can also indicate illusion, emotional confusion, or something operating in shadow that hasn't yet been brought to light.",
    domains: ["personal", "love", "health"],
    reflectionQuestion: "What is your intuition telling you right now that your rational mind keeps dismissing?",
    locationModifier: {
      nearHandle: "Emotional and intuitive themes are most active in your immediate personal life.",
      oppositeHandle: "A more mysterious or distant influence is operating — something not yet visible.",
      nearRim: "An emotional realization or intuitive knowing is about to surface.",
      nearBottom: "Deep subconscious patterns, ancestral influences, or long-held emotional themes are present.",
    },
  },
  {
    symbol: "sun",
    alternateNames: ["circle with rays", "sunshine", "solar symbol"],
    themes: ["vitality", "success", "clarity", "confidence", "joy"],
    positiveMeaning: "The sun is the symbol of radiant success, vitality, and clarity. It suggests a period of flourishing where efforts are recognized and life energy is high.",
    shadowMeaning: "The sun reversed or obscured might indicate ego inflation, overexposure, or burning out from too much output without rest.",
    domains: ["career", "personal", "health"],
    reflectionQuestion: "Where in your life does the sun most need to shine right now — what area needs your full, radiant attention?",
    locationModifier: {
      nearHandle: "Success and vitality are active in your immediate circumstances.",
      oppositeHandle: "Recognition or opportunity is coming from an outside source.",
      nearRim: "A bright, energized period is beginning very soon.",
      nearBottom: "A core vitality that has been dormant is beginning to re-emerge.",
    },
  },
  {
    symbol: "tree",
    alternateNames: ["branches", "trunk", "roots and branches", "oak", "tree of life"],
    themes: ["growth", "roots", "family", "stability", "longevity"],
    positiveMeaning: "The tree speaks of deep roots supporting expansive growth — of stability, family legacy, and the long-term flourishing of what has been carefully tended over time.",
    shadowMeaning: "A fallen or bare tree may indicate a disruption of roots, family difficulty, or a foundation that needs examination.",
    domains: ["family", "personal", "career"],
    reflectionQuestion: "What roots in your life — family, values, or home — most need tending right now?",
    locationModifier: {
      nearHandle: "Family and home life are the center of current growth.",
      oppositeHandle: "Growth is happening in more distant or public areas of life.",
      nearRim: "A period of visible flourishing is approaching.",
      nearBottom: "Deep ancestral or family roots are the underlying theme.",
    },
  },
  {
    symbol: "mountain",
    alternateNames: ["peak", "triangle", "hill", "summit"],
    themes: ["achievement", "challenge", "ambition", "perspective", "obstacle"],
    positiveMeaning: "The mountain represents a significant achievement being climbed toward — a goal that requires effort and patience but whose view from the top is worth every step.",
    shadowMeaning: "A mountain may also indicate a significant obstacle that feels overwhelming in scale — the invitation is to take it one step at a time rather than trying to see the whole summit.",
    domains: ["career", "personal"],
    reflectionQuestion: "What mountain have you been avoiding beginning to climb? What would the first step look like?",
    locationModifier: {
      nearHandle: "The challenge or achievement is immediately ahead in your current life.",
      oppositeHandle: "A longer-range goal or more distant challenge is in view.",
      nearRim: "The peak of a challenge or achievement is approaching in the near term.",
      nearBottom: "A foundational ambition or long-standing challenge is active beneath current circumstances.",
    },
  },
  {
    symbol: "road",
    alternateNames: ["path", "line", "track", "trail", "straight line"],
    themes: ["journey", "direction", "choices", "progress", "clarity of path"],
    positiveMeaning: "A clear road or path signals forward momentum and a clear sense of direction — the path ahead is becoming visible and traversable.",
    shadowMeaning: "A winding or fragmented road may indicate uncertainty about direction or a need to make a clear choice about which way to go.",
    domains: ["personal", "career", "travel"],
    reflectionQuestion: "Which direction are you being called to take, and what has been stopping you from choosing it clearly?",
    locationModifier: {
      nearHandle: "Direction and momentum are most relevant to immediate personal circumstances.",
      oppositeHandle: "The path leads toward external opportunity, travel, or a new direction in the wider world.",
      nearRim: "A new direction is becoming available very soon.",
      nearBottom: "A foundational life direction question is being worked through at depth.",
    },
  },
  {
    symbol: "bridge",
    alternateNames: ["arch", "overpass", "crossing"],
    themes: ["transition", "connection", "crossing over", "linking worlds", "overcoming division"],
    positiveMeaning: "The bridge signals a transition between two states — a crossing being made from one life phase to another, or the connection of two things that had been separated.",
    shadowMeaning: "A collapsed or incomplete bridge may indicate difficulty completing a transition, or a connection that isn't yet stable.",
    domains: ["personal", "love", "career"],
    reflectionQuestion: "What are you in the process of crossing over from and into — and what support do you need for the crossing?",
    locationModifier: {
      nearHandle: "A personal or domestic transition is underway.",
      oppositeHandle: "A more significant life transition is involving external circumstances.",
      nearRim: "A crossing or transition is imminent.",
      nearBottom: "A deep life transition is its own foundation theme.",
    },
  },
  {
    symbol: "door",
    alternateNames: ["gateway", "entrance", "opening", "threshold", "archway"],
    themes: ["opportunity", "new beginning", "access", "threshold", "decision"],
    positiveMeaning: "An open door is one of the most auspicious symbols — it signals an opportunity, a new beginning available, and an invitation to cross a threshold into something genuinely new.",
    shadowMeaning: "A closed door may indicate an opportunity that has not yet opened, or a pattern of avoiding what is actually being offered.",
    domains: ["career", "personal", "love"],
    reflectionQuestion: "What door has been appearing before you that you haven't yet been willing to walk through?",
    locationModifier: {
      nearHandle: "An opportunity within immediate life circumstances is present.",
      oppositeHandle: "An external opportunity — a new job, a meeting, a distant connection — is approaching.",
      nearRim: "A door is opening very soon.",
      nearBottom: "A deep opportunity or life threshold has been waiting for a long time.",
    },
  },
  {
    symbol: "key",
    alternateNames: ["key shape", "lock opener"],
    themes: ["access", "solution", "discovery", "unlocking potential", "secret revealed"],
    positiveMeaning: "The key signals that a solution, access, or revelation is available — something that was locked is about to be opened. The answer is present; it may just require recognizing which door it belongs to.",
    shadowMeaning: "A lost or broken key may indicate that access to what you need is temporarily blocked, or that the wrong question is being asked.",
    domains: ["personal", "career", "love"],
    reflectionQuestion: "What have you been trying to unlock in your life — and do you already have the key?",
    locationModifier: {
      nearHandle: "The solution or revelation is within your immediate environment.",
      oppositeHandle: "Access or insight is coming from an outside source.",
      nearRim: "A revealing moment is approaching quickly.",
      nearBottom: "A fundamental unlocking of something long hidden.",
    },
  },
  {
    symbol: "ring",
    alternateNames: ["circle", "O shape", "band", "loop"],
    themes: ["commitment", "completion", "eternity", "relationship", "wholeness"],
    positiveMeaning: "The ring is a symbol of commitment, wholeness, and the eternal nature of genuine connection — it may signal a deepening commitment, a completed cycle, or a relationship moving toward permanence.",
    shadowMeaning: "A broken ring may indicate a relationship challenge, a cycle ending, or a commitment being questioned.",
    domains: ["love", "personal", "family"],
    reflectionQuestion: "What commitment in your life most deserves to be honored and deepened right now?",
    locationModifier: {
      nearHandle: "Commitment themes are most active in immediate relationships.",
      oppositeHandle: "A commitment or completion in a more external or professional context.",
      nearRim: "A commitment or relationship development is approaching.",
      nearBottom: "A foundational commitment from the past is active — either needing renewal or release.",
    },
  },
  {
    symbol: "fish",
    alternateNames: ["fish shape", "school of fish", "swimming creature"],
    themes: ["abundance", "subconscious", "fertility", "spiritual depth", "luck"],
    positiveMeaning: "The fish swims in the depths — abundance from the subconscious, spiritual good fortune, and the fertility of emotional and material life. Fish traditionally signal financial abundance and spiritual depth.",
    shadowMeaning: "A fish out of water or reversed may suggest feeling out of one's element, or diving too deep without adequate preparation.",
    domains: ["career", "personal", "health"],
    reflectionQuestion: "What depths have you been reluctant to dive into, and what might you find there?",
    locationModifier: {
      nearHandle: "Abundance and depth are present in immediate circumstances.",
      oppositeHandle: "Financial or spiritual fortune is coming from a more distant source.",
      nearRim: "Material or spiritual abundance is near.",
      nearBottom: "Deep spiritual or financial foundations are active.",
    },
  },
  {
    symbol: "cat",
    alternateNames: ["feline", "kitten", "cat shape"],
    themes: ["independence", "mystery", "intuition", "feminine power", "deception"],
    positiveMeaning: "The cat brings independence, intuitive perception, and feminine mystery — the ability to move gracefully through the world while maintaining one's own counsel.",
    shadowMeaning: "May indicate deception nearby, or the presence of someone who is not showing their full hand. The cat also warns of excessive independence that tips into isolation.",
    domains: ["personal", "love"],
    reflectionQuestion: "Where in your life are you moving through on your own terms — and is that serving you or isolating you?",
    locationModifier: {
      nearHandle: "Mystery or independence energy is active in the immediate home or relationship space.",
      oppositeHandle: "An independent or mysterious person or situation in the wider world.",
      nearRim: "An encounter with mystery or an independent-minded person is approaching.",
      nearBottom: "Deep independence or mysterious patterns have been formative.",
    },
  },
  {
    symbol: "dog",
    alternateNames: ["canine", "loyal animal", "puppy"],
    themes: ["loyalty", "friendship", "protection", "companionship", "faithfulness"],
    positiveMeaning: "The dog is the symbol of loyal friendship, faithful companionship, and protective love — one of the most reassuring symbols in the cup, signaling that you are surrounded by genuine loyalty.",
    shadowMeaning: "A growling or threatening dog energy may indicate the need to protect yourself, or misplaced loyalty to someone who doesn't deserve it.",
    domains: ["love", "family", "personal"],
    reflectionQuestion: "Who in your life represents genuine loyal friendship — and are you honoring that relationship?",
    locationModifier: {
      nearHandle: "Loyalty and friendship are most active in your immediate home and relationships.",
      oppositeHandle: "A loyal connection at a distance — a friend or ally in external circumstances.",
      nearRim: "A reunion, a new friendship, or a faithful connection is approaching.",
      nearBottom: "Deep foundations of loyalty — old friendships, family ties, or formative bonds.",
    },
  },
  {
    symbol: "horse",
    alternateNames: ["stallion", "mare", "galloping horse", "equine"],
    themes: ["freedom", "power", "journey", "strength", "nobility"],
    positiveMeaning: "The horse carries the energy of powerful forward movement — freedom, physical vitality, and the strength to carry you toward your goals. A horse in full gallop signals that momentum is available.",
    shadowMeaning: "An out-of-control or rearing horse may suggest energy that is difficult to direct — power without adequate guidance.",
    domains: ["personal", "career", "travel"],
    reflectionQuestion: "What would it feel like to ride toward your next life chapter with the full power available to you?",
    locationModifier: {
      nearHandle: "Powerful movement and freedom are present in immediate circumstances.",
      oppositeHandle: "A journey or power shift is coming from an external source.",
      nearRim: "A significant movement or breakthrough is approaching fast.",
      nearBottom: "Deep vitality and the desire for freedom have been long-standing themes.",
    },
  },
  {
    symbol: "butterfly",
    alternateNames: ["moth", "winged insect", "metamorphosis symbol"],
    themes: ["transformation", "rebirth", "lightness", "change", "beauty from struggle"],
    positiveMeaning: "The butterfly is the most direct symbol of transformation — the beautiful result of genuine metamorphosis. It signals that a significant personal change is complete or very near completion.",
    shadowMeaning: "A moth rather than butterfly may indicate transformation happening in darkness, or change that feels disorienting before it becomes beautiful.",
    domains: ["personal", "love"],
    reflectionQuestion: "What are you in the process of transforming into — and can you trust the process even before the wings have formed?",
    locationModifier: {
      nearHandle: "Transformation is occurring in your immediate personal life.",
      oppositeHandle: "Change is being invited by external circumstances.",
      nearRim: "A beautiful transformation is very near completion.",
      nearBottom: "A fundamental personal metamorphosis has been the foundational work of this life period.",
    },
  },
  {
    symbol: "spider",
    alternateNames: ["arachnid", "web-maker", "eight legs"],
    themes: ["creativity", "patience", "fate", "industry", "entanglement"],
    positiveMeaning: "The spider is the master weaver — patient, creative, and willing to build something intricate one thread at a time. It signals a period requiring patient, deliberate creation.",
    shadowMeaning: "A spider's web may indicate feeling caught or entangled — in a situation, in a relationship dynamic, or in one's own fears.",
    domains: ["career", "personal"],
    reflectionQuestion: "What web are you weaving in your life — and is it the one you actually want to live in?",
    locationModifier: {
      nearHandle: "Creative industry or entanglement is most active in your immediate life.",
      oppositeHandle: "An external web of circumstances or a more distant creative project.",
      nearRim: "A web is being woven or is near completion.",
      nearBottom: "Deep patterns — of creation or entanglement — are foundational.",
    },
  },
  {
    symbol: "web",
    alternateNames: ["spider web", "net", "grid pattern", "lattice"],
    themes: ["interconnection", "traps", "community", "complex situations", "hidden patterns"],
    positiveMeaning: "The web signals complex interconnection — the recognition that many things are more linked than they appear. Situations are more interwoven than they seem on the surface.",
    shadowMeaning: "A web can indicate feeling trapped, or the presence of someone attempting to manipulate through complex entanglement.",
    domains: ["personal", "career", "love"],
    reflectionQuestion: "Where in your life are you caught in a web of complexity that may actually be simpler than it appears?",
    locationModifier: {
      nearHandle: "Interconnected dynamics are active in immediate relationships.",
      oppositeHandle: "A complex web of circumstances in external life.",
      nearRim: "Entanglement or interconnection is becoming more visible.",
      nearBottom: "Foundational patterns of connection or entanglement.",
    },
  },
  {
    symbol: "boat",
    alternateNames: ["ship", "vessel", "sailboat", "canoe"],
    themes: ["journey", "navigation", "crossing", "adventure", "trust in the process"],
    positiveMeaning: "The boat signals a journey being navigated — whether literal travel or the metaphorical voyage of a significant life transition. The waters may not always be calm, but the vessel is sound.",
    shadowMeaning: "A capsizing or damaged boat may indicate a journey that has become difficult, or the need to reassess your navigation tools.",
    domains: ["travel", "personal", "career"],
    reflectionQuestion: "What journey are you in the middle of — and are you trusting the vessel that is carrying you?",
    locationModifier: {
      nearHandle: "A journey connected to home or personal life.",
      oppositeHandle: "Travel or a life journey taking you away from the familiar.",
      nearRim: "A journey or transition is beginning very soon.",
      nearBottom: "A fundamental life journey has been long underway.",
    },
  },
  {
    symbol: "anchor",
    alternateNames: ["anchor shape", "heavy hook", "maritime anchor"],
    themes: ["stability", "grounding", "commitment", "security", "steadiness"],
    positiveMeaning: "The anchor speaks of groundedness, reliable foundations, and the security of something that holds fast even in turbulent waters. What is stable in your life is more solid than it may appear.",
    shadowMeaning: "An anchor can also indicate feeling weighed down — stability that has become rigidity, or a commitment that has become a limitation on movement.",
    domains: ["personal", "love", "career"],
    reflectionQuestion: "What anchors you in the best sense — and what has become an anchor in the limiting sense?",
    locationModifier: {
      nearHandle: "Stability and grounding are present in immediate circumstances.",
      oppositeHandle: "Stability is being sought or found in external life.",
      nearRim: "A grounding or stabilizing force is arriving.",
      nearBottom: "Deep, foundational stability — or foundational limitations.",
    },
  },
  {
    symbol: "cloud",
    alternateNames: ["storm cloud", "fog", "mist", "cluster"],
    themes: ["uncertainty", "confusion", "impending change", "intuition", "weather"],
    positiveMeaning: "Clouds bring rain that nourishes — they may represent a period of productive uncertainty before clarity arrives, or the gentle obscuring before a revelation.",
    shadowMeaning: "Dark clouds may indicate emotional difficulty approaching, confusion, or a situation where the full picture is not yet visible.",
    domains: ["personal", "career"],
    reflectionQuestion: "What clouds are obscuring your clarity right now — and can you sit with the not-knowing long enough for the weather to shift?",
    locationModifier: {
      nearHandle: "Uncertainty is present in your immediate personal environment.",
      oppositeHandle: "External circumstances are less clear than they appear.",
      nearRim: "A period of confusion or transition is approaching.",
      nearBottom: "Deep uncertainty or long-standing confusion about a foundational area.",
    },
  },
  {
    symbol: "lightning bolt",
    alternateNames: ["thunder bolt", "zigzag", "electricity symbol"],
    themes: ["sudden change", "revelation", "energy", "awakening", "disruption"],
    positiveMeaning: "The lightning bolt is the moment of sudden illumination — a revelation, a breakthrough, or a sudden change that clarifies everything. What has been obscure becomes instantly clear.",
    shadowMeaning: "Lightning can also signal shocking disruption, sudden loss, or an event that arrives without warning and demands rapid adaptation.",
    domains: ["personal", "career", "love"],
    reflectionQuestion: "What sudden revelation or change are you being asked to absorb and integrate right now?",
    locationModifier: {
      nearHandle: "A sudden revelation or change in your immediate personal life.",
      oppositeHandle: "Sudden external events are influencing your situation.",
      nearRim: "A surprise or breakthrough is arriving very soon.",
      nearBottom: "A fundamental disruption that has changed the foundation of things.",
    },
  },
  {
    symbol: "flower",
    alternateNames: ["bloom", "rose", "blossom", "petal pattern"],
    themes: ["beauty", "growth", "flourishing", "love", "new life"],
    positiveMeaning: "The flower is an emblem of beauty in full bloom — flourishing, love, creative expression, and the joy of life expressing itself fully. What is being tended is blooming.",
    shadowMeaning: "A wilting flower may indicate something that needs more nourishment, or beauty and life force being neglected.",
    domains: ["love", "personal", "health"],
    reflectionQuestion: "What area of your life is in full bloom right now — and what still needs tending before it can open?",
    locationModifier: {
      nearHandle: "Beauty and flourishing are most active in your immediate relationships.",
      oppositeHandle: "Growth and beauty are blooming in external circumstances.",
      nearRim: "A blossoming or creative expression is arriving soon.",
      nearBottom: "Deep roots of beauty and creativity.",
    },
  },
  {
    symbol: "cross",
    alternateNames: ["crucifix", "plus sign", "X shape", "intersection"],
    themes: ["faith", "burden", "sacrifice", "intersection of paths", "spiritual meaning"],
    positiveMeaning: "The cross can signal faith, spiritual support, and the meeting point between the earthly and divine — protection and guidance through difficulty.",
    shadowMeaning: "The cross can also indicate a burden being carried, a sacrifice being required, or a painful intersection of conflicting demands.",
    domains: ["personal", "health", "family"],
    reflectionQuestion: "What burden are you carrying right now — and is it truly yours to carry, or can you set it down?",
    locationModifier: {
      nearHandle: "Spiritual or practical burdens are present in immediate circumstances.",
      oppositeHandle: "External circumstances are creating challenges that require faith.",
      nearRim: "A significant challenge or spiritual activation is approaching.",
      nearBottom: "A foundational spiritual or karmic theme.",
    },
  },
  {
    symbol: "arrow",
    alternateNames: ["pointing line", "dart", "directional symbol"],
    themes: ["direction", "intention", "focus", "moving toward", "clarity of aim"],
    positiveMeaning: "The arrow signals clear direction and intentional aim — the clarity of knowing where you are going and moving decisively toward it.",
    shadowMeaning: "An arrow pointing backward or reversed may indicate looking back too much, or energy being directed away from what matters.",
    domains: ["career", "personal"],
    reflectionQuestion: "Where is your arrow pointed right now — and is that truly the direction you want to be moving?",
    locationModifier: {
      nearHandle: "Direction is most clearly available in your immediate personal circumstances.",
      oppositeHandle: "A clear direction or opportunity is pointing away from the familiar.",
      nearRim: "Clarity of direction is arriving soon.",
      nearBottom: "A foundational directional clarity is present.",
    },
  },
  {
    symbol: "circle",
    alternateNames: ["ring", "O", "complete loop", "zero"],
    themes: ["completion", "wholeness", "cycles", "eternity", "protection"],
    positiveMeaning: "The circle is completion and wholeness — the return to beginning after the full cycle has been completed. It signals that a cycle is reaching its natural culmination.",
    shadowMeaning: "An incomplete circle may indicate something not yet finished, or a cycle being resisted rather than completed.",
    domains: ["personal", "love"],
    reflectionQuestion: "What cycle in your life is nearing completion — and can you honor its ending before beginning the next?",
    locationModifier: {
      nearHandle: "A completion or whole cycle is present in immediate circumstances.",
      oppositeHandle: "Completion is happening in external life.",
      nearRim: "A cycle is completing very soon.",
      nearBottom: "A fundamental completion at the root of current themes.",
    },
  },
  {
    symbol: "triangle",
    alternateNames: ["pyramid", "three-pointed shape", "delta"],
    themes: ["aspiration", "structure", "trinity", "power", "manifestation"],
    positiveMeaning: "The triangle pointing upward signals aspiration, the drive toward something higher, and the stable structure of three-point alignment — mind, body, spirit, or past, present, future in harmony.",
    shadowMeaning: "A downward-pointing triangle may indicate something descending into the unconscious, or structural instability.",
    domains: ["career", "personal"],
    reflectionQuestion: "What three elements of your life are you being called to align into a stable, upward-moving structure?",
    locationModifier: {
      nearHandle: "Aspirational or structural themes in immediate life.",
      oppositeHandle: "A higher aspiration being reached toward in external circumstances.",
      nearRim: "An aspiration or manifestation is approaching.",
      nearBottom: "Foundational structural or aspirational patterns.",
    },
  },
  {
    symbol: "eye",
    alternateNames: ["open eye", "eye of providence", "all-seeing eye"],
    themes: ["perception", "awareness", "psychic vision", "watchfulness", "clarity"],
    positiveMeaning: "The eye signals heightened perception and awareness — you are seeing clearly, or are about to. Trust your perceptions; they are more accurate than others might want you to believe.",
    shadowMeaning: "May indicate feeling watched or surveilled, or a tendency to be overly analytical rather than allowing intuition to operate.",
    domains: ["personal", "career"],
    reflectionQuestion: "What are you seeing clearly right now that you may have been reluctant to fully acknowledge?",
    locationModifier: {
      nearHandle: "Clear perception is most available in immediate circumstances.",
      oppositeHandle: "Something in the wider world requires careful observation.",
      nearRim: "A significant perception or revelation is arriving.",
      nearBottom: "Deep, long-standing patterns of perception or avoidance.",
    },
  },
  {
    symbol: "hand",
    alternateNames: ["palm", "fingers", "open hand", "pointing finger"],
    themes: ["giving", "receiving", "skill", "help", "connection"],
    positiveMeaning: "The hand signals assistance coming or being offered — help, practical skill, or the direct, tangible connection of one person to another.",
    shadowMeaning: "A closed fist or pointing hand may indicate withholding, accusation, or aggression.",
    domains: ["personal", "career", "love"],
    reflectionQuestion: "Are you extending your hand in the ways that feel most authentic right now — and are you allowing yourself to receive when a hand is extended toward you?",
    locationModifier: {
      nearHandle: "Help and connection are present in immediate circumstances.",
      oppositeHandle: "Assistance or skill coming from outside your immediate circle.",
      nearRim: "Help or a significant handshake is approaching.",
      nearBottom: "Foundational help or skill.",
    },
  },
  {
    symbol: "crown",
    alternateNames: ["tiara", "laurel wreath", "circlet"],
    themes: ["success", "authority", "recognition", "achievement", "leadership"],
    positiveMeaning: "The crown signals success, recognition, and the authority that comes from genuine achievement. Your efforts are being recognized, and a position of leadership or honor is available.",
    shadowMeaning: "A tipping or fallen crown may indicate authority being challenged, or the price of leadership becoming apparent.",
    domains: ["career", "personal"],
    reflectionQuestion: "What would you need to believe about yourself to fully step into the authority and recognition available to you?",
    locationModifier: {
      nearHandle: "Recognition is coming in your immediate professional or personal life.",
      oppositeHandle: "Public recognition or authority from external sources.",
      nearRim: "Achievement and recognition are arriving very soon.",
      nearBottom: "A deep, foundational sense of worthiness of recognition.",
    },
  },
  {
    symbol: "sword",
    alternateNames: ["blade", "dagger", "sword shape"],
    themes: ["truth", "decision", "conflict", "clarity", "cutting away"],
    positiveMeaning: "The sword is the instrument of truth and clarity — the capacity to cut through pretense and make a decisive choice. It may signal that a clear, brave truth needs to be spoken.",
    shadowMeaning: "Conflict, the potential for harm through words or actions, or a battle that may not be worth having.",
    domains: ["personal", "career", "communication"],
    reflectionQuestion: "What truth needs to be spoken clearly — and are you willing to hold the sword steady enough to say it?",
    locationModifier: {
      nearHandle: "A truth or decision is most pressing in your immediate circumstances.",
      oppositeHandle: "A conflict or clarity issue in external or professional life.",
      nearRim: "A decisive moment is approaching.",
      nearBottom: "A foundational truth that has been avoided.",
    },
  },
  {
    symbol: "cup",
    alternateNames: ["chalice", "goblet", "vessel"],
    themes: ["emotional life", "receptivity", "nourishment", "spiritual sustenance", "love"],
    positiveMeaning: "The cup signals emotional receptivity and the capacity to receive what is being offered — love, nourishment, spiritual sustenance. The cup that is open and upright receives the rain.",
    shadowMeaning: "A tipped or empty cup may indicate emotional depletion, giving without receiving, or a feeling of emptiness.",
    domains: ["love", "personal", "health"],
    reflectionQuestion: "Is your cup currently full enough to give from — or does it need to be refilled first?",
    locationModifier: {
      nearHandle: "Emotional receptivity is most needed in immediate relationships.",
      oppositeHandle: "Emotional nourishment from an outside source.",
      nearRim: "Emotional fulfillment or nourishment is arriving.",
      nearBottom: "Deep emotional foundations — thirst or sustenance at the root of current themes.",
    },
  },
  {
    symbol: "coin",
    alternateNames: ["circle with markings", "pentacle", "disc"],
    themes: ["money", "material security", "value", "exchange", "prosperity"],
    positiveMeaning: "The coin signals material prosperity, financial exchange, and the currency of value — a financial opportunity, a fair exchange, or the material manifestation of what you have been building.",
    shadowMeaning: "A single coin may indicate limited resources, or an over-focus on material concerns at the expense of other values.",
    domains: ["career", "personal"],
    reflectionQuestion: "How does your relationship to money and material security reflect your deeper sense of self-worth?",
    locationModifier: {
      nearHandle: "Financial themes are most active in your immediate circumstances.",
      oppositeHandle: "Financial opportunity is coming from outside your current situation.",
      nearRim: "A financial development is approaching.",
      nearBottom: "Deep financial patterns or foundations.",
    },
  },
  {
    symbol: "ladder",
    alternateNames: ["rungs", "steps upward", "staircase on an angle"],
    themes: ["advancement", "effort", "climbing toward goals", "ambition", "progress"],
    positiveMeaning: "The ladder signals steady, methodical advancement — the possibility of climbing toward your goals one rung at a time. Progress is available, and the ladder is stable.",
    shadowMeaning: "A broken or unstable ladder may indicate that the path of advancement has obstacles, or that the wrong ladder has been chosen.",
    domains: ["career", "personal"],
    reflectionQuestion: "What is the next rung on the ladder before you — and do you believe you are capable of reaching it?",
    locationModifier: {
      nearHandle: "Advancement is most available in your immediate personal or professional life.",
      oppositeHandle: "Career or life advancement through external opportunity.",
      nearRim: "A significant step upward is approaching.",
      nearBottom: "Foundational work on which advancement can be built.",
    },
  },
  {
    symbol: "tower",
    alternateNames: ["tall building", "fortress", "lighthouse"],
    themes: ["ambition", "isolation", "protection", "revelation", "pride"],
    positiveMeaning: "The tower may signal a period of elevated perspective — being above the chaos and seeing clearly from a higher vantage point. A lighthouse tower brings guidance and safety.",
    shadowMeaning: "The tower as fortress signals isolation, defensiveness, or pride before a fall. What is fortified too rigidly becomes vulnerable in its very rigidity.",
    domains: ["career", "personal"],
    reflectionQuestion: "Are you defending something in isolation that would be stronger if you allowed connection?",
    locationModifier: {
      nearHandle: "Isolation or elevated perspective in immediate life.",
      oppositeHandle: "External structures or ambitions that feel elevated.",
      nearRim: "A significant rise or revelation is approaching.",
      nearBottom: "Foundational pride or defensiveness that has shaped things.",
    },
  },
  {
    symbol: "river",
    alternateNames: ["stream", "flowing water", "winding line with flow", "waterway"],
    themes: ["life flow", "emotions moving", "change", "time", "natural progression"],
    positiveMeaning: "The river signals the natural flow of life — time moving, emotions processing, and the trust that what needs to happen will happen in its own time.",
    shadowMeaning: "A flooding river may indicate emotions overwhelming boundaries; a dried-up stream suggests emotional depletion or stagnation.",
    domains: ["personal", "health"],
    reflectionQuestion: "Are you flowing with the current of your life, or are you swimming against it? What would it feel like to trust the river?",
    locationModifier: {
      nearHandle: "Emotional flow or life movement is most active in immediate circumstances.",
      oppositeHandle: "The flow of time and change in external life.",
      nearRim: "A new current or direction is beginning.",
      nearBottom: "Deep emotional or life-flow patterns.",
    },
  },
  {
    symbol: "wave",
    alternateNames: ["ocean wave", "undulating line", "water motion"],
    themes: ["emotion", "power", "cycles", "overwhelm", "riding energy"],
    positiveMeaning: "The wave signals a powerful surge of emotional or life energy — the possibility of riding this momentum toward something significant.",
    shadowMeaning: "Being overcome by waves may indicate emotional overwhelm, or energy that is too powerful to direct without being submerged.",
    domains: ["personal", "love"],
    reflectionQuestion: "What wave of energy is surging through your life right now — and are you riding it or trying to resist it?",
    locationModifier: {
      nearHandle: "Powerful emotional energy in immediate relationships.",
      oppositeHandle: "External forces creating waves of change.",
      nearRim: "A powerful surge is arriving.",
      nearBottom: "Deep emotional tides.",
    },
  },
  {
    symbol: "fire",
    alternateNames: ["flame", "blaze", "campfire", "torch"],
    themes: ["passion", "transformation", "destruction", "energy", "inspiration"],
    positiveMeaning: "Fire signals passion, inspiration, and the transformative power of genuine creative or emotional energy — something is being set alight.",
    shadowMeaning: "Uncontrolled fire may indicate passion that is consuming rather than illuminating, or conflict that has become destructive.",
    domains: ["love", "career", "personal"],
    reflectionQuestion: "What are you on fire about right now — and is that fire illuminating or consuming?",
    locationModifier: {
      nearHandle: "Passion and energy are most active in your immediate circumstances.",
      oppositeHandle: "An external source of inspiration or conflict.",
      nearRim: "A passionate or transformative energy is arriving.",
      nearBottom: "Foundational passion or transformation.",
    },
  },
  {
    symbol: "house",
    alternateNames: ["home shape", "building with roof", "dwelling"],
    themes: ["home", "security", "family", "self", "belonging"],
    positiveMeaning: "The house is one of the most comforting symbols — it signals security, belonging, home, and the safety of being within a stable and loving environment.",
    shadowMeaning: "A house in disrepair or disorder may indicate instability in the home environment, or that the foundation of security feels shaky.",
    domains: ["family", "personal", "love"],
    reflectionQuestion: "What does home mean to you right now — and do you feel at home within yourself as much as in your physical space?",
    locationModifier: {
      nearHandle: "Home and security are most active in immediate circumstances.",
      oppositeHandle: "Home or belonging themes in external circumstances.",
      nearRim: "A significant development related to home or belonging.",
      nearBottom: "Foundational home, security, and belonging themes.",
    },
  },
  {
    symbol: "stairs",
    alternateNames: ["steps", "staircase", "ascending steps"],
    themes: ["progress", "step-by-step growth", "achievement", "elevation", "gradual development"],
    positiveMeaning: "The stairs signal steady, step-by-step progress toward a goal — the satisfaction of methodical advancement and the recognition that each small step adds up to something significant.",
    shadowMeaning: "Descending stairs may indicate a retreat or deliberate stepping back — not failure, but a strategic return to rebuild.",
    domains: ["career", "personal"],
    reflectionQuestion: "What is the next concrete step available to you right now — not the whole staircase, just the next step?",
    locationModifier: {
      nearHandle: "Progress is most available in your immediate personal or professional life.",
      oppositeHandle: "External steps toward a goal.",
      nearRim: "An important step is approaching.",
      nearBottom: "Foundational steps that everything rests upon.",
    },
  },
  {
    symbol: "gate",
    alternateNames: ["fence gate", "entry", "barrier with opening"],
    themes: ["threshold", "permission", "entry point", "choice", "invitation"],
    positiveMeaning: "The gate signals that you are standing at a significant threshold — something is opening that has been closed, and entry is being offered. The question is: will you walk through?",
    shadowMeaning: "A locked or closed gate may indicate permission being withheld — either by circumstances, others, or the internal belief that you are not yet allowed.",
    domains: ["personal", "career", "love"],
    reflectionQuestion: "What gate have you been standing before, waiting for permission to walk through — and who is actually supposed to give you that permission?",
    locationModifier: {
      nearHandle: "A threshold in your immediate personal life.",
      oppositeHandle: "An entry point in external circumstances.",
      nearRim: "An invitation or opening is arriving.",
      nearBottom: "A foundational threshold that has shaped your path.",
    },
  },
  {
    symbol: "mirror",
    alternateNames: ["looking glass", "reflection", "oval shape"],
    themes: ["self-reflection", "truth", "projection", "inner seeing", "vanity"],
    positiveMeaning: "The mirror invites honest self-reflection — seeing yourself clearly rather than through the lens of others' expectations or your own defenses.",
    shadowMeaning: "A cracked mirror may indicate distorted self-perception, or a significant relationship dynamic where projection and mirroring are obscuring the truth.",
    domains: ["personal", "love"],
    reflectionQuestion: "What are you seeing when you look in the mirror right now — and is that the truth of you, or a story about you?",
    locationModifier: {
      nearHandle: "Self-reflection is most needed in your immediate circumstances.",
      oppositeHandle: "Others are mirroring something back to you from the wider world.",
      nearRim: "A revealing self-reflection or mirroring is arriving.",
      nearBottom: "Deep patterns of self-perception.",
    },
  },
  {
    symbol: "book",
    alternateNames: ["open book", "tome", "pages", "manuscript"],
    themes: ["learning", "knowledge", "secrets", "wisdom", "communication"],
    positiveMeaning: "The book signals learning, knowledge, and the wisdom available from study — an invitation to go deeper into understanding, or the literal or metaphorical arrival of important information.",
    shadowMeaning: "A closed book may indicate information being withheld, or wisdom available but not yet accessed.",
    domains: ["communication", "career", "personal"],
    reflectionQuestion: "What knowledge or wisdom are you being called to study more deeply — what book, metaphorical or literal, needs to be opened?",
    locationModifier: {
      nearHandle: "Learning and knowledge are most active in immediate circumstances.",
      oppositeHandle: "Knowledge or information coming from an outside source.",
      nearRim: "An important piece of information or learning is approaching.",
      nearBottom: "Foundational knowledge or wisdom.",
    },
  },
  {
    symbol: "letter",
    alternateNames: ["envelope", "correspondence", "message"],
    themes: ["communication", "news", "message received", "correspondence", "surprise information"],
    positiveMeaning: "The letter signals news arriving — communication, correspondence, or an important message making its way to you. The content is generally favorable.",
    shadowMeaning: "A sealed or unclear letter may indicate information withheld, or communication that has not yet arrived or been sent.",
    domains: ["communication", "career", "love"],
    reflectionQuestion: "What message have you been waiting to receive — or what message have you been putting off sending?",
    locationModifier: {
      nearHandle: "Important communication is active in your immediate life.",
      oppositeHandle: "News or correspondence from a distance.",
      nearRim: "A significant message is arriving soon.",
      nearBottom: "Long-awaited or foundational communication.",
    },
  },
  {
    symbol: "clock",
    alternateNames: ["timepiece", "watch", "circular with hands"],
    themes: ["timing", "urgency", "patience", "deadlines", "the right moment"],
    positiveMeaning: "The clock signals that timing is significant — either that the right moment is approaching, or that something has been waiting for precisely the right time and that time is now.",
    shadowMeaning: "A stopped or backward clock may indicate feeling stuck in time, living in the past, or anxiety about time running out.",
    domains: ["career", "personal"],
    reflectionQuestion: "What are you waiting for the right moment to do — and is the moment actually here already?",
    locationModifier: {
      nearHandle: "Timing is most critical in your immediate circumstances.",
      oppositeHandle: "Timing related to external events or opportunities.",
      nearRim: "An important timing threshold is very near.",
      nearBottom: "Long-standing timing or patience themes.",
    },
  },
  {
    symbol: "spiral",
    alternateNames: ["coil", "whirlpool", "vortex", "snail shell"],
    themes: ["evolution", "expansion", "cycles", "going deeper", "energy vortex"],
    positiveMeaning: "The spiral signals evolution and the ongoing deepening of understanding — each cycle returns to the same themes but from a higher vantage point. Growth is underway.",
    shadowMeaning: "A tight inward spiral may indicate rumination, withdrawal, or getting pulled into obsessive thinking.",
    domains: ["personal", "health"],
    reflectionQuestion: "Where in your evolution are you right now — and can you trust that the spiral is taking you somewhere real?",
    locationModifier: {
      nearHandle: "Evolutionary or cyclical themes in immediate life.",
      oppositeHandle: "Evolution happening through external experiences.",
      nearRim: "A new cycle of evolution is beginning.",
      nearBottom: "Deep evolutionary themes at the root of current life.",
    },
  },
  {
    symbol: "face",
    alternateNames: ["profile", "head shape", "mask", "portrait"],
    themes: ["identity", "personality", "a specific person", "reputation", "how you are seen"],
    positiveMeaning: "A face in the grounds often indicates a specific person — someone significant in your life, or a quality of person arriving. Faces also speak to identity and how you present yourself.",
    shadowMeaning: "A masked or unclear face may indicate someone who is not showing their true self, or an aspect of your own identity that is hidden.",
    domains: ["love", "personal", "communication"],
    reflectionQuestion: "Whose face comes to mind as you contemplate what most needs your attention right now?",
    locationModifier: {
      nearHandle: "A significant person in your immediate life.",
      oppositeHandle: "Someone more distant whose influence is being felt.",
      nearRim: "A significant person is approaching or a new identity is forming.",
      nearBottom: "A deep, formative relationship or aspect of identity.",
    },
  },
  {
    symbol: "number one",
    alternateNames: ["1", "single line", "first"],
    themes: ["new beginning", "independence", "leadership", "self", "initiation"],
    positiveMeaning: "The number one signals a genuine new beginning and the energy of independent initiative. You are being invited to start something entirely new.",
    shadowMeaning: "Isolation or ego that resists the collaboration needed to make something real.",
    domains: ["career", "personal"],
    reflectionQuestion: "What new beginning is trying to initiate through you right now?",
    locationModifier: {
      nearHandle: "A new beginning in immediate life.",
      oppositeHandle: "A new beginning in external circumstances.",
      nearRim: "A new beginning is arriving.",
      nearBottom: "The first steps of something foundational.",
    },
  },
  {
    symbol: "broken line",
    alternateNames: ["discontinuous line", "dashes", "interrupted line", "jagged"],
    themes: ["interruption", "disruption", "uncertainty", "change of direction", "fragmentation"],
    positiveMeaning: "A broken line may indicate a necessary interruption — a pause built into the process that makes the next phase possible.",
    shadowMeaning: "Fragmentation, plans that are not proceeding smoothly, or a sense of disconnection between intention and execution.",
    domains: ["career", "personal"],
    reflectionQuestion: "Where in your life has an interruption or disruption actually been protective or redirecting?",
    locationModifier: {
      nearHandle: "Interruptions are most active in immediate circumstances.",
      oppositeHandle: "External disruptions affecting your path.",
      nearRim: "A significant interruption or change of direction is approaching.",
      nearBottom: "Foundational disruptions that have shaped your current path.",
    },
  },
  {
    symbol: "thick cluster",
    alternateNames: ["dense mass", "clump", "cloud-like shape", "dark area"],
    themes: ["concentrated energy", "blockage", "complexity", "overload", "focal point"],
    positiveMeaning: "A thick cluster often indicates a focal point of concentrated energy — where the most is happening, where attention is most needed, or where a dense possibility is beginning to crystallize.",
    shadowMeaning: "A dark cluster may indicate a blockage, an overload, or something that has accumulated to a critical density requiring release.",
    domains: ["personal", "health"],
    reflectionQuestion: "Where in your life is there a cluster of unprocessed energy — and what one thing might help to begin to clear it?",
    locationModifier: {
      nearHandle: "A concentrated issue or focal point in your immediate personal life.",
      oppositeHandle: "Concentrated energy or complexity in external circumstances.",
      nearRim: "A clustering of issues is approaching resolution.",
      nearBottom: "Deep, concentrated patterns at the foundation.",
    },
  },
  {
    symbol: "scattered dots",
    alternateNames: ["small marks", "speckled pattern", "tiny circles"],
    themes: ["scattered energy", "many small things", "distraction", "abundance of detail", "unfocused"],
    positiveMeaning: "Many small scattered dots may indicate an abundance of small opportunities or connections — a period of busy, active energy where many small things are happening simultaneously.",
    shadowMeaning: "Scattered energy that needs consolidation — too many small things preventing the focus needed for something significant.",
    domains: ["personal", "career"],
    reflectionQuestion: "Where are you spreading your attention too thin — and what one area would most benefit from your full focus?",
    locationModifier: {
      nearHandle: "Scattered energy is most present in immediate personal life.",
      oppositeHandle: "Dispersed activity in external circumstances.",
      nearRim: "A period of scattered but abundant activity.",
      nearBottom: "Foundational patterns of scattered energy.",
    },
  },
  {
    symbol: "large empty space",
    alternateNames: ["clear area", "open space", "void", "clearness"],
    themes: ["potential", "openness", "new chapter", "space to create", "emptiness"],
    positiveMeaning: "A large empty space in the grounds is one of the most auspicious signals — it indicates open space for new creation, a chapter that is genuinely clear and ready to be written.",
    shadowMeaning: "Emptiness can also speak to loneliness, or a life area that feels hollow or unoccupied when it longs to be filled.",
    domains: ["personal", "career"],
    reflectionQuestion: "What empty space in your life is actually an invitation rather than a lack — and what might you create in it?",
    locationModifier: {
      nearHandle: "Open, creative space is present in your immediate personal life.",
      oppositeHandle: "External circumstances are clearing to make space for something new.",
      nearRim: "A significant opening is arriving.",
      nearBottom: "A foundational clearing or openness.",
    },
  },
  {
    symbol: "dark stain",
    alternateNames: ["dark spot", "shadow mark", "blot"],
    themes: ["shadow", "warning", "unconscious difficulty", "hidden issue", "unresolved matter"],
    positiveMeaning: "A dark stain, when recognized, is the beginning of bringing something to light. Awareness is the first step to resolution.",
    shadowMeaning: "An unresolved issue, a shadow pattern, or something in the situation that is not entirely what it appears. This symbol invites careful, honest examination.",
    domains: ["personal", "health", "love"],
    reflectionQuestion: "What dark area of a situation are you perhaps avoiding looking at too closely — and what would honest examination reveal?",
    locationModifier: {
      nearHandle: "A shadow issue is most present in your immediate personal or relationship life.",
      oppositeHandle: "An unresolved matter in external circumstances.",
      nearRim: "A shadow issue is coming to the surface soon.",
      nearBottom: "A deep, foundational shadow pattern.",
    },
  },
];
