/**
 * Mantra template seeds — stable ids for upsert. 60+ rows (10 planets × 6).
 * Farsi marked with // NEEDS NATIVE REVIEW where phrasing may need polish.
 */
export type MantraTemplateSeed = {
  id: string;
  planetTag: string;
  aspectTag: string;
  signTag: string;
  qualityTag: string;
  mantraEn: string;
  mantraFa: string;
  mantraEnExploratory: string;
  mantraFaExploratory: string;
  themeAffinity: string[];
  isActive: boolean;
};

const AFF = {
  calm: "calm",
  confidence: "confidence",
  selfWorth: "self-worth",
  love: "love",
  healing: "healing",
  focus: "focus",
  growth: "growth",
  release: "release",
  hope: "hope",
  faith: "faith",
  discipline: "discipline",
} as const;

/** Saturn — discipline / structure */
const saturn: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "discipline",
    mantraEn: "I honor my limits and keep the promises I make to myself.",
    mantraFa: "به حد و مرزم احترام می‌ذارم و به قولی که به خودم می‌دم عمل می‌کنم.",
    mantraEnExploratory: "What small promise to myself could I keep today?",
    mantraFaExploratory: "امروز چه قول کوچیکی می‌تونم به خودم بدم و واقعا بهش پایبند بمونم؟",
    themeAffinity: [AFF.discipline, AFF.focus, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "patience",
    mantraEn: "I build what lasts by moving slowly and showing up again tomorrow.",
    mantraFa: "آروم و پیوسته پیش می‌رم و چیزی می‌سازم که موندنی باشه.",
    mantraEnExploratory: "Where could patience change the outcome today?",
    mantraFaExploratory: "امروز کجا صبرم می‌تونه نتیجه را عوض کنه؟",
    themeAffinity: [AFF.calm, AFF.growth, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "boundaries",
    mantraEn: "I say no with kindness when yes would cost me my peace.",
    mantraFa: "وقتی بله گفتن آرامشم را می‌گیره، با مهربونی نه می‌گم.",
    mantraEnExploratory: "What boundary would protect my energy this week?",
    mantraFaExploratory: "این هفته چه مرزی بیشتر از انرژی‌م مراقبت می‌کنه؟",
    themeAffinity: [AFF.confidence, AFF.release, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "maturity",
    mantraEn: "I own my choices and repair what I can without shame.",
    mantraFa: "مسئول انتخاب‌هام هستم و هرجا بشه، بدون شرم درستش می‌کنم.",
    mantraEnExploratory: "What repair would show my real maturity today?",
    mantraFaExploratory: "امروز چه کاری نشون می‌ده که واقعا بالغ‌تر شدم؟",
    themeAffinity: [AFF.growth, AFF.healing, AFF.selfWorth],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "resilience",
    mantraEn: "I stay steady through delay because my worth is not a deadline.",
    mantraFa: "توی تأخیر هم محکم می‌مونم، چون ارزش من به وقت رسیدن نیست.",
    mantraEnExploratory: "How might delay be training my resilience?",
    mantraFaExploratory: "این تأخیر چطور می‌تونه من را قوی‌تر کنه؟",
    themeAffinity: [AFF.hope, AFF.faith, AFF.discipline],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "structure",
    mantraEn: "I give my day a simple frame so my mind can rest inside it.",
    mantraFa: "به روزم یک نظم ساده می‌دم تا ذهنم کمی نفس بکشه.",
    mantraEnExploratory: "What one structure would calm my mind today?",
    mantraFaExploratory: "امروز چه نظم ساده‌ای ذهنم را آرام‌تر می‌کنه؟",
    themeAffinity: [AFF.focus, AFF.calm, AFF.growth],
    isActive: true,
  },
];

const mercury: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "communication",
    mantraEn: "I speak clearly and listen for the feeling beneath the words.",
    mantraFa: "روشن حرف می‌زنم و حسم را پشت کلمه‌ها هم می‌شنوم.",
    mantraEnExploratory: "What honest sentence am I ready to say gently?",
    mantraFaExploratory: "چه حرف راستی را می‌تونم امروز با نرمی بگم؟",
    themeAffinity: [AFF.love, AFF.focus, AFF.confidence],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "clarity",
    mantraEn: "I name what confuses me and let questions open the next step.",
    mantraFa: "به چیزی که گیجم کرده اسم می‌دم و با سوال، راه بعد را پیدا می‌کنم.",
    mantraEnExploratory: "What question would bring clarity right now?",
    mantraFaExploratory: "الان چه سوالی می‌تونه ذهنم را روشن‌تر کنه؟",
    themeAffinity: [AFF.focus, AFF.calm, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "curiosity",
    mantraEn: "I stay curious instead of certain when the talk gets tight.",
    mantraFa: "وقتی گفتگو گره می‌خوره، کنجکاو می‌مونم نه لجباز.",
    mantraEnExploratory: "Could curiosity soften this conversation today?",
    mantraFaExploratory: "امروز کنجکاوی چطور می‌تونه این گفتگو را نرم‌تر کنه؟",
    themeAffinity: [AFF.hope, AFF.release, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "learning",
    mantraEn: "I treat mistakes as information that steers my next draft.",
    mantraFa: "اشتباه‌هام را نشونه می‌بینم، نه شکست.",
    mantraEnExploratory: "What did my last mistake teach me in one line?",
    mantraFaExploratory: "آخرین اشتباهم توی یک جمله چی یادم داد؟",
    themeAffinity: [AFF.growth, AFF.confidence, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "listening",
    mantraEn: "I pause before I answer so my reply can carry real care.",
    mantraFa: "قبل از جواب دادن مکث می‌کنم تا حرفم از دلِ توجه بیاد.",
    mantraEnExploratory: "Who needs me to listen more than I fix today?",
    mantraFaExploratory: "امروز چه کسی بیشتر از راه‌حل، به شنیده شدن نیاز داره؟",
    themeAffinity: [AFF.love, AFF.healing, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "truth",
    mantraEn: "I choose honest words that protect both kindness and self-respect.",
    mantraFa: "حرف راست را جوری می‌زنم که هم مهربون باشه هم حرمت خودم حفظ بشه.",
    mantraEnExploratory: "Where could softer truth replace a sharp silence?",
    mantraFaExploratory: "کجا می‌تونم به جای سکوت سنگین، یک حقیقت نرم بگم؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.release],
    isActive: true,
  },
];

const venus: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "love",
    mantraEn: "I let love move through me without demanding a perfect scene.",
    mantraFa: "می‌ذارم عشق جاری بشه، بی‌اینکه همه‌چیز بی‌نقص باشه.",
    mantraEnExploratory: "How might I receive affection without scoring it?",
    mantraFaExploratory: "چطور می‌تونم محبت را بدون حساب و کتاب بگیرم؟",
    themeAffinity: [AFF.love, AFF.hope, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "beauty",
    mantraEn: "I notice one small beauty and let it soften my whole mood.",
    mantraFa: "یک زیبایی کوچیک را می‌بینم و می‌ذارم حالم را عوض کنه.",
    mantraEnExploratory: "What tiny beauty is already in front of me?",
    mantraFaExploratory: "الان چه زیبایی کوچیکی جلوی چشمم هست؟",
    themeAffinity: [AFF.calm, AFF.hope, AFF.selfWorth],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "pleasure",
    mantraEn: "I allow simple pleasure without guilt because joy also heals.",
    mantraFa: "به خودم اجازه می‌دم از یک لذت ساده خوشحال بشم، بدون عذاب وجدان.",
    mantraEnExploratory: "What harmless pleasure could I gift myself today?",
    mantraFaExploratory: "امروز چه لذت ساده و بی‌ضرری می‌تونم به خودم هدیه بدم؟",
    themeAffinity: [AFF.healing, AFF.release, AFF.love],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "harmony",
    mantraEn: "I choose peace in my close ties over winning every small point.",
    mantraFa: "توی رابطه‌های نزدیک، آرامش را به برنده شدن ترجیح می‌دم.",
    mantraEnExploratory: "Where would harmony cost less than being right?",
    mantraFaExploratory: "کجا آرامش از حق به جانب بودن برام ارزشمندتره؟",
    themeAffinity: [AFF.calm, AFF.love, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "worth",
    mantraEn: "I am allowed to want tenderness and still hold my standards.",
    mantraFa: "حق دارم مهربونی بخوام و همزمان حد و مرزم را نگه دارم.",
    mantraEnExploratory: "What would self-respect look like in love today?",
    mantraFaExploratory: "امروز احترام به خودم توی عشق چه شکلی داره؟",
    themeAffinity: [AFF.selfWorth, AFF.confidence, AFF.love],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "connection",
    mantraEn: "I reach out once with warmth and release the perfect reply.",
    mantraFa: "یک بار با گرمی جلو می‌رم و منتظر جواب بی‌نقص نمی‌مونم.",
    mantraEnExploratory: "Who might welcome a simple warm check-in?",
    mantraFaExploratory: "امروز چه کسی از یک احوالپرسی گرم خوشحال می‌شه؟",
    themeAffinity: [AFF.love, AFF.hope, AFF.healing],
    isActive: true,
  },
];

const mars: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "action",
    mantraEn: "I take one brave step today and trust momentum to meet me.",
    mantraFa: "امروز یک قدم شجاع برمی‌دارم و راه را با حرکت باز می‌کنم.",
    mantraEnExploratory: "What is the smallest brave action open to me?",
    mantraFaExploratory: "کوچک‌ترین کار شجاعانه‌ای که الان می‌تونم بکنم چیه؟",
    themeAffinity: [AFF.confidence, AFF.focus, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "courage",
    mantraEn: "I face what I avoided with breath and a steady voice.",
    mantraFa: "با نفس عمیق و صدای محکم، با چیزی که ازش فرار می‌کردم روبه‌رو می‌شم.",
    mantraEnExploratory: "What avoidance is ready to be faced gently?",
    mantraFaExploratory: "الان وقت روبه‌رو شدنِ آرام با کدوم فراره؟",
    themeAffinity: [AFF.confidence, AFF.healing, AFF.release],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "energy",
    mantraEn: "I channel my fire into one task until it is honestly done.",
    mantraFa: "انرژی‌م را روی یک کار می‌ذارم تا واقعا تمامش کنم.",
    mantraEnExploratory: "Where should my energy go first for real progress?",
    mantraFaExploratory: "اول از همه انرژی‌م را کجا بذارم که واقعا جلو برم؟",
    themeAffinity: [AFF.focus, AFF.growth, AFF.discipline],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "assertion",
    mantraEn: "I ask directly for what I need without apologizing for existing.",
    mantraFa: "واضح می‌گم چی لازم دارم، بدون اینکه برای نیاز داشتنم عذر بخوام.",
    mantraEnExploratory: "What direct request would honor my needs today?",
    mantraFaExploratory: "امروز چه درخواست مستقیمی بیشتر به نیازم احترام می‌ذاره؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.love],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "drive",
    mantraEn: "I aim my hunger at a goal that matches my deeper values.",
    mantraFa: "انگیزه‌م را سمت هدفی می‌برم که با ارزش‌هام جور دربیاد.",
    mantraEnExploratory: "Does my drive still match what I truly value?",
    mantraFaExploratory: "این تلاشم هنوز با چیزی که عمیقا برام مهمه هماهنگه؟",
    themeAffinity: [AFF.growth, AFF.faith, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "reset",
    mantraEn: "I cool my temper with water, air, and a slower next move.",
    mantraFa: "قبل از واکنش، با آب و هوا و کمی مکث آروم‌تر می‌شم.",
    mantraEnExploratory: "What would help me reset before I react?",
    mantraFaExploratory: "قبل از اینکه واکنش نشون بدم، چی می‌تونه من را آروم کنه؟",
    themeAffinity: [AFF.calm, AFF.release, AFF.healing],
    isActive: true,
  },
];

const jupiter: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "expansion",
    mantraEn: "I widen my horizon one generous choice at a time.",
    mantraFa: "با هر انتخابِ بخشنده، دنیام را کمی بزرگ‌تر می‌کنم.",
    mantraEnExploratory: "Where could a little generosity expand my life?",
    mantraFaExploratory: "کجا کمی بخشندگی می‌تونه زندگی‌م را بازتر کنه؟",
    themeAffinity: [AFF.growth, AFF.hope, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "faith",
    mantraEn: "I trust the stretch even when I cannot see the far shore.",
    mantraFa: "حتی وقتی آخر راه را نمی‌بینم، به مسیر اعتماد می‌کنم.",
    mantraEnExploratory: "What might I trust beyond my current proof?",
    mantraFaExploratory: "الان فراتر از چیزی که ثابت شده، به چی می‌تونم اعتماد کنم؟",
    themeAffinity: [AFF.faith, AFF.hope, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "optimism",
    mantraEn: "I look for one honest reason this chapter can still grow me.",
    mantraFa: "دنبال یک دلیل واقعی می‌گردم که این فصل هم بتونه من را رشد بده.",
    mantraEnExploratory: "What honest hopeful angle is still available?",
    mantraFaExploratory: "الان چه نگاه امیدوارکننده و صادقی هنوز برام مونده؟",
    themeAffinity: [AFF.hope, AFF.growth, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "abundance",
    mantraEn: "I notice enough here to share without feeding my scarcity fear.",
    mantraFa: "فراوانیِ همین حالا را می‌بینم و از ترس کمبود نمی‌چسبم.",
    mantraEnExploratory: "What do I already have enough of to offer?",
    mantraFaExploratory: "الان از چی به اندازه کافی دارم که بتونم با دل باز ببخشم؟",
    themeAffinity: [AFF.love, AFF.selfWorth, AFF.release],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "meaning",
    mantraEn: "I search for meaning in the lesson, not only in the prize.",
    mantraFa: "معنا را فقط توی نتیجه نمی‌گردم، توی درسی که دارم هم می‌بینم.",
    mantraEnExploratory: "What lesson is trying to enlarge me now?",
    mantraFaExploratory: "الان چه درسی می‌خواد من را بزرگ‌تر کنه؟",
    themeAffinity: [AFF.growth, AFF.faith, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "adventure",
    mantraEn: "I say yes to a healthy risk that makes my life feel wider.",
    mantraFa: "به یک ریسک سالم بله می‌گم تا زندگی‌م کمی بازتر بشه.",
    mantraEnExploratory: "What safe adventure is calling my name?",
    mantraFaExploratory: "الان چه تجربه تازه و امنی من را صدا می‌زنه؟",
    themeAffinity: [AFF.hope, AFF.confidence, AFF.release],
    isActive: true,
  },
];

const moon: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "intuition",
    mantraEn: "I trust the quiet nudge that arrives before the full proof.",
    mantraFa: "به آن حس آرام درونم اعتماد می‌کنم، حتی قبل از اینکه همه‌چیز روشن بشه.",
    mantraEnExploratory: "What is my gut trying to whisper before I rush?",
    mantraFaExploratory: "قبل از اینکه عجله کنم، دلم داره چی را یواشکی می‌گه؟",
    themeAffinity: [AFF.calm, AFF.healing, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "feelings",
    mantraEn: "I name my feeling without drowning it so it can move through.",
    mantraFa: "به احساسم اسم می‌دم تا ازم رد بشه، نه اینکه توش گم بشم.",
    mantraEnExploratory: "What feeling needs a name before it can pass?",
    mantraFaExploratory: "الان کدوم حس فقط می‌خواد اسمش را بگم؟",
    themeAffinity: [AFF.healing, AFF.release, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "nurture",
    mantraEn: "I mother myself with rest, food, and gentle inner talk.",
    mantraFa: "با استراحت، غذا و حرف مهربون، از خودم مراقبت می‌کنم.",
    mantraEnExploratory: "How would I comfort a tired version of me?",
    mantraFaExploratory: "اگر خیلی خسته بودم، چطور با خودم مهربون‌تر رفتار می‌کردم؟",
    themeAffinity: [AFF.love, AFF.calm, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "rhythm",
    mantraEn: "I follow my natural pace without forcing a constant peak.",
    mantraFa: "با ریتم خودم پیش می‌رم و خودم را مجبور به اوجِ همیشگی نمی‌کنم.",
    mantraEnExploratory: "What pace fits my body and mood today?",
    mantraFaExploratory: "امروز چه سرعتی با بدن و حالِ من جورتره؟",
    themeAffinity: [AFF.calm, AFF.focus, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "memory",
    mantraEn: "I honor old pain without letting it steer every new choice.",
    mantraFa: "به دردهای قدیمی احترام می‌ذارم، ولی نمی‌ذارم همه تصمیم‌های تازه‌م را بچرخونن.",
    mantraEnExploratory: "Which memory needs honoring but not the wheel?",
    mantraFaExploratory: "کدوم خاطره را باید فقط ببینم، نه اینکه دوباره فرمان را بهش بدم؟",
    themeAffinity: [AFF.healing, AFF.release, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "safety",
    mantraEn: "I build safety in small rituals that tell my body it is home.",
    mantraFa: "با کارهای کوچیک و آشنا، به بدنم یادآوری می‌کنم که امنم.",
    mantraEnExploratory: "What tiny ritual would signal safety to me?",
    mantraFaExploratory: "چه کار کوچیکی امروز حس امنیت بیشتری بهم می‌ده؟",
    themeAffinity: [AFF.calm, AFF.faith, AFF.love],
    isActive: true,
  },
];

const sun: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "identity",
    mantraEn: "I show up as myself even when the room feels too bright.",
    mantraFa: "خودِ واقعی‌م را پنهان نمی‌کنم، حتی وقتی همه‌چیز زیادی رو به چشم باشه.",
    mantraEnExploratory: "Where am I hiding a real part of my identity?",
    mantraFaExploratory: "کجا دارم بخشی از خودِ واقعی‌م را پنهان می‌کنم؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "visibility",
    mantraEn: "I let one honest part of me be seen without rehearsing perfection.",
    mantraFa: "می‌ذارم یک بخش واقعی از من دیده بشه، بدون اینکه بخوام کامل به نظر بیام.",
    mantraEnExploratory: "What truth about me could tolerate gentle light?",
    mantraFaExploratory: "چه حقیقتی درباره من می‌تونه امروز آروم دیده بشه؟",
    themeAffinity: [AFF.confidence, AFF.love, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "vitality",
    mantraEn: "I feed my life force with sleep, sun, and purpose I chose.",
    mantraFa: "با خواب، نور، و کاری که از دل خودم میاد، جانم را تازه می‌کنم.",
    mantraEnExploratory: "What restores my vitality in a simple way?",
    mantraFaExploratory: "چه چیز ساده‌ای زودتر از همه جونم را برمی‌گردونه؟",
    themeAffinity: [AFF.growth, AFF.focus, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "purpose",
    mantraEn: "I align my day with one purpose that feels true to my core.",
    mantraFa: "روزم را با چیزی هماهنگ می‌کنم که ته دلم هنوز براش روشنه.",
    mantraEnExploratory: "What purpose still feels alive in my chest?",
    mantraFaExploratory: "چه هدفی هنوز ته دلم زنده و بیداره؟",
    themeAffinity: [AFF.faith, AFF.focus, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "confidence",
    mantraEn: "I stand in my worth without shrinking when others shine too.",
    mantraFa: "روی ارزش خودم می‌ایستم و با درخشش دیگران کوچیک نمی‌شم.",
    mantraEnExploratory: "Where could I share light instead of compete?",
    mantraFaExploratory: "کجا می‌تونم به جای رقابت، نورم را با دل باز تقسیم کنم؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.love],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "warmth",
    mantraEn: "I lead with warmth because strength without care feels hollow.",
    mantraFa: "با گرمی جلو می‌رم، چون قدرتِ بی‌مهر برای من خالیه.",
    mantraEnExploratory: "How could warmth lead my next hard conversation?",
    mantraFaExploratory: "چطور می‌تونم گفتگوی سخت بعدی را با گرمی جلو ببرم؟",
    themeAffinity: [AFF.love, AFF.healing, AFF.calm],
    isActive: true,
  },
];

const neptune: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "surrender",
    mantraEn: "I release the grip when control is only fear in disguise.",
    mantraFa: "وقتی می‌فهمم این کنترل فقط از ترسه، دستم را شل می‌کنم.",
    mantraEnExploratory: "What am I ready to soften my grip on today?",
    mantraFaExploratory: "امروز وقتِ رها کردنِ چی رسیده؟",
    themeAffinity: [AFF.release, AFF.faith, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "dreams",
    mantraEn: "I let imagination visit without letting it erase my ground.",
    mantraFa: "به خیال‌هام جا می‌دم، بی‌اینکه از زمین جدا بشم.",
    mantraEnExploratory: "What dream needs a gentle boundary around it?",
    mantraFaExploratory: "کدوم رویاهام به یک مرز نرم و سالم نیاز داره؟",
    themeAffinity: [AFF.hope, AFF.healing, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "compassion",
    mantraEn: "I soften toward myself first so compassion can be real.",
    mantraFa: "اول با خودم نرم‌تر می‌شم تا مهربونی‌م واقعی باشه.",
    mantraEnExploratory: "Where would self-compassion change everything?",
    mantraFaExploratory: "کجا اگر کمی بیشتر با خودم مهربون باشم، همه‌چیز عوض می‌شه؟",
    themeAffinity: [AFF.healing, AFF.love, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "mystery",
    mantraEn: "I tolerate not knowing and still take the next faithful step.",
    mantraFa: "با ندانستن می‌مونم و بازم قدم بعدی را برمی‌دارم.",
    mantraEnExploratory: "What unknown am I willing to walk beside?",
    mantraFaExploratory: "کنار کدوم نادانسته حاضرم هنوز راه برم؟",
    themeAffinity: [AFF.faith, AFF.hope, AFF.release],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "dissolve",
    mantraEn: "I let old stories dissolve in salt water and quiet breath.",
    mantraFa: "قصه‌های کهنه را با نفس آرام و دلِ سبک رها می‌کنم.",
    mantraEnExploratory: "Which old story is ready to dissolve?",
    mantraFaExploratory: "کدوم قصه قدیمی دیگه وقتش رسیده ازم جدا بشه؟",
    themeAffinity: [AFF.release, AFF.healing, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "spirit",
    mantraEn: "I open to something larger without abandoning my daily duties.",
    mantraFa: "به چیزی بزرگ‌تر از خودم دل باز می‌کنم و از کارهای روزمره‌م هم جا نمی‌مونم.",
    mantraEnExploratory: "How might spirit and duty share the same day?",
    mantraFaExploratory: "امروز چطور می‌تونم هم به روحم برسم هم به مسئولیت‌هام؟",
    themeAffinity: [AFF.faith, AFF.hope, AFF.focus],
    isActive: true,
  },
];

const pluto: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "transformation",
    mantraEn: "I let what must end end so a truer life can find space.",
    mantraFa: "می‌ذارم هر چیزی که باید تموم بشه، تموم بشه تا جا برای زندگیِ واقعی‌تر باز بشه.",
    mantraEnExploratory: "What ending would clear soil for real growth?",
    mantraFaExploratory: "چه پایانی می‌تونه راه رشد واقعی را برام باز کنه؟",
    themeAffinity: [AFF.release, AFF.growth, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "power",
    mantraEn: "I use my power to heal patterns instead of repeating harm.",
    mantraFa: "از قدرتم برای ترمیم استفاده می‌کنم، نه برای تکرار زخم‌ها.",
    mantraEnExploratory: "Where could I redirect power toward repair?",
    mantraFaExploratory: "الان کجا می‌تونم قدرتم را سمت ترمیم ببرم؟",
    themeAffinity: [AFF.healing, AFF.confidence, AFF.love],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "shadow",
    mantraEn: "I look at my shadow with respect because it carries my truth.",
    mantraFa: "به سایه‌هام با احترام نگاه می‌کنم، چون بخشی از حقیقت من توی اون‌هاست.",
    mantraEnExploratory: "What shadow truth is asking for integration?",
    mantraFaExploratory: "کدوم بخش پنهان من می‌خواد دیده و پذیرفته بشه؟",
    themeAffinity: [AFF.healing, AFF.selfWorth, AFF.release],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "rebirth",
    mantraEn: "I welcome a new chapter even if the doorway feels narrow.",
    mantraFa: "از فصل تازه استقبال می‌کنم، حتی اگر راه ورودش تنگ و نامطمئن باشه.",
    mantraEnExploratory: "What rebirth is quietly knocking at my life?",
    mantraFaExploratory: "چه شروع تازه‌ای داره آروم‌آروم به زندگی‌م نزدیک می‌شه؟",
    themeAffinity: [AFF.hope, AFF.faith, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "intensity",
    mantraEn: "I hold intensity without spilling it on people who are fragile.",
    mantraFa: "شدتِ درونم را نگه می‌دارم و بی‌ملاحظه روی کسی خالی نمی‌کنم.",
    mantraEnExploratory: "Where should I channel intensity with care?",
    mantraFaExploratory: "امروز این شدت را کجا می‌تونم با آگاهی و مراقبت هدایت کنم؟",
    themeAffinity: [AFF.focus, AFF.calm, AFF.love],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "release",
    mantraEn: "I compost old resentments into fuel for honest change.",
    mantraFa: "کینه‌های کهنه را به نیرویی برای تغییر واقعی تبدیل می‌کنم.",
    mantraEnExploratory: "What resentment is ready to become compost?",
    mantraFaExploratory: "کدوم کینه قدیمی آماده‌ست که بالاخره رها بشه؟",
    themeAffinity: [AFF.release, AFF.growth, AFF.healing],
    isActive: true,
  },
];

const chiron: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "healing",
    mantraEn: "I tend my wound without turning it into my whole identity.",
    mantraFa: "به زختم رسیدگی می‌کنم، بی‌اینکه بگذارم تمام تعریف من بشه.",
    mantraEnExploratory: "How can I heal without staying only the hurt?",
    mantraFaExploratory: "چطور می‌تونم خوب بشم، بدون اینکه فقط با زخمم شناخته بشم؟",
    themeAffinity: [AFF.healing, AFF.selfWorth, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "mentor",
    mantraEn: "I turn my hardest lesson into gentle guidance for someone else.",
    mantraFa: "از سخت‌ترین درس‌هام، راهی نرم برای کمک به دیگری می‌سازم.",
    mantraEnExploratory: "Who might benefit from what I survived?",
    mantraFaExploratory: "چه کسی می‌تونه از چیزی که من ازش عبور کردم نفع ببره؟",
    themeAffinity: [AFF.love, AFF.healing, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "vulnerability",
    mantraEn: "I share one real crack so connection does not stay shallow.",
    mantraFa: "یک بخش واقعی و ترک‌خورده از خودم را نشان می‌دم تا رابطه‌هام سطحی نمونه.",
    mantraEnExploratory: "What safe vulnerability could deepen trust today?",
    mantraFaExploratory: "امروز چه آسیب‌پذیری امنی می‌تونه اعتماد را عمیق‌تر کنه؟",
    themeAffinity: [AFF.love, AFF.confidence, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "wisdom",
    mantraEn: "I honor pain that taught me wisdom without romanticizing harm.",
    mantraFa: "به دردی که بهم خرد داده احترام می‌ذارم، بی‌اینکه زخم را قشنگ جلوه بدم.",
    mantraEnExploratory: "What pain taught me something I would keep?",
    mantraFaExploratory: "کدوم درد چیزی یادم داده که هنوز با من مونده؟",
    themeAffinity: [AFF.growth, AFF.faith, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "acceptance",
    mantraEn: "I accept what I cannot rewrite and still choose my next line.",
    mantraFa: "چیزی را که نمی‌تونم عوض کنم می‌پذیرم و بازم انتخاب بعدی‌م را خودم می‌کنم.",
    mantraEnExploratory: "What acceptance would free my next sentence?",
    mantraFaExploratory: "چه پذیرشی می‌تونه راه قدم بعدی‌م را بازتر کنه؟",
    themeAffinity: [AFF.calm, AFF.release, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "service",
    mantraEn: "I serve from scar-tissue strength without bleeding on others.",
    mantraFa: "از جایی که ترمیم شدم کمک می‌کنم، نه از جایی که هنوز دارم زخم می‌ریزم.",
    mantraEnExploratory: "Where could humble service heal me too?",
    mantraFaExploratory: "کجا خدمتِ بی‌ادعا می‌تونه هم به دیگری کمک کنه هم به من؟",
    themeAffinity: [AFF.healing, AFF.love, AFF.faith],
    isActive: true,
  },
];

function withIds(rows: Omit<MantraTemplateSeed, "id">[], prefix: string): MantraTemplateSeed[] {
  return rows.map((r, i) => ({
    ...r,
    id: `mt-${prefix}-${i + 1}`,
  }));
}

export const mantraTemplates: MantraTemplateSeed[] = [
  ...withIds(saturn, "saturn"),
  ...withIds(mercury, "mercury"),
  ...withIds(venus, "venus"),
  ...withIds(mars, "mars"),
  ...withIds(jupiter, "jupiter"),
  ...withIds(moon, "moon"),
  ...withIds(sun, "sun"),
  ...withIds(neptune, "neptune"),
  ...withIds(pluto, "pluto"),
  ...withIds(chiron, "chiron"),
];
