/**
 * Mantra template seeds — stable ids for upsert. 60+ rows (10 planets × 6).
 * Farsi marked with // NEEDS NATIVE REVIEW where phrasing may need polish.
 */
export type MantraTemplateSeed = {
  id: string;
  planetTag: string;
  aspectTag: string;
  signTag: string;
  qualityTag: string;
  mantraEn: string;
  mantraFa: string;
  mantraEnExploratory: string;
  mantraFaExploratory: string;
  themeAffinity: string[];
  isActive: boolean;
};

const AFF = {
  calm: "calm",
  confidence: "confidence",
  selfWorth: "self-worth",
  love: "love",
  healing: "healing",
  focus: "focus",
  growth: "growth",
  release: "release",
  hope: "hope",
  faith: "faith",
  discipline: "discipline",
} as const;

/** Saturn — discipline / structure */
const saturn: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "discipline",
    mantraEn: "I honor my limits and keep the promises I make to myself.",
    mantraFa: "به حدود خود احترام می‌گذارم و به قول‌هایی که به خودم داده‌ام پایبند می‌مانم.", // NEEDS NATIVE REVIEW
    mantraEnExploratory: "What small promise to myself could I keep today?",
    mantraFaExploratory: "امروز چه قول کوچکی به خودم می‌توانم بدهم و به آن عمل کنم؟",
    themeAffinity: [AFF.discipline, AFF.focus, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "patience",
    mantraEn: "I build what lasts by moving slowly and showing up again tomorrow.",
    mantraFa: "با آرامش و تکرار فردا، می‌سازمش که بماند.",
    mantraEnExploratory: "Where could patience change the outcome today?",
    mantraFaExploratory: "کجا صبر می‌تواند نتیجه را عوض کند؟",
    themeAffinity: [AFF.calm, AFF.growth, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "boundaries",
    mantraEn: "I say no with kindness when yes would cost me my peace.",
    mantraFa: "با مهربانی نه می‌گویم وقتی بله آرامشم را می‌گیرد.",
    mantraEnExploratory: "What boundary would protect my energy this week?",
    mantraFaExploratory: "چه مرزی این هفته انرژی‌ام را حفظ می‌کند؟",
    themeAffinity: [AFF.confidence, AFF.release, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "maturity",
    mantraEn: "I own my choices and repair what I can without shame.",
    mantraFa: "مسئول انتخاب‌هایم هستم و بی‌شرمانه آنچه را می‌توانم درست می‌کنم.",
    mantraEnExploratory: "What repair would show my real maturity today?",
    mantraFaExploratory: "امروز چه جبرانی بلوغ واقعی‌ام را نشان می‌دهد؟",
    themeAffinity: [AFF.growth, AFF.healing, AFF.selfWorth],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "resilience",
    mantraEn: "I stay steady through delay because my worth is not a deadline.",
    mantraFa: "در تأخیر هم استوار می‌مانم؛ ارزشم به موعد نیست.",
    mantraEnExploratory: "How might delay be training my resilience?",
    mantraFaExploratory: "تأخیر چگونه می‌تواند تمرین تاب‌آوری من باشد؟",
    themeAffinity: [AFF.hope, AFF.faith, AFF.discipline],
    isActive: true,
  },
  {
    planetTag: "saturn",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "structure",
    mantraEn: "I give my day a simple frame so my mind can rest inside it.",
    mantraFa: "به روزم یک چارچوب ساده می‌دهم تا ذهنم در آن آرام بگیرد.",
    mantraEnExploratory: "What one structure would calm my mind today?",
    mantraFaExploratory: "یک ساختار ساده امروز ذهنم را آرام می‌کند؟",
    themeAffinity: [AFF.focus, AFF.calm, AFF.growth],
    isActive: true,
  },
];

const mercury: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "communication",
    mantraEn: "I speak clearly and listen for the feeling beneath the words.",
    mantraFa: "روشن می‌گویم و زیر حرف‌ها را هم می‌شنوم.",
    mantraEnExploratory: "What honest sentence am I ready to say gently?",
    mantraFaExploratory: "چه جملهٔ راستی را می‌توانم با ملایت بگویم؟",
    themeAffinity: [AFF.love, AFF.focus, AFF.confidence],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "clarity",
    mantraEn: "I name what confuses me and let questions open the next step.",
    mantraFa: "آنچه گیجم می‌کند نام می‌گذارم و می‌گذارم پرسش قدم بعد را باز کند.",
    mantraEnExploratory: "What question would bring clarity right now?",
    mantraFaExploratory: "الان چه پرسشی روشنم می‌کند؟",
    themeAffinity: [AFF.focus, AFF.calm, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "curiosity",
    mantraEn: "I stay curious instead of certain when the talk gets tight.",
    mantraFa: "وقتی حرف‌ها سخت می‌شود کنجکاو می‌مانم نه محکم.",
    mantraEnExploratory: "Could curiosity soften this conversation today?",
    mantraFaExploratory: "امروز کنجکاوی می‌تواند این گفتگو را نرم کند؟",
    themeAffinity: [AFF.hope, AFF.release, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "learning",
    mantraEn: "I treat mistakes as information that steers my next draft.",
    mantraFa: "اشتباه را اطلاعاتی می‌دانم که پیش‌نویس بعدی را هدایت می‌کند.",
    mantraEnExploratory: "What did my last mistake teach me in one line?",
    mantraFaExploratory: "آخرین اشتباهم در یک جمله چه آموخت؟",
    themeAffinity: [AFF.growth, AFF.confidence, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "listening",
    mantraEn: "I pause before I answer so my reply can carry real care.",
    mantraFa: "قبل از جواب می‌ایستم تا پاسخم واقعاً مراقبت باشد.",
    mantraEnExploratory: "Who needs me to listen more than I fix today?",
    mantraFaExploratory: "امروز کی به شنیدن بیش از درست‌کردن نیاز دارد؟",
    themeAffinity: [AFF.love, AFF.healing, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "mercury",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "truth",
    mantraEn: "I choose honest words that protect both kindness and self-respect.",
    mantraFa: "حرف‌های راست را انتخاب می‌کنم که هم مهربان باشد هم احترام به خود.",
    mantraEnExploratory: "Where could softer truth replace a sharp silence?",
    mantraFaExploratory: "کجا حقیقت نرم‌تر می‌تواند جای سکوت تیز را بگیرد؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.release],
    isActive: true,
  },
];

const venus: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "love",
    mantraEn: "I let love move through me without demanding a perfect scene.",
    mantraFa: "می‌گذارم عشق از من بگذرد بی‌آنکه صحنه‌ای بی‌نقص بخواهم.",
    mantraEnExploratory: "How might I receive affection without scoring it?",
    mantraFaExploratory: "چگونه محبت را بی‌امتیاز گرفتن دریافت کنم؟",
    themeAffinity: [AFF.love, AFF.hope, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "beauty",
    mantraEn: "I notice one small beauty and let it soften my whole mood.",
    mantraFa: "یک زیبایی کوچک می‌بینم و می‌گذارم حالم را نرم کند.",
    mantraEnExploratory: "What tiny beauty is already in front of me?",
    mantraFaExploratory: "چه زیبایی کوچکی همین جلوی چشم من است؟",
    themeAffinity: [AFF.calm, AFF.hope, AFF.selfWorth],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "pleasure",
    mantraEn: "I allow simple pleasure without guilt because joy also heals.",
    mantraFa: "لذت ساده را بی‌احساس گناه اجازه می‌دهم؛ شادی هم شفاست.",
    mantraEnExploratory: "What harmless pleasure could I gift myself today?",
    mantraFaExploratory: "امروز چه لذت بی‌آسیبی به خودم هدیه دهم؟",
    themeAffinity: [AFF.healing, AFF.release, AFF.love],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "harmony",
    mantraEn: "I choose peace in my close ties over winning every small point.",
    mantraFa: "در روابط نزدیک صلح را به بردن هر نکته کوچک ترجیح می‌دهم.",
    mantraEnExploratory: "Where would harmony cost less than being right?",
    mantraFaExploratory: "کجا هماهنگی ارزان‌تر از راست بودن است؟",
    themeAffinity: [AFF.calm, AFF.love, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "worth",
    mantraEn: "I am allowed to want tenderness and still hold my standards.",
    mantraFa: "حق دارم ملایمت بخواهم و هم‌زمان حد و مرز داشته باشم.",
    mantraEnExploratory: "What would self-respect look like in love today?",
    mantraFaExploratory: "امروز احترام به خود در عشق چه شکلی است؟",
    themeAffinity: [AFF.selfWorth, AFF.confidence, AFF.love],
    isActive: true,
  },
  {
    planetTag: "venus",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "connection",
    mantraEn: "I reach out once with warmth and release the perfect reply.",
    mantraFa: "یک بار با گرمی دست می‌دهم و جواب بی‌نقص را رها می‌کنم.",
    mantraEnExploratory: "Who might welcome a simple warm check-in?",
    mantraFaExploratory: "کی از یک سرکوچک گرم استقبال می‌کند؟",
    themeAffinity: [AFF.love, AFF.hope, AFF.healing],
    isActive: true,
  },
];

const mars: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "action",
    mantraEn: "I take one brave step today and trust momentum to meet me.",
    mantraFa: "امروز یک قدم شجاع برمی‌دارم و به تکانه اعتماد می‌کنم.",
    mantraEnExploratory: "What is the smallest brave action open to me?",
    mantraFaExploratory: "کوچک‌ترین کار شجاعانهٔ ممکن چیست؟",
    themeAffinity: [AFF.confidence, AFF.focus, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "courage",
    mantraEn: "I face what I avoided with breath and a steady voice.",
    mantraFa: "روبرو می‌شوم با چیزی که فراری بودم، با نفس و صدای آرام.",
    mantraEnExploratory: "What avoidance is ready to be faced gently?",
    mantraFaExploratory: "چه فراری‌ای آمادهٔ روبه‌رویی ملایم است؟",
    themeAffinity: [AFF.confidence, AFF.healing, AFF.release],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "energy",
    mantraEn: "I channel my fire into one task until it is honestly done.",
    mantraFa: "آتشم را در یک کار می‌ریزم تا راست‌حساب تمام شود.",
    mantraEnExploratory: "Where should my energy go first for real progress?",
    mantraFaExploratory: "انرژی‌ام را اول کجا بریزم که پیشرفت راستین شود؟",
    themeAffinity: [AFF.focus, AFF.growth, AFF.discipline],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "assertion",
    mantraEn: "I ask directly for what I need without apologizing for existing.",
    mantraFa: "رک می‌خواهم آنچه لازم دارم بی‌عذرخواهی برای بودنم.",
    mantraEnExploratory: "What direct request would honor my needs today?",
    mantraFaExploratory: "امروز چه درخواست رکّی به نیازم احترام می‌گذارد؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.love],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "drive",
    mantraEn: "I aim my hunger at a goal that matches my deeper values.",
    mantraFa: "گرسنگی‌ام را به هدفی می‌زنم که با ارزش‌هایم یکی است.",
    mantraEnExploratory: "Does my drive still match what I truly value?",
    mantraFaExploratory: "آیا تکانه‌ام هنوز با آنچه باور دارم هم‌خوان است؟",
    themeAffinity: [AFF.growth, AFF.faith, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "mars",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "reset",
    mantraEn: "I cool my temper with water, air, and a slower next move.",
    mantraFa: "خشمم را با آب و هوا و حرکت بعدی آهسته‌تر خنک می‌کنم.",
    mantraEnExploratory: "What would help me reset before I react?",
    mantraFaExploratory: "چه چیزی قبل از واکنش مرا ریست می‌کند؟",
    themeAffinity: [AFF.calm, AFF.release, AFF.healing],
    isActive: true,
  },
];

const jupiter: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "expansion",
    mantraEn: "I widen my horizon one generous choice at a time.",
    mantraFa: "افق را یک انتخاب بخشنده در می‌گسترانم.",
    mantraEnExploratory: "Where could a little generosity expand my life?",
    mantraFaExploratory: "کجا کمی بخشش زندگی‌ام را گسترده می‌کند؟",
    themeAffinity: [AFF.growth, AFF.hope, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "faith",
    mantraEn: "I trust the stretch even when I cannot see the far shore.",
    mantraFa: "به کشش اعتماد می‌کنم حتی وقتی ساحل دور را نمی‌بینم.",
    mantraEnExploratory: "What might I trust beyond my current proof?",
    mantraFaExploratory: "فراتر از مدرک فعلی‌ام به چه می‌توانم اعتماد کنم؟",
    themeAffinity: [AFF.faith, AFF.hope, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "optimism",
    mantraEn: "I look for one honest reason this chapter can still grow me.",
    mantraFa: "یک دلیل راست‌حساب می‌جویم که این فصل مرا بسازد.",
    mantraEnExploratory: "What honest hopeful angle is still available?",
    mantraFaExploratory: "چه زاویهٔ امیدوارکنندهٔ راستی هنوز هست؟",
    themeAffinity: [AFF.hope, AFF.growth, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "abundance",
    mantraEn: "I notice enough here to share without feeding my scarcity fear.",
    mantraFa: "کفایت همین‌جا را می‌بینم تا بدهم بی‌ترس از کمبود.",
    mantraEnExploratory: "What do I already have enough of to offer?",
    mantraFaExploratory: "از چه چیزی همین حالا به اندازه دارم که بدهم؟",
    themeAffinity: [AFF.love, AFF.selfWorth, AFF.release],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "meaning",
    mantraEn: "I search for meaning in the lesson, not only in the prize.",
    mantraFa: "معنا را در درس می‌جویم نه فقط در جایزه.",
    mantraEnExploratory: "What lesson is trying to enlarge me now?",
    mantraFaExploratory: "چه درسی الآن می‌خواهد مرا بزرگ‌تر کند؟",
    themeAffinity: [AFF.growth, AFF.faith, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "jupiter",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "adventure",
    mantraEn: "I say yes to a healthy risk that makes my life feel wider.",
    mantraFa: "به ریسک سالم بله می‌گویم که زندگی‌ام را پهن‌تر کند.",
    mantraEnExploratory: "What safe adventure is calling my name?",
    mantraFaExploratory: "چه ماجرای امنی نام مرا صدا می‌زند؟",
    themeAffinity: [AFF.hope, AFF.confidence, AFF.release],
    isActive: true,
  },
];

const moon: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "intuition",
    mantraEn: "I trust the quiet nudge that arrives before the full proof.",
    mantraFa: "به نرم‌فشار آرام قبل از مدرک کامل اعتماد می‌کنم.",
    mantraEnExploratory: "What is my gut trying to whisper before I rush?",
    mantraFaExploratory: "احساس درونی قبل از عجله چه می‌گوید؟",
    themeAffinity: [AFF.calm, AFF.healing, AFF.faith],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "feelings",
    mantraEn: "I name my feeling without drowning it so it can move through.",
    mantraFa: "احساسم را نام می‌گذارم بی‌غرق شدن تا رد شود.",
    mantraEnExploratory: "What feeling needs a name before it can pass?",
    mantraFaExploratory: "چه احساسی برای گذر به نام نیاز دارد؟",
    themeAffinity: [AFF.healing, AFF.release, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "nurture",
    mantraEn: "I mother myself with rest, food, and gentle inner talk.",
    mantraFa: "با استراحت، غذا و حرف ملایم با خودم مادری می‌کنم.",
    mantraEnExploratory: "How would I comfort a tired version of me?",
    mantraFaExploratory: "به نسخهٔ خستهٔ خودم چطور دلداری می‌دادم؟",
    themeAffinity: [AFF.love, AFF.calm, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "rhythm",
    mantraEn: "I follow my natural pace without forcing a constant peak.",
    mantraFa: "به ریتم طبیعی‌ام پایبندم بی‌اجبار به اوج دائم.",
    mantraEnExploratory: "What pace fits my body and mood today?",
    mantraFaExploratory: "امروز چه سرعتی به بدن و حالم می‌خورد؟",
    themeAffinity: [AFF.calm, AFF.focus, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "memory",
    mantraEn: "I honor old pain without letting it steer every new choice.",
    mantraFa: "به درد قدیمی احترام می‌گذارم ولی نمی‌گذارم همهٔ انتخاب‌های تازه را براند.",
    mantraEnExploratory: "Which memory needs honoring but not the wheel?",
    mantraFaExploratory: "کدام خاطره محترم است ولی نباید فرمان بگیرد؟",
    themeAffinity: [AFF.healing, AFF.release, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "moon",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "safety",
    mantraEn: "I build safety in small rituals that tell my body it is home.",
    mantraFa: "با آیین‌های کوچک امنیت می‌سازم که به بدن بگوید خانه اینجاست.",
    mantraEnExploratory: "What tiny ritual would signal safety to me?",
    mantraFaExploratory: "چه آیین کوچکی به من امنیت می‌دهد؟",
    themeAffinity: [AFF.calm, AFF.faith, AFF.love],
    isActive: true,
  },
];

const sun: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "identity",
    mantraEn: "I show up as myself even when the room feels too bright.",
    mantraFa: "خودم را نشان می‌دهم حتی وقتی اتاق زیادی روشن است.",
    mantraEnExploratory: "Where am I hiding a real part of my identity?",
    mantraFaExploratory: "کجا بخشی از هویتم را پنهان کرده‌ام؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "visibility",
    mantraEn: "I let one honest part of me be seen without rehearsing perfection.",
    mantraFa: "یک بخش راستین را بی‌تمرین کمال دیده می‌شود می‌گذارم.",
    mantraEnExploratory: "What truth about me could tolerate gentle light?",
    mantraFaExploratory: "چه حقیقتی از من تحت نور ملایم دوام می‌آورد؟",
    themeAffinity: [AFF.confidence, AFF.love, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "vitality",
    mantraEn: "I feed my life force with sleep, sun, and purpose I chose.",
    mantraFa: "نیروی زندگی را با خواب، آفتاب و هدفی که خودم برگزیدم می‌خورانم.",
    mantraEnExploratory: "What restores my vitality in a simple way?",
    mantraFaExploratory: "چه چیز ساده‌ای توانم را برمی‌گرداند؟",
    themeAffinity: [AFF.growth, AFF.focus, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "purpose",
    mantraEn: "I align my day with one purpose that feels true to my core.",
    mantraFa: "روزم را با یک هدف هم‌راستا با هسته‌ام همسو می‌کنم.",
    mantraEnExploratory: "What purpose still feels alive in my chest?",
    mantraFaExploratory: "چه هدفی هنوز در سینه‌ام زنده است؟",
    themeAffinity: [AFF.faith, AFF.focus, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "confidence",
    mantraEn: "I stand in my worth without shrinking when others shine too.",
    mantraFa: "در ارزشم می‌ایستم و کوچک نمی‌شوم وقتی دیگران هم می‌درخشند.",
    mantraEnExploratory: "Where could I share light instead of compete?",
    mantraFaExploratory: "کجا می‌توانم نور بدهم به‌جای رقابت؟",
    themeAffinity: [AFF.confidence, AFF.selfWorth, AFF.love],
    isActive: true,
  },
  {
    planetTag: "sun",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "warmth",
    mantraEn: "I lead with warmth because strength without care feels hollow.",
    mantraFa: "با گرمی پیش می‌روم؛ قدرت بی‌مراقبت توخالی است.",
    mantraEnExploratory: "How could warmth lead my next hard conversation?",
    mantraFaExploratory: "گرمی چگونه سخت‌ترین گفتگو را پیش ببرد؟",
    themeAffinity: [AFF.love, AFF.healing, AFF.calm],
    isActive: true,
  },
];

const neptune: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "surrender",
    mantraEn: "I release the grip when control is only fear in disguise.",
    mantraFa: "وقتی کنترل فقط نقاب ترس است، مشت را باز می‌کنم.",
    mantraEnExploratory: "What am I ready to soften my grip on today?",
    mantraFaExploratory: "امروز از چه چیزی مشت را باز کنم؟",
    themeAffinity: [AFF.release, AFF.faith, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "dreams",
    mantraEn: "I let imagination visit without letting it erase my ground.",
    mantraFa: "خیال را راه می‌دهم بی‌آنکه زمین را از زیر پام بردارد.",
    mantraEnExploratory: "What dream needs a gentle boundary around it?",
    mantraFaExploratory: "چه رویایی به مرز ملایم نیاز دارد؟",
    themeAffinity: [AFF.hope, AFF.healing, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "compassion",
    mantraEn: "I soften toward myself first so compassion can be real.",
    mantraFa: "اول با خودم نرم می‌شوم تا رحم واقعی باشد.",
    mantraEnExploratory: "Where would self-compassion change everything?",
    mantraFaExploratory: "کجا دلسوزی به خود همه‌چیز را عوض می‌کند؟",
    themeAffinity: [AFF.healing, AFF.love, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "mystery",
    mantraEn: "I tolerate not knowing and still take the next faithful step.",
    mantraFa: "ندانستن را تحمل می‌کنم و باز قدم بعدی را با ایمان برمی‌دارم.",
    mantraEnExploratory: "What unknown am I willing to walk beside?",
    mantraFaExploratory: "کنار چه نادانسته‌ای حاضرم قدم بردارم؟",
    themeAffinity: [AFF.faith, AFF.hope, AFF.release],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "dissolve",
    mantraEn: "I let old stories dissolve in salt water and quiet breath.",
    mantraFa: "روایت‌های قدیم را در آب نمک و نفس آرام حل می‌کنم.",
    mantraEnExploratory: "Which old story is ready to dissolve?",
    mantraFaExploratory: "کدام روایت قدیمی آمادهٔ حل شدن است؟",
    themeAffinity: [AFF.release, AFF.healing, AFF.calm],
    isActive: true,
  },
  {
    planetTag: "neptune",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "spirit",
    mantraEn: "I open to something larger without abandoning my daily duties.",
    mantraFa: "به بزرگ‌تر از خودم باز می‌شوم بی‌آنکه وظایف روزمره را رها کنم.",
    mantraEnExploratory: "How might spirit and duty share the same day?",
    mantraFaExploratory: "روح و وظیفه چگونه در یک روز جمع شوند؟",
    themeAffinity: [AFF.faith, AFF.hope, AFF.focus],
    isActive: true,
  },
];

const pluto: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "transformation",
    mantraEn: "I let what must end end so a truer life can find space.",
    mantraFa: "می‌گذارم آنچه باید تمام شود تمام شود تا زندگی راستین جا باز کند.",
    mantraEnExploratory: "What ending would clear soil for real growth?",
    mantraFaExploratory: "چه پایانی خاک را برای رشد واقعی آماده می‌کند؟",
    themeAffinity: [AFF.release, AFF.growth, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "power",
    mantraEn: "I use my power to heal patterns instead of repeating harm.",
    mantraFa: "قدرتم را برای شفای الگوها به کار می‌برم نه تکرار آسیب.",
    mantraEnExploratory: "Where could I redirect power toward repair?",
    mantraFaExploratory: "کجا قدرت را به‌سوی ترمیم برگردانم؟",
    themeAffinity: [AFF.healing, AFF.confidence, AFF.love],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "shadow",
    mantraEn: "I look at my shadow with respect because it carries my truth.",
    mantraFa: "به سایه‌ام با احترام نگاه می‌کنم؛ حقیقت را دارد.",
    mantraEnExploratory: "What shadow truth is asking for integration?",
    mantraFaExploratory: "چه حقیقت سایه‌ای می‌خواهد یکپارچه شود؟",
    themeAffinity: [AFF.healing, AFF.selfWorth, AFF.release],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "rebirth",
    mantraEn: "I welcome a new chapter even if the doorway feels narrow.",
    mantraFa: "فصل تازه را خوش‌آمد می‌گویم حتی اگر درش باریک باشد.",
    mantraEnExploratory: "What rebirth is quietly knocking at my life?",
    mantraFaExploratory: "چه تولدی بی‌صدا به زندگی‌ام در می‌زند؟",
    themeAffinity: [AFF.hope, AFF.faith, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "intensity",
    mantraEn: "I hold intensity without spilling it on people who are fragile.",
    mantraFa: "شدت را نگه می‌دارم بی‌ریختن بر کسانی که شکننده‌اند.",
    mantraEnExploratory: "Where should I channel intensity with care?",
    mantraFaExploratory: "شدت را با مراقبت کجا هدایت کنم؟",
    themeAffinity: [AFF.focus, AFF.calm, AFF.love],
    isActive: true,
  },
  {
    planetTag: "pluto",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "release",
    mantraEn: "I compost old resentments into fuel for honest change.",
    mantraFa: "کینه‌های قدیم را کمپوست می‌کنم به سوخت برای تغییر راستین.",
    mantraEnExploratory: "What resentment is ready to become compost?",
    mantraFaExploratory: "چه کینه‌ای آمادهٔ کمپوست شدن است؟",
    themeAffinity: [AFF.release, AFF.growth, AFF.healing],
    isActive: true,
  },
];

const chiron: Omit<MantraTemplateSeed, "id">[] = [
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "healing",
    mantraEn: "I tend my wound without turning it into my whole identity.",
    mantraFa: "به زختم رسیدگی می‌کنم بی‌آنکه تمام هویتم شود.",
    mantraEnExploratory: "How can I heal without staying only the hurt?",
    mantraFaExploratory: "چگونه شفا بگیرم بی‌ماندن فقط «زخمی»؟",
    themeAffinity: [AFF.healing, AFF.selfWorth, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "mentor",
    mantraEn: "I turn my hardest lesson into gentle guidance for someone else.",
    mantraFa: "سخت‌ترین درسم را به راهنمایی ملایم برای دیگری تبدیل می‌کنم.",
    mantraEnExploratory: "Who might benefit from what I survived?",
    mantraFaExploratory: "کی از چیزی که از آن گذشتم سود می‌برد؟",
    themeAffinity: [AFF.love, AFF.healing, AFF.growth],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "vulnerability",
    mantraEn: "I share one real crack so connection does not stay shallow.",
    mantraFa: "یک ترک واقعی را به اشتراک می‌گذارم تا پیوند سطحی نماند.",
    mantraEnExploratory: "What safe vulnerability could deepen trust today?",
    mantraFaExploratory: "امروز چه آسیب‌پذیری امنی اعتماد را عمیق می‌کند؟",
    themeAffinity: [AFF.love, AFF.confidence, AFF.healing],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "wisdom",
    mantraEn: "I honor pain that taught me wisdom without romanticizing harm.",
    mantraFa: "به دردی که خرد آورد احترام می‌گذارم بی‌رمانتیک کردن آسیب.",
    mantraEnExploratory: "What pain taught me something I would keep?",
    mantraFaExploratory: "چه دردی چیزی آموخت که نگه می‌دارم؟",
    themeAffinity: [AFF.growth, AFF.faith, AFF.focus],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "acceptance",
    mantraEn: "I accept what I cannot rewrite and still choose my next line.",
    mantraFa: "آنچه را نمی‌توانم بازنویسی کنم می‌پذیرم و باز خط بعد را می‌نویسم.",
    mantraEnExploratory: "What acceptance would free my next sentence?",
    mantraFaExploratory: "چه پذیرشی جملهٔ بعدیم را آزاد می‌کند؟",
    themeAffinity: [AFF.calm, AFF.release, AFF.hope],
    isActive: true,
  },
  {
    planetTag: "chiron",
    aspectTag: "any",
    signTag: "any",
    qualityTag: "service",
    mantraEn: "I serve from scar-tissue strength without bleeding on others.",
    mantraFa: "از قدرت بافت‌اسکار خدمت می‌کنم بی‌ریختن خون بر دیگران.",
    mantraEnExploratory: "Where could humble service heal me too?",
    mantraFaExploratory: "کجا خدمت فروتنانه مرا هم شفا می‌دهد؟",
    themeAffinity: [AFF.healing, AFF.love, AFF.faith],
    isActive: true,
  },
];

function withIds(rows: Omit<MantraTemplateSeed, "id">[], prefix: string): MantraTemplateSeed[] {
  return rows.map((r, i) => ({
    ...r,
    id: `mt-${prefix}-${i + 1}`,
  }));
}

export const mantraTemplates: MantraTemplateSeed[] = [
  ...withIds(saturn, "saturn"),
  ...withIds(mercury, "mercury"),
  ...withIds(venus, "venus"),
  ...withIds(mars, "mars"),
  ...withIds(jupiter, "jupiter"),
  ...withIds(moon, "moon"),
  ...withIds(sun, "sun"),
  ...withIds(neptune, "neptune"),
  ...withIds(pluto, "pluto"),
  ...withIds(chiron, "chiron"),
];
