export interface Planet {
  name: string;
  symbol: string;
  keywords: string[];
  rulesOver: string[];
  healthyExpression: string;
  difficultExpression: string;
  inRelationships: string;
  inDecisionMaking: string;
  underTransit: string;
  bodyAndHealth: string;
}

export const PLANETS: Planet[] = [
  {
    name: "Sun",
    symbol: "☉",
    keywords: ["identity", "vitality", "purpose", "ego", "consciousness", "will"],
    rulesOver: ["core identity", "life force energy", "creative self-expression", "vitality", "conscious will", "the father archetype"],
    healthyExpression: "Radiates authentic self-expression, purpose, and generosity. A well-placed Sun person knows who they are and leads from that center without needing to diminish others.",
    difficultExpression: "Becomes prideful, attention-seeking, or inflexible. May define themselves too rigidly through external roles, achievements, or the opinions of others.",
    inRelationships: "The Sun shows how we shine in partnership — whether we lead with generosity or ego, whether we need to be the center of attention, and how authentically we express ourselves with those we love.",
    inDecisionMaking: "The Sun drives decisions aligned with identity and pride. We tend to choose what affirms who we believe ourselves to be. Strong Sun energy makes decisions feel natural and purposeful.",
    underTransit: "Transit activations of the natal Sun bring identity themes to the foreground — periods of heightened visibility, creative expression, or questioning who we are and what we stand for.",
    bodyAndHealth: "Governs the heart, spine, and overall vitality. Sun-related health themes often emerge around energy depletion, heart concerns, or conditions affecting the body's central life force.",
  },
  {
    name: "Moon",
    symbol: "☽",
    keywords: ["emotion", "instinct", "memory", "nurturing", "cycles", "the unconscious"],
    rulesOver: ["emotional nature", "subconscious patterns", "the mother archetype", "home and roots", "instincts and habits", "memory and the past"],
    healthyExpression: "Emotionally attuned, instinctively nurturing, and comfortably responsive to life's natural rhythms. A well-integrated Moon allows feelings to flow without flooding.",
    difficultExpression: "Reactive, moody, overly dependent, or emotionally defended. May unconsciously recreate the emotional patterns of early life without realizing it.",
    inRelationships: "The Moon reveals what we need to feel emotionally safe in love. It shows our attachment style, how we comfort and need to be comforted, and what triggers our deepest insecurities.",
    inDecisionMaking: "Moon-driven decisions are instinctive and emotional. We often 'just know' how we feel about a choice before we can articulate why. Ignoring the Moon leads to rational decisions that feel hollow.",
    underTransit: "Lunar transits shift emotional weather quickly — they stir up feelings, memories, and needs that may have been dormant. Full Moons especially mark emotional culminations.",
    bodyAndHealth: "Governs the stomach, breasts, lymphatic system, and bodily fluids. Moon-related health themes often connect to digestive sensitivity, immune cycles, and the body's response to emotional stress.",
  },
  {
    name: "Mercury",
    symbol: "☿",
    keywords: ["communication", "intellect", "analysis", "perception", "learning", "adaptability"],
    rulesOver: ["communication and speech", "thought processes and logic", "short-distance travel", "siblings", "learning and education", "commerce and trade"],
    healthyExpression: "Clear, curious, and adaptable thinking. A well-functioning Mercury person communicates effectively, learns quickly, and makes meaningful connections between ideas.",
    difficultExpression: "Scattered, critical, or overly analytical. May talk without listening, intellectualize emotions to avoid feeling them, or become anxious through endless mental loops.",
    inRelationships: "Mercury shows how we communicate with partners — whether we listen as well as we speak, how we argue, and whether our thought patterns support or undermine connection.",
    inDecisionMaking: "Mercury-led decisions are analytical and information-driven. We research, compare, and deliberate. The shadow is paralysis through over-analysis.",
    underTransit: "Mercury activations heighten mental activity, communication, and information processing. Mercury retrograde transits often bring revisiting of conversations, agreements, or thought patterns.",
    bodyAndHealth: "Governs the nervous system, lungs, arms, hands, and sensory organs. Stress often manifests in Mercury-ruled areas — anxiety, respiratory tension, and repetitive strain.",
  },
  {
    name: "Venus",
    symbol: "♀",
    keywords: ["love", "beauty", "values", "pleasure", "harmony", "attraction"],
    rulesOver: ["romantic love and attraction", "aesthetics and beauty", "personal values and what we desire", "money and possessions", "social grace and diplomacy", "the feminine principle"],
    healthyExpression: "Gracious, loving, aesthetically refined, and clear about their values. Healthy Venus energy attracts beauty and connection without grasping or losing themselves in others.",
    difficultExpression: "Vain, possessive, or unable to be alone. May confuse love with control, mistake comfort for contentment, or compromise values to maintain harmony.",
    inRelationships: "Venus is the heart of the relationship story — showing what we find attractive, how we express affection, and what we need to feel loved. It describes our love language.",
    inDecisionMaking: "Venus influences decisions through values, desire, and aesthetic preference. We choose what we find beautiful, pleasurable, or aligned with who we want to be.",
    underTransit: "Venus transits soften and beautify the area of life they touch. They often coincide with romantic developments, social opportunities, or renewed appreciation for beauty.",
    bodyAndHealth: "Governs the kidneys, veins, skin, and throat. Venus health themes often include sugar balance, skin conditions, and throat issues — particularly when values or love life are in conflict.",
  },
  {
    name: "Mars",
    symbol: "♂",
    keywords: ["action", "desire", "courage", "assertion", "energy", "drive"],
    rulesOver: ["physical energy and stamina", "desire and ambition", "assertiveness and aggression", "sexuality and passion", "competition and sport", "the masculine principle"],
    healthyExpression: "Decisive, courageous, and physically energized. Healthy Mars channels drive into purposeful action without trampling others. Passion becomes fuel, not fire.",
    difficultExpression: "Aggressive, reactive, or scattered. May act without thinking, pick unnecessary fights, or exhaust themselves and others with relentless drive.",
    inRelationships: "Mars describes how we pursue, assert, and express desire in relationships. It can reveal conflict style — whether we confront directly, passively resist, or suppress and explode.",
    inDecisionMaking: "Mars drives action-oriented decisions. It pushes us to move — sometimes prematurely. Strong Mars energy makes choices feel bold and instinctive.",
    underTransit: "Mars transits bring energy, urgency, and sometimes friction to the area they activate. They often coincide with increased drive, assertiveness, or irritability — and sometimes conflict.",
    bodyAndHealth: "Governs the muscles, head, adrenals, and blood. Mars health themes often involve inflammation, accidents, fevers, or adrenal exhaustion from sustained overdrive.",
  },
  {
    name: "Jupiter",
    symbol: "♃",
    keywords: ["expansion", "abundance", "wisdom", "optimism", "faith", "growth"],
    rulesOver: ["higher education and philosophy", "spiritual belief and faith", "abundance and good fortune", "long-distance travel and foreign cultures", "law, ethics, and social justice", "teachers and mentors"],
    healthyExpression: "Generous, wise, optimistic, and genuinely devoted to growth. Healthy Jupiter expands life through genuine faith, philosophy, and the courage to invest in possibility.",
    difficultExpression: "Overconfident, excessive, or dogmatic. May overextend in finance, weight, or promises. Can become lazy under luck's protection, or arrogant in beliefs.",
    inRelationships: "Jupiter in synastry brings joy, generosity, and expansion. It can elevate and inspire — but unchecked, may inflate unrealistic expectations or create a dynamic where one person always plays teacher.",
    inDecisionMaking: "Jupiter encourages risk and optimism. Jupiter-influenced decisions often feel like leaps of faith — and frequently pay off, though not always in the expected way.",
    underTransit: "Jupiter transits are often the most welcome: they bring expansion, opportunity, and fortunate encounters to whatever they touch. These are windows for growth, publishing, travel, and new possibilities.",
    bodyAndHealth: "Governs the liver, thighs, hips, and fat tissue. Jupiter health themes often involve overindulgence — issues with digestion, liver function, and conditions from excess.",
  },
  {
    name: "Saturn",
    symbol: "♄",
    keywords: ["discipline", "limitation", "karma", "responsibility", "structure", "mastery"],
    rulesOver: ["career and ambition", "time and aging", "limitations and boundaries", "karma and life lessons", "authority and tradition", "fear and the father complex"],
    healthyExpression: "Disciplined, patient, and masterful. A well-integrated Saturn person uses limitations as teachers and builds lasting achievements through sustained effort and integrity.",
    difficultExpression: "Rigid, fearful, overly critical, or stuck in structures that no longer serve. May self-sabotage through excessive caution or recreate harsh authority dynamics.",
    inRelationships: "Saturn in relationships brings longevity, commitment, and seriousness. It can also bring inhibition, fear of vulnerability, or dynamics that feel more like obligation than joy. Maturity makes Saturn relationships deepen.",
    inDecisionMaking: "Saturn demands caution and long-term thinking. Saturn-influenced decisions prioritize security, tradition, and proven paths over novelty or risk.",
    underTransit: "Saturn transits are refining fires. They test, pressure, and demand growth through restriction. These are the transit periods remembered as pivotal — the ones that forged something real.",
    bodyAndHealth: "Governs the skeleton, teeth, skin, and knees. Saturn health themes often involve structural issues, chronic conditions, and the literal or figurative weight we carry.",
  },
  {
    name: "Uranus",
    symbol: "♅",
    keywords: ["liberation", "rebellion", "innovation", "disruption", "freedom", "awakening"],
    rulesOver: ["sudden change and upheaval", "innovation and technology", "rebellion and revolution", "individuality and eccentricity", "humanitarian ideals", "the collective awakening"],
    healthyExpression: "Authentically individuated, inventive, and genuinely ahead of their time. Healthy Uranus energy liberates without destroying — it creates space for the new without burning everything down.",
    difficultExpression: "Chaotic, contrary, or emotionally unavailable. May crave freedom at the expense of intimacy, or disrupt for the sake of disruption rather than genuine change.",
    inRelationships: "Uranus in relationship charts brings electric attraction and non-conformity. These relationships feel awakening and exciting — but can also bring sudden disruptions or a persistent sense of distance.",
    inDecisionMaking: "Uranus disrupts the predictable. Decisions under Uranus influence feel sudden, unconventional, and sometimes shocking even to the person making them.",
    underTransit: "Uranus transits crack open whatever has become too rigid. They bring liberation and disruption simultaneously — the breakthrough and the breakdown often arrive together.",
    bodyAndHealth: "Governs the nervous system at a macro level, circulatory system, and ankles. Uranus health themes often involve sudden onset conditions, neurological disruptions, and stress-related electrical misfires.",
  },
  {
    name: "Neptune",
    symbol: "♆",
    keywords: ["mysticism", "illusion", "compassion", "dissolution", "spirituality", "transcendence"],
    rulesOver: ["spiritual experience and mysticism", "dreams, illusions, and idealization", "compassion and self-sacrifice", "artistic and creative transcendence", "addiction and escapism", "the collective unconscious"],
    healthyExpression: "Spiritually open, deeply creative, and compassionately attuned to the suffering of others. Healthy Neptune dissolves the ego's walls and opens to transcendent experience and artistic beauty.",
    difficultExpression: "Deluded, escapist, or prone to addiction. May idealize what isn't real, flee from reality, or sacrifice themselves to people or substances that take without giving.",
    inRelationships: "Neptune in synastry creates romantic idealization — seeing a partner as perfect rather than real. These connections feel fated and transcendent, but may dissolve when reality asserts itself.",
    inDecisionMaking: "Neptune blurs decision-making with longing, idealism, and wishful thinking. It's harder to discern clearly under Neptune influence — reality may be veiled until later.",
    underTransit: "Neptune transits bring periods of dissolving boundaries — between self and other, real and ideal, sacred and mundane. They can bring spiritual opening, confusion, or creative inspiration.",
    bodyAndHealth: "Governs the pineal gland, feet, immune system, and the body's sensitivity to substances. Neptune health themes often involve mysterious conditions, chemical sensitivities, and immune dysregulation.",
  },
  {
    name: "Pluto",
    symbol: "♇",
    keywords: ["transformation", "power", "death and rebirth", "depth", "intensity", "the shadow"],
    rulesOver: ["death, rebirth, and regeneration", "power and control", "the unconscious shadow", "collective transformation", "sexuality as power", "obsession and compulsion"],
    healthyExpression: "Profoundly transformative, psychologically deep, and empowering in their impact on others. Healthy Pluto energy faces the darkness without being consumed by it — and emerges regenerated.",
    difficultExpression: "Controlling, obsessive, or consumed by power dynamics. May manipulate unconsciously, draw to themselves the very darkness they fear, or become a vehicle for power they haven't yet integrated.",
    inRelationships: "Pluto in relationship charts creates intense, transformative bonds. These connections change both people — often through power dynamics, jealousy, and depth of feeling that can be overwhelming.",
    inDecisionMaking: "Pluto drives decisions from the depths — from compulsion, passion, and the soul-level recognition that something must change. Pluto choices often feel irrevocable.",
    underTransit: "Pluto transits are the deepest renovations the chart will experience. They dismantle what is no longer authentic to make space for what must be born. These periods are rarely comfortable — and rarely forgotten.",
    bodyAndHealth: "Governs the reproductive system, colon, and eliminative organs. Pluto health themes often involve hidden or systemic conditions — things that have been building underground before surfacing.",
  },
  {
    name: "Chiron",
    symbol: "⚷",
    keywords: ["wound", "healing", "wisdom through pain", "the wounded healer", "bridge", "integration"],
    rulesOver: ["core wounds and where we feel broken", "the healing gifts we develop through pain", "the bridge between Saturn and Uranus", "maverick wisdom", "mentorship and teaching from experience", "where we feel perpetually not enough"],
    healthyExpression: "A wounded healer who has transformed personal suffering into compassion and wisdom. Healthy Chiron integration means the wound is acknowledged, tended to, and eventually turned into a source of meaning.",
    difficultExpression: "A festering wound that poisons rather than heals — overidentification with pain, helping others as avoidance of self-help, or an inability to believe healing is possible.",
    inRelationships: "Chiron in synastry activates old wounds through intimate contact. This can be healing — like finding the one person who truly understands — or it can re-wound if both people are unaware.",
    inDecisionMaking: "Chiron-influenced decisions are filtered through the lens of the core wound. We may avoid what triggers the wound, or we may be drawn to it repeatedly, seeking resolution.",
    underTransit: "Chiron transits open the wound for healing. These periods bring the core pain to the surface — not to hurt, but to offer the chance to finally tend to it with maturity and self-compassion.",
    bodyAndHealth: "Governs the holistic bridge between body and soul. Chiron health themes often involve chronic conditions that serve as teachers — pain that has something to say about the life being lived.",
  },
];
