export interface ZodiacSign {
  sign: string;
  symbol: string;
  element: "fire" | "earth" | "air" | "water";
  modality: "cardinal" | "fixed" | "mutable";
  rulingPlanet: string;
  keywords: string[];
  strengths: string[];
  blindSpots: string[];
  emotionalStyle: string;
  communicationStyle: string;
  relationshipStyle: string;
  workStyle: string;
  stressPattern: string;
  growthEdge: string;
}

export const ZODIAC_SIGNS: ZodiacSign[] = [
  {
    sign: "Aries",
    symbol: "♈",
    element: "fire",
    modality: "cardinal",
    rulingPlanet: "Mars",
    keywords: ["courageous", "pioneering", "impulsive", "direct", "enthusiastic", "competitive"],
    strengths: ["Natural leadership and initiative", "Fearless in the face of new challenges", "Infectious enthusiasm that inspires others", "Honest and refreshingly direct", "Resilient — bounces back quickly"],
    blindSpots: ["Impatience with slower-moving people or processes", "Tendency to start strong but lose interest", "Can act before thinking through consequences", "May struggle to consider others' emotional needs in the moment"],
    emotionalStyle: "Aries feels emotions intensely and immediately, often expressing them through action rather than words. Anger flares fast but usually passes just as quickly — rarely holding grudges.",
    communicationStyle: "Direct, bold, and energetic. Aries speaks their mind without much filtering, which others experience as refreshing honesty or bluntness depending on context.",
    relationshipStyle: "Aries pursues with passion and loves the thrill of new connection. They want a partner who matches their energy and can keep up — but need to learn that love deepens through patience, not conquest.",
    workStyle: "Thrives on initiating, leading, and competing. Aries does best when given autonomy and fresh challenges — routine kills their spark. They're the team member who starts three projects in a week.",
    stressPattern: "Under stress, Aries becomes irritable, reactive, and prone to blowing up situations that could be handled more gently. The urge to fight or flee activates quickly.",
    growthEdge: "Aries is here to learn that true courage includes slowing down, listening deeply, and following through — not just charging forward.",
  },
  {
    sign: "Taurus",
    symbol: "♉",
    element: "earth",
    modality: "fixed",
    rulingPlanet: "Venus",
    keywords: ["steadfast", "sensual", "patient", "reliable", "stubborn", "grounded"],
    strengths: ["Extraordinary patience and follow-through", "Deep loyalty in relationships", "Practical wisdom and financial common sense", "Ability to create beauty, comfort, and stability", "Stays calm when others panic"],
    blindSpots: ["Resistance to change even when change is clearly needed", "Can dig into a position and refuse to budge", "Comfort-seeking can become avoidance", "May prioritize security over growth"],
    emotionalStyle: "Taurus feels deeply but processes slowly. They need time and safety to open up emotionally, but once they trust you, their warmth and steadiness are profound.",
    communicationStyle: "Measured, thoughtful, and deliberate. Taurus thinks before speaking and means exactly what they say — not prone to exaggeration or hollow promises.",
    relationshipStyle: "Taurus loves through acts of service, physical presence, and steadfast loyalty. They are the partner who shows up consistently, remembers your preferences, and builds a life with you — not just promises one.",
    workStyle: "Methodical and persistent. Taurus executes slowly but with exceptional quality. They resist rushing and do their best work in stable, comfortable environments with clear expectations.",
    stressPattern: "When pushed past their comfort zone, Taurus can become immovable, overly indulgent (eating, spending, retreating), or silently resentful.",
    growthEdge: "Taurus is here to learn that security is not the same as stagnation — real growth requires releasing what has outlived its purpose.",
  },
  {
    sign: "Gemini",
    symbol: "♊",
    element: "air",
    modality: "mutable",
    rulingPlanet: "Mercury",
    keywords: ["curious", "adaptable", "witty", "social", "scattered", "communicative"],
    strengths: ["Quick, agile mind that connects disparate ideas", "Natural gift for communication and storytelling", "Adaptability — comfortable in almost any situation", "Playful wit that makes others feel at ease", "Ability to see multiple perspectives simultaneously"],
    blindSpots: ["Difficulty committing — to people, projects, or opinions", "Can skim the surface rather than going deep", "May say what people want to hear", "Mental restlessness can become anxiety"],
    emotionalStyle: "Gemini tends to intellectualize emotions, analyzing what they feel before fully experiencing it. They need mental connection as a pathway to emotional intimacy.",
    communicationStyle: "Lively, quick, and versatile. Gemini can talk about anything with almost anyone and shifts register effortlessly — playful one moment, analytical the next.",
    relationshipStyle: "Gemini needs mental stimulation and variety in love. A partner who keeps them intellectually engaged is irresistible; someone who bores them will not keep their attention long.",
    workStyle: "Thrives in environments that reward creative thinking, communication, and variety. Gemini shines in brainstorming, writing, networking, and teaching — less so in repetitive execution.",
    stressPattern: "Under stress, Gemini overthinks, becomes scattered, and may talk excessively as a way of processing or avoiding. Decision paralysis is common.",
    growthEdge: "Gemini is here to learn the value of depth — that staying present with one idea, one person, or one feeling long enough to truly know it is its own kind of freedom.",
  },
  {
    sign: "Cancer",
    symbol: "♋",
    element: "water",
    modality: "cardinal",
    rulingPlanet: "Moon",
    keywords: ["nurturing", "intuitive", "protective", "emotional", "tenacious", "empathic"],
    strengths: ["Deep emotional intelligence and empathy", "Fierce protectiveness of loved ones", "Powerful intuition that rarely misleads them", "Capacity to create warmth, belonging, and home", "Long memory — they never forget what matters"],
    blindSpots: ["Can absorb others' emotions as if they are their own", "Tendency to retreat rather than address conflict", "Past hurts can color present relationships", "The shell protects, but also isolates"],
    emotionalStyle: "Cancer experiences the world through feeling. They're deeply affected by the emotional atmosphere around them and need safe containers to process their rich inner world.",
    communicationStyle: "Indirect at first, but capable of profound emotional expression once trust is established. Cancer communicates best through care and checking in rather than confrontation.",
    relationshipStyle: "Cancer loves through nurturing, devotion, and creating a safe home base. They need emotional security and reciprocal care — and may become clingy when that security feels threatened.",
    workStyle: "Works best when feeling emotionally connected to their work and team. Cancer excels in roles that require care, intuition, and long-term commitment — counseling, caregiving, creative arts, and leadership.",
    stressPattern: "Under stress, Cancer withdraws into their shell, becomes moody, or clings to what feels familiar — even if it no longer serves them.",
    growthEdge: "Cancer is here to learn that they can be deeply feeling and emotionally sovereign — that their sensitivity is power, not fragility.",
  },
  {
    sign: "Leo",
    symbol: "♌",
    element: "fire",
    modality: "fixed",
    rulingPlanet: "Sun",
    keywords: ["confident", "generous", "dramatic", "loyal", "creative", "warm-hearted"],
    strengths: ["Magnetic presence that draws people in", "Enormous generosity and big-heartedness", "Natural leadership through inspiration, not fear", "Commitment to those they love is unwavering", "Creative courage — willing to put themselves out there"],
    blindSpots: ["Pride can make it hard to admit mistakes", "Hunger for validation may read as ego", "Can dominate conversations or dynamics without realizing it", "May take disinterest as personal rejection"],
    emotionalStyle: "Leo feels emotions large and expresses them expressively. Their joy is radiant; their hurt is equally visible. They need acknowledgment to feel emotionally secure.",
    communicationStyle: "Theatrical, warm, and commanding. Leo tells stories that draw people in, speaks with conviction, and has a natural ability to inspire and motivate.",
    relationshipStyle: "Leo loves deeply and loyally, but needs to feel admired and celebrated in return. A partner who consistently recognizes Leo's contributions will have their devotion for life.",
    workStyle: "Thrives in visible, creative, and leadership roles. Leo needs work that feels meaningful and where their contributions are seen. They excel on stage — literal or metaphorical.",
    stressPattern: "When stressed or uncelebrated, Leo can become dramatic, reactive, or demand attention in ways that push others away — the opposite of what they actually need.",
    growthEdge: "Leo is here to learn that true confidence doesn't require an audience — and that the most powerful thing they can do is shine without needing permission.",
  },
  {
    sign: "Virgo",
    symbol: "♍",
    element: "earth",
    modality: "mutable",
    rulingPlanet: "Mercury",
    keywords: ["analytical", "meticulous", "service-oriented", "practical", "discerning", "humble"],
    strengths: ["Extraordinary eye for detail and quality", "Deeply reliable — follows through on commitments", "Practical problem-solving and systems thinking", "Genuine desire to be of service to others", "High standards that elevate everything they touch"],
    blindSpots: ["Self-criticism can become corrosive", "Perfectionism leads to procrastination or overwork", "Tendency to focus on what's wrong rather than what's right", "May micro-manage or critique when anxious"],
    emotionalStyle: "Virgo tends to process emotions through analysis, sometimes at the expense of simply feeling. They express care through acts of service — doing, fixing, and improving.",
    communicationStyle: "Precise, organized, and thorough. Virgo means exactly what they say and expects the same clarity from others. They can come across as critical when they're actually trying to help.",
    relationshipStyle: "Virgo shows love by being useful — remembering details, handling logistics, anticipating needs. They need a partner who appreciates their effort and doesn't mistake their standards for judgment.",
    workStyle: "Meticulous, thorough, and hardworking. Virgo thrives in roles that require precision, analysis, and system-building. They improve everything they touch — but struggle to call anything 'finished.'",
    stressPattern: "Under stress, Virgo hyper-analyzes, becomes hypercritical (of themselves or others), and may spiral into anxiety about what could go wrong.",
    growthEdge: "Virgo is here to learn that imperfect action taken with love is often more healing than perfect inaction — and that they themselves deserve the care they so readily give others.",
  },
  {
    sign: "Libra",
    symbol: "♎",
    element: "air",
    modality: "cardinal",
    rulingPlanet: "Venus",
    keywords: ["diplomatic", "charming", "fair-minded", "indecisive", "relational", "aesthetic"],
    strengths: ["Natural gift for mediation and seeing all sides", "Deeply attuned to fairness and ethics", "Exceptional social grace and charm", "Eye for beauty and harmony in environment and relationship", "Thoughtful, balanced decision-making when not overwhelmed"],
    blindSpots: ["Difficulty making decisions, especially under pressure", "May suppress own needs to keep the peace", "Can tell people what they want to hear rather than the truth", "Conflict avoidance can create bigger problems later"],
    emotionalStyle: "Libra processes emotions through relationship and reflection. They often need to talk things through to understand what they actually feel — and can be deeply affected by the emotional harmony of their environment.",
    communicationStyle: "Gracious, diplomatic, and careful. Libra weighs their words and works hard to not offend — sometimes at the cost of clarity. They have a talent for beautiful, persuasive language.",
    relationshipStyle: "Libra is the natural partner — they thrive in one-on-one connection and give deeply in love. But they must learn to maintain their own identity within the relationship rather than mirroring their partner.",
    workStyle: "Excel in collaborative, aesthetic, or justice-oriented environments. Libra makes excellent mediators, designers, lawyers, and diplomats. They struggle with solo projects that lack clear feedback.",
    stressPattern: "Under stress, Libra vacillates endlessly, becomes passive-aggressive, or outsources their decisions to others — undermining the very fairness they stand for.",
    growthEdge: "Libra is here to learn that true balance includes their own needs — that the most harmonious relationships are built on honesty, not accommodation.",
  },
  {
    sign: "Scorpio",
    symbol: "♏",
    element: "water",
    modality: "fixed",
    rulingPlanet: "Pluto",
    keywords: ["intense", "perceptive", "transformative", "loyal", "secretive", "magnetic"],
    strengths: ["Penetrating psychological insight — they see what others miss", "Extraordinary depth of commitment and loyalty", "Fearlessness in facing what others avoid", "Capacity for profound transformation — in themselves and others", "Resilience that comes from having survived the depths"],
    blindSpots: ["Tendency toward jealousy and possessiveness", "Can hold grudges long past their usefulness", "Trust once broken is rarely repaired", "May use control as a substitute for vulnerability"],
    emotionalStyle: "Scorpio feels everything intensely and privately. They rarely show what they're experiencing until they trust you completely — and even then, only partially.",
    communicationStyle: "Strategic and purposeful. Scorpio reveals little about themselves while skillfully drawing out others. When they do speak their truth, it lands with weight and precision.",
    relationshipStyle: "Scorpio loves with complete intensity or not at all. They demand honesty, depth, and loyalty — and offer the same in return when trust is earned. Betrayal is rarely forgiven.",
    workStyle: "Thrives in research, investigation, strategy, and roles that require getting to the truth beneath the surface. Scorpio does their best work when fully invested — half-measures are not in their nature.",
    stressPattern: "Under stress, Scorpio becomes controlling, suspicious, or vengeful. The pain of perceived betrayal can activate a self-protective shutdown that damages the very bonds they value most.",
    growthEdge: "Scorpio is here to learn that vulnerability is not weakness — that allowing themselves to be seen fully is the deepest act of courage their soul can take.",
  },
  {
    sign: "Sagittarius",
    symbol: "♐",
    element: "fire",
    modality: "mutable",
    rulingPlanet: "Jupiter",
    keywords: ["adventurous", "philosophical", "optimistic", "honest", "restless", "expansive"],
    strengths: ["Infectious optimism that lifts everyone around them", "Genuine love of learning, travel, and expansion", "Philosophical depth alongside playful lightness", "Honesty that cuts through pretense", "Freedom-loving spirit that refuses to shrink"],
    blindSpots: ["Commitment to ideas over people can create distance", "Bluntness can wound without realizing it", "The next horizon is always more exciting than the present one", "May overextend and under-deliver"],
    emotionalStyle: "Sagittarius moves through emotions quickly, preferring to reframe and expand rather than dwell. They can struggle with sitting in difficulty without immediately seeking a silver lining.",
    communicationStyle: "Enthusiastic, direct, and philosophical. Sagittarius loves big conversations about meaning, ethics, and possibility. They speak in broad strokes and may miss the nuance of interpersonal dynamics.",
    relationshipStyle: "Sagittarius needs a partner who is a companion in adventure — intellectually, spiritually, and literally. They love freedom and need a relationship that feels like an expansion, not a cage.",
    workStyle: "Thrives in roles that involve travel, learning, teaching, or big-picture thinking. Sagittarius needs autonomy and purpose — bureaucracy and micromanagement are their natural enemies.",
    stressPattern: "Under stress, Sagittarius runs — physically or mentally. They may flee a difficult situation through travel, diversion, or grandiose planning that avoids the present problem.",
    growthEdge: "Sagittarius is here to learn that meaning is not only found on the horizon — that depth, commitment, and presence in the everyday are their own profound form of freedom.",
  },
  {
    sign: "Capricorn",
    symbol: "♑",
    element: "earth",
    modality: "cardinal",
    rulingPlanet: "Saturn",
    keywords: ["ambitious", "disciplined", "responsible", "patient", "reserved", "strategic"],
    strengths: ["Exceptional long-range planning and strategic thinking", "Self-discipline that others rarely match", "Deep sense of responsibility — rarely lets people down", "Respect for tradition and mastery built over time", "Quiet resilience through sustained effort"],
    blindSpots: ["May prioritize achievement over relationships and wellbeing", "Inner critic is relentless — both for themselves and others", "Can appear cold or aloof when actually deeply feeling", "Difficulty asking for help or appearing vulnerable"],
    emotionalStyle: "Capricorn manages emotions with composure and caution. They feel deeply but rarely demonstrate it publicly — their love is shown through showing up, not sentiment.",
    communicationStyle: "Direct, minimal, and purposeful. Capricorn values substance over style and tends toward understated, dry humor. They say what they mean and mean what they say.",
    relationshipStyle: "Capricorn shows love through provision, loyalty, and investment in the long-term. They need a partner who respects their ambitions and matches their commitment level.",
    workStyle: "Capricorn lives to excel. They're strategic, patient, and willing to work harder than anyone else. They're the team member who becomes the quiet authority over time — not through charm but through competence.",
    stressPattern: "Under stress, Capricorn works harder, withdraws emotionally, and becomes rigidly controlling. The fear of failure or public failure can drive them into isolation.",
    growthEdge: "Capricorn is here to learn that worthiness is not earned through achievement — that rest, play, and being loved without proving anything are not indulgences but necessities.",
  },
  {
    sign: "Aquarius",
    symbol: "♒",
    element: "air",
    modality: "fixed",
    rulingPlanet: "Uranus",
    keywords: ["visionary", "humanitarian", "independent", "eccentric", "detached", "innovative"],
    strengths: ["Genuine concern for humanity and the collective", "Visionary thinking that is ahead of its time", "Intellectual courage to hold unpopular truths", "Comfort with being different — doesn't need approval", "Natural connector of communities and ideas"],
    blindSpots: ["Emotional detachment can feel cold in intimate relationships", "Fixed opinions can become as rigid as any tradition they oppose", "May relate better to humanity in the abstract than to individuals", "Can use intellect to avoid emotional vulnerability"],
    emotionalStyle: "Aquarius processes emotion through concept and analysis. They are genuinely caring but can struggle with the messy, irrational nature of emotional intimacy.",
    communicationStyle: "Intellectual, unconventional, and often provocative. Aquarius challenges assumptions and loves a debate that expands thinking. They can come across as detached when they're actually deeply engaged.",
    relationshipStyle: "Aquarius needs a partner who is a genuine friend first — someone who honors their independence and engages their mind. They may struggle with the vulnerability that deep love requires.",
    workStyle: "Thrives in innovation, social impact, research, and technology. Aquarius needs autonomy, unconventional environments, and the sense that their work contributes to something beyond profit.",
    stressPattern: "Under stress, Aquarius becomes more intellectually rigid, emotionally distant, or chaotically rebellious — breaking things that don't need breaking to assert autonomy.",
    growthEdge: "Aquarius is here to learn that being truly connected to humanity starts with being willing to be truly seen by another human — that vulnerability is the bridge between ideals and love.",
  },
  {
    sign: "Pisces",
    symbol: "♓",
    element: "water",
    modality: "mutable",
    rulingPlanet: "Neptune",
    keywords: ["compassionate", "imaginative", "intuitive", "dreamy", "boundaryless", "spiritual"],
    strengths: ["Extraordinary empathy and capacity to understand others' pain", "Deep creative and spiritual imagination", "Nonjudgmental acceptance of all kinds of people", "Intuitive access to undercurrents that others miss", "Capacity for transcendent love, art, and devotion"],
    blindSpots: ["Porous boundaries — easily absorbs others' emotions as their own", "Can escape into fantasy, substances, or avoidance when reality is hard", "Difficulty with consistent follow-through and practical details", "May struggle to say no or assert their own needs"],
    emotionalStyle: "Pisces lives in the feeling realm more than any other sign. Their emotional experience is oceanic — vast, deep, and hard to separate from their sense of self.",
    communicationStyle: "Gentle, evocative, and often metaphorical. Pisces communicates through feeling and imagery more than logic. They are deeply sensitive to tone and can pick up on what isn't said.",
    relationshipStyle: "Pisces loves with complete self-dissolution — they merge with partners deeply and romantically. They need a partner who is kind, creative, and grounded enough to provide the structure Pisces floats in.",
    workStyle: "Thrives in creative, healing, and spiritual work — art, music, counseling, and spirituality are natural homes. Pisces needs meaningful work and may struggle in highly structured or transactional environments.",
    stressPattern: "Under stress, Pisces retreats into fantasy, escapism, or emotional overwhelm. They may become martyred, victimized, or simply disappear rather than face conflict directly.",
    growthEdge: "Pisces is here to learn that their sensitivity is not a wound to be managed but a gift to be wielded — and that healthy boundaries make their love more sustainable, not smaller.",
  },
];
