export interface TransitMeaning {
  transitPlanet: string;
  natalTarget: string;
  aspect: string;
  themes: string[];
  emotionalTone: string;
  practicalExpression: string;
  timingNote: string;
  caution: string;
  domain: string[];
}

export const TRANSIT_MEANINGS: TransitMeaning[] = [
  // ─── JUPITER TRANSITS ───────────────────────────────────────────────────────
  {
    transitPlanet: "Jupiter",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["expansion", "confidence", "opportunity", "visibility", "growth"],
    emotionalTone: "Optimistic, energized, and ready to grow — a sense of rightness about your direction.",
    practicalExpression: "A peak period for career visibility, creative projects, and personal confidence. Opportunities may appear in teaching, travel, publishing, or leadership. This is a time to launch, apply, and say yes.",
    timingNote: "Lasts approximately 2-3 weeks while exact; the broader window is about 2 months.",
    caution: "Overconfidence and overextension are real risks. Not every opportunity that arrives deserves a yes — discernment still matters.",
    domain: ["career", "inner", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Sun",
    aspect: "trine",
    themes: ["ease", "growth", "recognition", "confidence", "flow"],
    emotionalTone: "A quiet, sustained sense of forward momentum — things feel easier and more aligned than usual.",
    practicalExpression: "Natural progress in career and personal goals without the intense push of a conjunction. Good timing for consolidating gains, pursuing education, or expanding professional reach.",
    timingNote: "Lasts 3-4 weeks while within orb; builds gradually.",
    caution: "The ease of the trine can make it easy to coast — active effort still multiplies the benefit.",
    domain: ["career", "expansion", "inner"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Sun",
    aspect: "sextile",
    themes: ["opportunity", "growth", "confidence", "networking", "learning"],
    emotionalTone: "Mildly optimistic and socially engaged — a pleasant sense of things opening up.",
    practicalExpression: "Good period for networking, taking on new learning, expanding your professional or creative reach. Doors open when you knock.",
    timingNote: "2-3 weeks while within orb.",
    caution: "A sextile requires initiative — the opportunity is available but won't be handed to you.",
    domain: ["career", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Sun",
    aspect: "square",
    themes: ["overreach", "growth tension", "reality check", "ambition excess", "adjustment"],
    emotionalTone: "Restless and eager, but with a note of friction — ambition slightly exceeds present capacity.",
    practicalExpression: "Growth is still available but requires more calibration. Plans made now may need revision. Be particularly careful about financial overextension and making promises you can't keep.",
    timingNote: "2-3 weeks acute; the tension prompts necessary adjustments.",
    caution: "Jupiter squares inflate confidence without matching resources — avoid significant financial risks or overcommitments during this window.",
    domain: ["career", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Sun",
    aspect: "opposition",
    themes: ["balance", "partnership opportunity", "perspective", "excess from others", "public growth"],
    emotionalTone: "A feeling of being stretched between personal vision and what others want from you.",
    practicalExpression: "Partnerships and collaborations are highlighted — often in beneficial ways. Others may bring opportunities. The challenge is maintaining your own direction while accepting expansion from outside sources.",
    timingNote: "2-3 weeks exact; broader influence about 6 weeks.",
    caution: "Giving too much credit to others' enthusiasm — not every partnership proposal is what it appears. Assess realistically.",
    domain: ["career", "relationships", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional expansion", "nurturing abundance", "home growth", "emotional warmth", "contentment"],
    emotionalTone: "Deeply content and emotionally generous — a feeling of inner fullness.",
    practicalExpression: "Home improvements, family celebrations, emotional healing, and a genuine sense of emotional abundance. Nurturing others and yourself comes naturally. A beautiful time for creative emotional work.",
    timingNote: "2-3 weeks acute.",
    caution: "Emotional excess — overeating, overspending for comfort, or over-investing emotionally in situations that don't warrant it.",
    domain: ["inner", "relationships", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Moon",
    aspect: "trine",
    themes: ["emotional ease", "family harmony", "contentment", "nurturing flow", "home peace"],
    emotionalTone: "Quietly happy and emotionally settled — a period of genuine comfort.",
    practicalExpression: "Family relationships flow well. A good time for home projects, nurturing creativity, and investing in your own emotional wellbeing.",
    timingNote: "2-3 weeks.",
    caution: "Minimal — this is one of the most comfortable transit energies. The only caution is not allowing comfort to become complacency.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Moon",
    aspect: "square",
    themes: ["emotional overwhelm", "domestic tension", "oversentimentality", "family friction", "emotional excess"],
    emotionalTone: "Emotionally heightened — feelings are bigger than the situation warrants.",
    practicalExpression: "Family dynamics may feel amplified. Emotional needs feel larger and harder to satisfy. Be aware of over-promising in relationships or making significant domestic decisions from heightened emotional states.",
    timingNote: "2-3 weeks.",
    caution: "Major domestic decisions or emotional investments made under this transit may feel right but need reviewing when the energy passes.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["mental expansion", "communication abundance", "publishing", "learning", "big ideas"],
    emotionalTone: "Intellectually excited and verbally abundant — ideas arrive faster than they can be processed.",
    practicalExpression: "Excellent for writing, publishing, presenting, teaching, and expanding how you communicate. Ideas flow generously. A good time to start a course, begin a book, or launch a communications project.",
    timingNote: "2-3 weeks.",
    caution: "Mental overload and exaggeration — Jupiter expands Mercury's tendency to have more ideas than can be executed. Prioritize ruthlessly.",
    domain: ["communication", "expansion", "career"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Mercury",
    aspect: "trine",
    themes: ["clear thinking", "learning ease", "good communication", "idea flow", "teaching"],
    emotionalTone: "Mentally clear, curious, and at ease with expression.",
    practicalExpression: "Smooth period for writing, learning, negotiating, and communicating. Ideas come easily and are well-received. A good time for study and intellectual pursuits.",
    timingNote: "2-3 weeks.",
    caution: "Can lead to overconfidence in how ideas will land — remember that clarity to you isn't always clarity to your audience.",
    domain: ["communication", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["romantic abundance", "financial opportunity", "pleasure", "beauty", "social expansion"],
    emotionalTone: "Warm, loving, and pleasurably expansive — a sense of being blessed in matters of the heart.",
    practicalExpression: "A favored period for romance, social life, creative projects, and financial opportunity. New relationships may begin or existing ones deepen with warmth. Aesthetic projects flourish.",
    timingNote: "2-3 weeks.",
    caution: "Over-indulgence — in spending, eating, or romantic idealization. Jupiter with Venus inflates desire.",
    domain: ["love", "career", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Venus",
    aspect: "trine",
    themes: ["romantic ease", "creative flow", "financial goodwill", "social warmth", "harmony"],
    emotionalTone: "Gracious and loving — relationships feel easy and reciprocal.",
    practicalExpression: "A pleasant period for all Venus-ruled areas: romance, art, beauty, and finances. Income may increase or a financial opportunity arrives without significant effort.",
    timingNote: "2-3 weeks.",
    caution: "Very few downsides — the main risk is not taking advantage of genuinely good timing.",
    domain: ["love", "career"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Mars",
    aspect: "conjunction",
    themes: ["peak energy", "bold action", "drive", "ambition surge", "physical vitality"],
    emotionalTone: "Charged, enthusiastic, and ready to act — perhaps over-ready.",
    practicalExpression: "Exceptional time for launching ambitious projects, physical endeavors, and asserting yourself in competitive arenas. Energy and motivation are at a peak.",
    timingNote: "2-3 weeks.",
    caution: "Overexertion and recklessness. The combination of Jupiter's excess with Mars's drive can produce impulsive risks. Avoid rushing into conflicts.",
    domain: ["career", "inner", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["structure expansion", "career achievement", "mature growth", "building abundance", "discipline rewarded"],
    emotionalTone: "Cautiously optimistic — as though something real is finally being recognized.",
    practicalExpression: "Hard work pays off in tangible, structural ways. Career advancement, formal recognition, or the successful completion of long-term efforts. A time when discipline meets opportunity.",
    timingNote: "2-4 weeks.",
    caution: "The conjunction of Jupiter and Saturn is powerful but requires patience — rushing the process undermines what's actually being built.",
    domain: ["career", "expansion", "inner"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["new beginning", "personal growth", "visibility", "optimism", "fresh start"],
    emotionalTone: "Buoyant and ready to begin — a felt sense of stepping into a new chapter.",
    practicalExpression: "A genuine fresh start period. First impressions are excellent; new opportunities find you. Physical vitality is high. This is one of the best times to launch anything new, including a new version of yourself.",
    timingNote: "2-3 weeks exact; the window of influence is 1-2 months.",
    caution: "Overconfidence and over-promising. The beginning energy is real — but it must be followed by sustained effort.",
    domain: ["career", "inner", "expansion"],
  },
  {
    transitPlanet: "Jupiter",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career peak", "public success", "recognition", "achievement", "professional expansion"],
    emotionalTone: "Proud, purposeful, and publicly confident.",
    practicalExpression: "The most career-significant Jupiter transit. Promotions, public recognition, professional milestones, and expanded reputation are all favored. Launch publicly now.",
    timingNote: "2-4 weeks exact; this period should be leveraged actively.",
    caution: "Pride and overextension. Visibility also means being seen when things go wrong. Act with integrity.",
    domain: ["career", "expansion"],
  },
  // ─── SATURN TRANSITS ────────────────────────────────────────────────────────
  {
    transitPlanet: "Saturn",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["accountability", "identity test", "serious work", "limitation", "maturity"],
    emotionalTone: "Serious, somewhat heavy, and deeply committed to what is real and lasting.",
    practicalExpression: "A defining period of accountability and identity refinement. Career and personal identity are tested and restructured. What survives is more authentic than what was there before. Avoid shortcuts.",
    timingNote: "Several months, with retrograde loops; felt acutely for 1-2 years.",
    caution: "Depression, isolation, and excessive self-criticism. Saturn on the Sun requires self-compassion as much as discipline.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Sun",
    aspect: "trine",
    themes: ["steady progress", "earned recognition", "disciplined growth", "stability", "long-term building"],
    emotionalTone: "Grounded, focused, and quietly productive.",
    practicalExpression: "One of the most productive Saturn transits — discipline and effort produce lasting results without excessive resistance. A good time for long-term projects, professional commitments, and building structures that will last.",
    timingNote: "Several months with retrograde movement.",
    caution: "The steadiness can feel slow. Don't mistake the lack of drama for a lack of progress.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Sun",
    aspect: "square",
    themes: ["pressure", "obstacle", "redirection", "confrontation", "reality check"],
    emotionalTone: "Pressured, frustrated, and aware of the gap between where you are and where you want to be.",
    practicalExpression: "Significant resistance in career and personal expression. Plans meet obstacles that demand rethinking. This is a refining period — what endures through the pressure is worth keeping.",
    timingNote: "Several months; often felt most acutely when exact.",
    caution: "Feeling defeated is a risk. Perspective matters: the obstacles are refining, not blocking permanently.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Sun",
    aspect: "opposition",
    themes: ["relationship accountability", "external pressure", "balance demands", "projection", "maturity test"],
    emotionalTone: "Stretched between personal needs and what others require of you — a feeling of being pulled into account.",
    practicalExpression: "Relationships and partnerships bring accountability themes forward. Others may challenge you or hold you to commitments. A time to meet obligations honestly.",
    timingNote: "Several months.",
    caution: "Projecting Saturn's demand for discipline onto others, or resenting the accountability others reflect back at you.",
    domain: ["career", "relationships", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional discipline", "inner work", "emotional restriction", "maturity", "family pressure"],
    emotionalTone: "Emotionally contained, sometimes lonely or heavy — a sense of carrying more than usual.",
    practicalExpression: "A period of deep emotional reckoning. Old emotional patterns, family wounds, and long-held grief may surface for resolution. Inner work done here creates lasting emotional maturity.",
    timingNote: "Several months with retrograde loops.",
    caution: "Isolation and emotional suppression. Seeking support — especially through therapy — is not weakness here. It's the wisest use of this energy.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Moon",
    aspect: "trine",
    themes: ["emotional stability", "mature feeling", "inner strength", "family structure", "grounded nurturing"],
    emotionalTone: "Emotionally steady and capable — less reactive, more grounded.",
    practicalExpression: "A productive time for building emotional structures: establishing boundaries, deepening self-knowledge, and stabilizing home life. Therapy, inner work, and honest conversations pay off.",
    timingNote: "Several months.",
    caution: "Minimal — this transit rewards emotional investment and consistency.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Moon",
    aspect: "square",
    themes: ["emotional blockage", "grief", "family tension", "emotional work", "isolation risk"],
    emotionalTone: "Emotionally constricted — feelings may feel blocked, denied, or too heavy to express.",
    practicalExpression: "A challenging but meaningful period for emotional work. Family tensions may arise. Old grief resurfaces. The path forward requires acknowledging rather than suppressing what is emotionally true.",
    timingNote: "Several months.",
    caution: "Prolonged low mood or grief without support. This transit particularly benefits from professional or community support.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["love test", "relationship seriousness", "value clarification", "financial discipline", "commitment question"],
    emotionalTone: "Serious and realistic about love — perhaps more aware of its limitations than its joys.",
    practicalExpression: "Relationships are tested for depth and genuine compatibility. Shallow connections may fall away. Financial tightening often accompanies this transit. What remains after the test is solid.",
    timingNote: "Several months.",
    caution: "Excessive pessimism about love or relationships. Loneliness during this transit is common but not permanent.",
    domain: ["love", "career", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Venus",
    aspect: "trine",
    themes: ["stable love", "committed relationships", "financial structure", "aesthetic discipline", "values clarity"],
    emotionalTone: "Quietly content and clear about what truly matters in love and finances.",
    practicalExpression: "A good period for formalizing commitments, financial planning, and creative projects that require sustained effort. Relationships that survive this transit have genuine foundations.",
    timingNote: "Several months.",
    caution: "Stability shouldn't be mistaken for settling. This transit supports depth, not resignation.",
    domain: ["love", "career"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["serious thinking", "mental discipline", "communication testing", "focused study", "mental maturity"],
    emotionalTone: "Mentally focused, somewhat serious, and less given to frivolous communication.",
    practicalExpression: "A time for deep, focused study and careful communication. Long-form projects, technical learning, and serious writing are favored. Conversations carry more weight.",
    timingNote: "Several months.",
    caution: "Mental depression or excessive self-criticism about intelligence. The mind is being sharpened, not condemned.",
    domain: ["communication", "career", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Mars",
    aspect: "conjunction",
    themes: ["energy restriction", "frustration", "disciplined action", "slowed ambition", "pressure"],
    emotionalTone: "Frustrated, contained, and aware of limitation — like driving with the handbrake on.",
    practicalExpression: "Energy and drive are tested by limitation and delay. Projects move slowly. The discipline applied here, though frustrating, produces durable results. Physical energy may be lower than usual.",
    timingNote: "Several months.",
    caution: "Suppressed anger and physical tension. Regular exercise and healthy outlets for frustration are essential.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["identity reset", "responsibility", "maturity", "new chapter with weight", "serious beginning"],
    emotionalTone: "Earnest, responsible, and aware that this moment requires showing up fully.",
    practicalExpression: "A significant reset of personal identity. The way you present yourself to the world is becoming more serious, mature, and responsible. New commitments feel weighty but real.",
    timingNote: "Several months; marks a major life chapter transition.",
    caution: "The heaviness of this period is real but temporary. What's being built now has lasting value.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Saturn",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career peak", "achievement", "public accountability", "professional structure", "maturity"],
    emotionalTone: "Sober, ambitious, and acutely aware of professional standing.",
    practicalExpression: "This is the most significant career transit possible — a peak and a reckoning simultaneously. Long-term career work comes to its natural conclusion or crystallizes into something lasting. Public accountability is high.",
    timingNote: "Several months; often felt for 1-2 years.",
    caution: "The pressure of Saturn at the MC can create fear of failure. Keep showing up — this is when the work produces legacy.",
    domain: ["career", "inner"],
  },
  // ─── MARS TRANSITS ───────────────────────────────────────────────────────────
  {
    transitPlanet: "Mars",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["peak energy", "drive", "initiation", "assertion", "vitality"],
    emotionalTone: "Fired up, ready to act, and somewhat impatient.",
    practicalExpression: "A burst of personal energy and drive. Excellent for starting projects, physical training, asserting yourself in competition, or any situation requiring courage and initiative.",
    timingNote: "1-2 weeks.",
    caution: "Aggression, recklessness, and burning out quickly. Channel the energy purposefully rather than letting it discharge in conflict.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Sun",
    aspect: "trine",
    themes: ["confident action", "energy", "productive effort", "drive", "momentum"],
    emotionalTone: "Energized and purposeful — action feels natural and aligned.",
    practicalExpression: "Physical energy is high and well-directed. Exercise, work, and assertive conversations go well. A time to push forward without much resistance.",
    timingNote: "1-2 weeks.",
    caution: "Overconfidence in physical capacity. Don't ignore signals of fatigue.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Sun",
    aspect: "square",
    themes: ["conflict", "frustration", "energy challenge", "assertion test", "impatience"],
    emotionalTone: "Irritable and confrontational — smaller frustrations feel larger.",
    practicalExpression: "Increased potential for conflict and ego clashes. Energy is high but misdirected. Be intentional about how you assert yourself and avoid picking fights that aren't worth it.",
    timingNote: "1-2 weeks.",
    caution: "Impulsive decisions and aggressive communication. Pause before responding.",
    domain: ["career", "inner", "relationships"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Sun",
    aspect: "opposition",
    themes: ["conflict with others", "competition", "assertion through relationship", "external drive", "projection"],
    emotionalTone: "Aware of tension with others — the push and pull of competition or conflict.",
    practicalExpression: "Conflict or competition with others is heightened. Rather than letting this become draining, use it as information about where you need to assert yourself more clearly.",
    timingNote: "1-2 weeks.",
    caution: "Projecting your own suppressed aggression onto others. The conflict you experience externally often mirrors an internal dynamic.",
    domain: ["relationships", "career", "inner"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional intensity", "reactive feelings", "passionate impulse", "domestic activity", "boldness in nurturing"],
    emotionalTone: "Emotionally charged and reactive — feelings come quickly and loudly.",
    practicalExpression: "Heightened emotional reactions and possible domestic friction. Physical energy is high but emotional. Good for home projects that require effort, or for voicing feelings that have been suppressed.",
    timingNote: "1-2 weeks.",
    caution: "Emotional outbursts and domestic conflicts. Give yourself space before reacting to emotional triggers.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Moon",
    aspect: "trine",
    themes: ["emotional courage", "passionate home life", "active nurturing", "emotional initiative"],
    emotionalTone: "Emotionally energized and willing to take action on feelings.",
    practicalExpression: "A good time to initiate conversations about emotional needs, make domestic improvements, or act on something you've felt strongly about but held back on.",
    timingNote: "1-2 weeks.",
    caution: "Ensuring energy expressed toward loved ones comes from care, not restlessness.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Moon",
    aspect: "square",
    themes: ["emotional conflict", "irritability", "family tension", "reactive feelings", "domestic friction"],
    emotionalTone: "Touchy and reactive — the emotional environment feels charged.",
    practicalExpression: "Family or domestic tensions are more likely. Old emotional patterns may trigger exaggerated responses. Physical restlessness needs an outlet.",
    timingNote: "1-2 weeks.",
    caution: "Saying things in anger that damage relationships. The intensity passes quickly — wait before responding to emotional triggers.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["mental sharpness", "assertive communication", "debate", "intellectual drive", "direct speech"],
    emotionalTone: "Sharp, assertive, and possibly argumentative.",
    practicalExpression: "The mind is quick and the mouth faster. Excellent for debates, negotiations, persuasive writing, and situations requiring mental courage. Watch for sharpness that wounds.",
    timingNote: "1-2 weeks.",
    caution: "Verbal aggression and hasty communication. Think before sending the sharp email.",
    domain: ["communication", "career"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["passion", "romantic intensity", "attraction", "creative boldness", "desire"],
    emotionalTone: "Intensely attracted — romantic and creative desire is heightened.",
    practicalExpression: "Romantic relationships intensify. New attractions are highly charged. Creative boldness is available. Sexual energy is prominent and can be channeled into creative work.",
    timingNote: "1-2 weeks.",
    caution: "Acting on purely physical attraction without considering emotional compatibility. Desire is high but discernment matters.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Venus",
    aspect: "square",
    themes: ["love friction", "desire frustration", "creative tension", "sexual tension", "value conflict"],
    emotionalTone: "Frustrated in love or creative expression — desire meets resistance.",
    practicalExpression: "Tension in romantic relationships is likely. Needs that feel urgent may not be easily met. Creative frustration can be channeled into bold creative work.",
    timingNote: "1-2 weeks.",
    caution: "Forcing romantic situations that aren't ready to move forward. Let the tension inform rather than drive action.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["drive meets resistance", "frustration", "discipline test", "physical tension", "ambition blocked"],
    emotionalTone: "Deeply frustrated — effort meets obstacles repeatedly.",
    practicalExpression: "Significant resistance to action. Projects and plans meet delays. Physical tension is high. The discipline required here is to work strategically rather than forcefully.",
    timingNote: "1-2 weeks.",
    caution: "Injury from pushing through physical resistance. Anger management is important — this combination produces explosive frustration.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["personal assertion", "high energy", "bold presence", "new initiative", "physical vitality"],
    emotionalTone: "Bold, energized, and personally assertive.",
    practicalExpression: "A peak energy period for personal action and initiation. Others notice your increased drive and presence. Physical vitality is high — excellent for fitness goals and new beginnings.",
    timingNote: "1-2 weeks.",
    caution: "Coming across as aggressive rather than assertive. The energy is powerful — channel it consciously.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Mars",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career action", "ambition surge", "professional assertion", "public drive", "bold career move"],
    emotionalTone: "Ambitious, driven, and ready to make a move professionally.",
    practicalExpression: "Excellent timing for career actions: asking for a raise, launching a project, asserting professional value. Drive and ambition are at their peak for career matters.",
    timingNote: "1-2 weeks.",
    caution: "Aggressiveness in professional settings can backfire. Channel the drive into confident action, not domination.",
    domain: ["career"],
  },
  // ─── VENUS TRANSITS ──────────────────────────────────────────────────────────
  {
    transitPlanet: "Venus",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["social warmth", "creative pleasure", "self-appreciation", "romance", "ease"],
    emotionalTone: "Warm, charming, and pleased with yourself and the world.",
    practicalExpression: "A pleasant period for social connections, romance, creative expression, and self-appreciation. You radiate warmth and attract positive responses. A good time to ask for what you want.",
    timingNote: "3-5 days.",
    caution: "Overindulgence in pleasure and comforts. The sweetness is real but brief.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional warmth", "nurturing pleasure", "domestic beauty", "affection", "comfort"],
    emotionalTone: "Affectionate, comfortable, and emotionally at ease.",
    practicalExpression: "Beautiful energy for home improvements, nurturing relationships, and receiving affection. Creativity in domestic settings flourishes. A good day for self-care.",
    timingNote: "3-5 days.",
    caution: "Sentimentality and overspending on comfort.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["charming communication", "creative writing", "social ease", "beautiful speech", "diplomacy"],
    emotionalTone: "Socially at ease and verbally charming.",
    practicalExpression: "An excellent day for negotiations, creative writing, charm-based communication, and reconnecting with people. Your words carry grace and persuasion.",
    timingNote: "3-5 days.",
    caution: "Telling people what they want to hear rather than the truth.",
    domain: ["communication", "love"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["beauty renewal", "love pleasure", "self-value", "attraction peak", "social fullness"],
    emotionalTone: "Deeply contented in your own skin and values.",
    practicalExpression: "A personal Venus return — a moment to celebrate what you value and to take pleasure in beauty, love, and connection. Attractions are heightened. Financial intuition is good.",
    timingNote: "3-5 days.",
    caution: "Overindulgence and impulse spending on beautiful things.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Mars",
    aspect: "conjunction",
    themes: ["passionate attraction", "romantic drive", "sexual energy", "creative boldness", "desire meets beauty"],
    emotionalTone: "Magnetized — passionate, attractive, and drawn to beauty.",
    practicalExpression: "Highly charged romantic and creative energy. Attraction is at a peak. A good time for creative projects that require both beauty and boldness.",
    timingNote: "3-5 days.",
    caution: "Acting on physical chemistry without emotional consideration.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["serious love", "commitment moment", "financial reality", "value discipline", "mature beauty"],
    emotionalTone: "Sobered in love — aware of what is real versus what is wished for.",
    practicalExpression: "A time for honest assessment of relationships and finances. Commitments are taken seriously. Not the most romantic energy, but it supports lasting choices.",
    timingNote: "3-5 days.",
    caution: "Pessimism about love or finances. The realism is useful but shouldn't become a reason to dismiss what's genuinely good.",
    domain: ["love", "career"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["personal charm", "magnetic presence", "attractive", "social ease", "beauty day"],
    emotionalTone: "Charming, magnetic, and personally at your best.",
    practicalExpression: "One of the best days for first impressions, social events, romantic encounters, and anything requiring charm and grace. You look and feel your best.",
    timingNote: "3-5 days.",
    caution: "Vanity and over-reliance on charm.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Venus",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["professional charm", "reputation enhancement", "creative career", "public grace", "career beauty"],
    emotionalTone: "Gracious, poised, and publicly appealing.",
    practicalExpression: "Favorable for professional visibility, creative career moves, and anything requiring public grace. A good day for performance, creative presentations, or networking.",
    timingNote: "3-5 days.",
    caution: "Relying on charm without substance in professional settings.",
    domain: ["career", "love"],
  },
  // ─── MERCURY TRANSITS ────────────────────────────────────────────────────────
  {
    transitPlanet: "Mercury",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["mental clarity", "communication peak", "identity expression", "verbal confidence", "sharp thinking"],
    emotionalTone: "Mentally sharp and verbally expressive.",
    practicalExpression: "Excellent for important conversations, presentations, writing, and decision-making. The mind and identity are aligned — you think and speak clearly about who you are.",
    timingNote: "2-3 days.",
    caution: "Over-analyzing personal identity rather than living from it.",
    domain: ["communication", "inner"],
  },
  {
    transitPlanet: "Mercury",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional articulation", "inner dialogue", "family communication", "feeling expressed in words"],
    emotionalTone: "More emotionally articulate than usual — able to put feelings into words.",
    practicalExpression: "A good day for emotional conversations, journaling, therapy, and expressing what you've been feeling but haven't been able to articulate.",
    timingNote: "2-3 days.",
    caution: "Over-thinking emotional situations instead of simply feeling them.",
    domain: ["communication", "inner"],
  },
  {
    transitPlanet: "Mercury",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["mental peak", "clarity", "communication", "mental agility", "decisions"],
    emotionalTone: "Mentally at peak — quick, clear, and well-expressed.",
    practicalExpression: "One of the best days for mental work: writing, studying, negotiating, and making decisions. The mind operates with unusual clarity.",
    timingNote: "2-3 days.",
    caution: "Analysis paralysis when clarity becomes over-analysis.",
    domain: ["communication", "career"],
  },
  {
    transitPlanet: "Mercury",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["charming conversation", "love communication", "diplomatic expression", "creative thinking", "beautiful words"],
    emotionalTone: "Gracious, tactful, and socially smooth.",
    practicalExpression: "An excellent day for love letters, apologies, negotiations, and charming conversation. The right words come naturally.",
    timingNote: "2-3 days.",
    caution: "Saying lovely things without backing them up.",
    domain: ["communication", "love"],
  },
  {
    transitPlanet: "Mercury",
    natalTarget: "Mars",
    aspect: "conjunction",
    themes: ["sharp debate", "mental drive", "assertive thinking", "quick decisions", "direct communication"],
    emotionalTone: "Sharp, quick, and ready to defend a position.",
    practicalExpression: "Good for debates, pitches, competitive thinking, and situations where you need mental speed and courage. The mind is a weapon today — use it wisely.",
    timingNote: "2-3 days.",
    caution: "Verbal aggression and hasty responses. Think before speaking.",
    domain: ["communication", "career"],
  },
  {
    transitPlanet: "Mercury",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["serious thinking", "cautious communication", "focused study", "planning", "mental discipline"],
    emotionalTone: "Serious, methodical, and mentally disciplined.",
    practicalExpression: "Good for detailed planning, legal matters, serious contracts, and focused technical work. Not ideal for light social communication.",
    timingNote: "2-3 days.",
    caution: "Overly negative thinking or excessive worry.",
    domain: ["communication", "career"],
  },
  {
    transitPlanet: "Mercury",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["verbal presence", "quick thinking", "social communication", "expressing identity", "networking"],
    emotionalTone: "Communicatively at ease — quick and present.",
    practicalExpression: "A good day for first meetings, job interviews, social networking, and any situation requiring you to represent yourself verbally.",
    timingNote: "2-3 days.",
    caution: "Talking more than listening — balance is key in conversations.",
    domain: ["communication", "inner"],
  },
  // ─── SUN TRANSITS ────────────────────────────────────────────────────────────
  {
    transitPlanet: "Sun",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["solar return", "birthday energy", "new year", "identity peak", "fresh start"],
    emotionalTone: "Energized and present in your own identity — a natural moment of renewal.",
    practicalExpression: "Your solar return period — the annual renewal of your life force. Intentions set around your birthday carry more weight than at other times. A moment for identity reflection and forward vision.",
    timingNote: "3-5 days; the solar return chart for the year is cast for the exact moment.",
    caution: "Overlooking this natural renewal point by treating your birthday as just another day.",
    domain: ["inner", "expansion"],
  },
  {
    transitPlanet: "Sun",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["new moon on natal", "emotional beginning", "seed planting", "instinct renewal"],
    emotionalTone: "Inward, fresh, and ready for a new emotional cycle.",
    practicalExpression: "If this coincides with a New Moon, it's particularly powerful for setting emotional intentions and beginning inner work. A time for listening to instinct.",
    timingNote: "3-5 days.",
    caution: "Over-interiority — balance inner focus with external responsiveness.",
    domain: ["inner"],
  },
  {
    transitPlanet: "Sun",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["love warmth", "creative pleasure", "social radiance", "beauty appreciation", "affection"],
    emotionalTone: "Warm, loving, and pleasure-oriented.",
    practicalExpression: "A warm, bright period for love, creativity, and social connection. Others are drawn to your warmth. Creative and romantic pursuits flourish.",
    timingNote: "3-5 days.",
    caution: "Overindulgence.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Sun",
    natalTarget: "Mars",
    aspect: "conjunction",
    themes: ["vitality peak", "energy surge", "drive", "initiative", "courage"],
    emotionalTone: "Fired up and ready for action.",
    practicalExpression: "Peak physical and volitional energy for the month. Excellent for initiating, competing, exercising, and asserting yourself.",
    timingNote: "3-5 days.",
    caution: "Aggression and overexertion.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Sun",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["reality focus", "accountability", "serious work", "identity meets discipline", "commitment"],
    emotionalTone: "Serious and focused — duty-oriented.",
    practicalExpression: "A good time for serious work, honoring commitments, and confronting what must be addressed. Not the most comfortable energy but productive.",
    timingNote: "3-5 days.",
    caution: "Excessive seriousness or self-criticism.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Sun",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["personal visibility", "fresh start", "new chapter", "identity expression", "energy"],
    emotionalTone: "Bright, present, and personally visible.",
    practicalExpression: "A strong energy day for first impressions, initiating, and presenting yourself. Others notice you. A natural fresh-start moment for personal beginnings.",
    timingNote: "3-5 days.",
    caution: "Overconfidence in first impressions.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Sun",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career visibility", "public moment", "professional expression", "achievement", "recognition"],
    emotionalTone: "Professionally confident and publicly visible.",
    practicalExpression: "One of the best days of the year for professional visibility. Present yourself, publish, present publicly, or have important career conversations.",
    timingNote: "3-5 days.",
    caution: "Public overexposure — say and do only what you'd be comfortable with the world seeing.",
    domain: ["career"],
  },
  // ─── MOON TRANSITS ───────────────────────────────────────────────────────────
  {
    transitPlanet: "Moon",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["emotional identity", "personal feeling", "vulnerability", "inner need meets outer expression"],
    emotionalTone: "Emotionally attuned to your core sense of self.",
    practicalExpression: "A brief but emotionally significant period where feelings and identity align. Good for authentic conversations and creative expression from the heart.",
    timingNote: "Hours to 1 day.",
    caution: "Emotional sensitivity — you may feel things more personally than usual.",
    domain: ["inner"],
  },
  {
    transitPlanet: "Moon",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional reset", "instinct aligned", "feeling peak", "personal cycle"],
    emotionalTone: "Emotionally in sync with your own nature — feelings are clear and direct.",
    practicalExpression: "Monthly emotional reset point. Good for checking in with your feelings, setting emotional intentions, and trusting your instincts.",
    timingNote: "Hours to 1 day.",
    caution: "Emotional reactivity — your feelings may be heightened.",
    domain: ["inner"],
  },
  {
    transitPlanet: "Moon",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["emotional warmth", "love feeling", "social ease", "pleasure", "affection"],
    emotionalTone: "Warm, affectionate, and emotionally open to love and beauty.",
    practicalExpression: "A lovely energy for emotional intimacy, creative feeling, and social warmth. Good for dates, family gatherings, and creative expression.",
    timingNote: "Hours to 1 day.",
    caution: "Emotional overindulgence or sentimentality.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Moon",
    natalTarget: "Mars",
    aspect: "conjunction",
    themes: ["emotional charge", "passionate feeling", "domestic action", "reactive energy"],
    emotionalTone: "Emotionally charged and somewhat reactive — feelings and drive are fused.",
    practicalExpression: "Energy for action driven by feeling. Good for physical activity that processes emotions. Be aware that emotional reactions are faster and stronger than usual.",
    timingNote: "Hours to 1 day.",
    caution: "Emotional impulsiveness. Avoid important confrontations when you're in this state.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Moon",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["emotional weight", "responsibility", "serious feeling", "subdued mood", "inner work"],
    emotionalTone: "Emotionally subdued or heavyhearted — a sense of carrying more than usual.",
    practicalExpression: "Brief but sobering emotional energy. A good time for quiet inner work, journaling, and attending to responsibilities. Not ideal for social events or important emotional conversations.",
    timingNote: "Hours to 1 day.",
    caution: "Allowing a temporarily low mood to color your long-term perspective.",
    domain: ["inner"],
  },
  {
    transitPlanet: "Moon",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["emotional presence", "personal feeling day", "vulnerability", "instinct active"],
    emotionalTone: "Emotionally present and personally sensitive.",
    practicalExpression: "Your emotional nature is on the surface today. A good day for self-care, emotional check-ins, and honest conversations about feelings.",
    timingNote: "Hours to 1 day.",
    caution: "Being overly reactive or wearing your heart too openly in contexts that don't support it.",
    domain: ["inner"],
  },
  // ─── URANUS TRANSITS ─────────────────────────────────────────────────────────
  {
    transitPlanet: "Uranus",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["radical change", "liberation", "identity upheaval", "awakening", "breakthrough"],
    emotionalTone: "Electrified and unsettled — the ground is shifting under your identity.",
    practicalExpression: "A once-in-a-lifetime (if at all) period of radical identity transformation. The life as currently constructed may not survive intact — which is precisely the point. Breakthroughs in how you understand yourself and your purpose arrive suddenly.",
    timingNote: "Several months with retrograde loops; the full influence is 1-2 years.",
    caution: "Destroying what still has value in the rush to be free. Ground yourself — liberation should serve your highest purpose, not just escape pressure.",
    domain: ["inner", "career", "expansion"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Sun",
    aspect: "trine",
    themes: ["liberating growth", "innovation", "authentic change", "exciting development", "breakthrough ease"],
    emotionalTone: "Excited, free, and open to unexpected possibilities.",
    practicalExpression: "An electric period where identity evolution happens naturally and excitingly. Breakthroughs in career, creative expression, and personal freedom come without the trauma of other Uranus transits.",
    timingNote: "Several months.",
    caution: "The ease of this transit can make changes feel more permanent than they are — ground new directions in practical action.",
    domain: ["inner", "career", "expansion"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Sun",
    aspect: "square",
    themes: ["identity crisis", "disruption", "rebellion", "forced change", "awakening pressure"],
    emotionalTone: "Internally destabilized and restless — the familiar no longer fits.",
    practicalExpression: "Significant disruption to how you understand your identity and life path. The structures that defined you are cracking — often from the inside. Career upheaval and identity rebellion are common.",
    timingNote: "Several months; may span 2 years.",
    caution: "Burning down the entire structure when refinement is what's needed. Act on what truly doesn't fit, but preserve what still has integrity.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional upheaval", "domestic disruption", "emotional awakening", "instinct liberation"],
    emotionalTone: "Emotionally unsettled and electrically alert — old emotional patterns are breaking.",
    practicalExpression: "Significant changes in home life, family dynamics, and emotional patterns. What felt emotionally secure may suddenly shift. The disruption creates space for more authentic emotional expression.",
    timingNote: "Several months with retrograde loops.",
    caution: "Impulsive domestic decisions that can't be undone. The impulse for change is real — act thoughtfully.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["relationship upheaval", "values revolution", "sudden attraction", "love liberation", "financial surprise"],
    emotionalTone: "Erotically charged and emotionally unpredictable in love.",
    practicalExpression: "Sudden changes in love life and values. New and unexpected relationships may begin. Existing relationships need room to breathe or they may rupture. Values are being revolutionized.",
    timingNote: "Several months.",
    caution: "Making permanent decisions about love under temporary revolutionary energy. Uranus attractions are often wildly exciting and not always lasting.",
    domain: ["love", "career"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["mental revolution", "sudden insight", "communication disruption", "innovative thinking", "tech breakthroughs"],
    emotionalTone: "Mentally electrified — ideas arrive suddenly and from unexpected sources.",
    practicalExpression: "A period of intellectual breakthrough and unconventional thinking. Great for innovation, technology-related work, and any field requiring out-of-the-box thinking. Communication may be erratic.",
    timingNote: "Several months.",
    caution: "Mental scatter and difficulty following through on the many brilliant ideas that arrive.",
    domain: ["communication", "career", "expansion"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["structure revolution", "breaking old limits", "authority challenge", "life reinvention", "system disruption"],
    emotionalTone: "Restless against the confines of old structures.",
    practicalExpression: "A profound breaking-down of old structures that have calcified. Career systems, long-held disciplines, and authority relationships are being disrupted and remade.",
    timingNote: "Several months to a year.",
    caution: "Throwing out genuinely useful structures along with the outdated ones. Discern what still serves before dismantling.",
    domain: ["career", "inner", "expansion"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["identity revolution", "personal reinvention", "sudden change", "authentic self", "liberation"],
    emotionalTone: "Suddenly and profoundly different — the old self no longer fits.",
    practicalExpression: "A complete reinvention of personal identity. Appearance, lifestyle, and how you present yourself all undergo radical change. This is a once-in-a-lifetime transit for most charts.",
    timingNote: "Several months; broader influence over 2 years.",
    caution: "Destroying relationships and structures that didn't need to be destroyed in the pursuit of liberation.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Uranus",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career revolution", "sudden career change", "public disruption", "professional liberation", "path reinvention"],
    emotionalTone: "Career path is electrified — the expected trajectory is no longer satisfying.",
    practicalExpression: "Sudden and significant career changes. A career or public path that no longer fits may suddenly end or radically transform. The new direction may be surprising to everyone, including you.",
    timingNote: "Several months to a year.",
    caution: "Impulsive career decisions without a sustainable plan for what comes next.",
    domain: ["career", "expansion"],
  },
  // ─── NEPTUNE TRANSITS ────────────────────────────────────────────────────────
  {
    transitPlanet: "Neptune",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["spiritual dissolution", "identity confusion", "creative transcendence", "idealization", "fog"],
    emotionalTone: "Dreamlike, unfocused, and spiritually open — but also uncertain about who you are.",
    practicalExpression: "A deeply spiritual and creative period — but one in which clear identity and direction can become foggy. Artistic and spiritual work can be transcendent. Practical matters may feel elusive.",
    timingNote: "Several years with retrograde loops.",
    caution: "Confusion, deception, and escapism. Be especially careful with substances, idealizing relationships, and commitments made under Neptune's fog.",
    domain: ["inner", "expansion"],
  },
  {
    transitPlanet: "Neptune",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional dissolution", "spiritual sensitivity", "psychic opening", "compassion flood", "boundary loss"],
    emotionalTone: "Deeply empathic, somewhat boundaryless, and spiritually open emotionally.",
    practicalExpression: "A profound deepening of emotional and spiritual sensitivity. Boundaries between self and others become porous. Creative, healing, and spiritual work is exceptional. Practical emotional clarity may be compromised.",
    timingNote: "Several years.",
    caution: "Losing yourself in others' emotional states, in idealized relationships, or in escapism. Maintaining healthy boundaries is essential.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Neptune",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["romantic idealization", "love transcendence", "artistic peak", "spiritual love", "financial illusion"],
    emotionalTone: "Deeply romantic, poetically inclined, and drawn to transcendent connection.",
    practicalExpression: "A peak period for artistic creation, spiritual love, and romantic idealization. Existing relationships take on a transcendent quality; new connections feel fated. Financial clarity may be compromised.",
    timingNote: "Several years.",
    caution: "Idealizing people who don't match the dream. Neptune dissolves clear perception in love — what seems perfect may be projection.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Neptune",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["intuitive thinking", "creative writing", "foggy communication", "psychic reception", "spiritual learning"],
    emotionalTone: "Intuitively aware but mentally foggy at times.",
    practicalExpression: "Exceptional for creative writing, poetry, spiritual study, and intuitive perception. Analytical clarity may be compromised. Read agreements carefully; avoid major contracts if possible.",
    timingNote: "Several years.",
    caution: "Misunderstandings, confusion, and susceptibility to misleading information. Verify facts carefully.",
    domain: ["communication", "inner"],
  },
  {
    transitPlanet: "Neptune",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["structure dissolution", "spiritual testing", "belief dissolution", "rebuilding foundations", "faith over fear"],
    emotionalTone: "Uncertain — old structures are dissolving and new ones have not yet formed.",
    practicalExpression: "Long-held structures, disciplines, and beliefs are softening. This can feel disorienting but creates space for more spiritually aligned structures to emerge. Faith replaces rigidity.",
    timingNote: "Several years.",
    caution: "Giving up too easily on things that still have value, or conversely, rigidly holding on to what Neptune is trying to dissolve.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Neptune",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["identity dissolution", "spiritual opening", "boundary loss", "empathic flooding", "mystical self"],
    emotionalTone: "Ethereal, porous, and spiritually receptive.",
    practicalExpression: "A period of profound identity softening — the boundaries of self dissolve into something more spiritual and empathic. Beautiful for artistic and healing work; challenging for practical identity and boundary maintenance.",
    timingNote: "Several years.",
    caution: "Extreme boundary vulnerability — susceptibility to being taken advantage of or lost in others' needs.",
    domain: ["inner", "expansion"],
  },
  {
    transitPlanet: "Neptune",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career dissolution", "spiritual vocation", "artistic career", "reputation fog", "calling awakening"],
    emotionalTone: "Uncertain about professional direction but pulled toward something deeper.",
    practicalExpression: "Career direction may dissolve or transform toward a spiritual, artistic, or healing vocation. What seemed clear about life's purpose becomes uncertain — and then recrystallizes into something more meaningful.",
    timingNote: "Several years.",
    caution: "Making major career decisions under Neptune's fog. Allow the transition to complete before locking in new directions.",
    domain: ["career", "inner"],
  },
  // ─── PLUTO TRANSITS ──────────────────────────────────────────────────────────
  {
    transitPlanet: "Pluto",
    natalTarget: "Sun",
    aspect: "conjunction",
    themes: ["total transformation", "death and rebirth of identity", "power confrontation", "radical change", "soul surgery"],
    emotionalTone: "Intense, stripped-down, and fundamentally altered — this is not a surface change.",
    practicalExpression: "The most intense personal transformation transit possible. Identity is stripped to its essentials. Power dynamics in career and relationships are confronted. What emerges is unrecognizably more authentic — but the process is rarely comfortable.",
    timingNote: "Several years; the full transit may span 3-5 years.",
    caution: "Power struggles, obsession, and the temptation to destroy rather than transform. The darker expressions of this transit can draw predatory people or situations. Psychological support is highly recommended.",
    domain: ["inner", "career", "expansion"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Sun",
    aspect: "trine",
    themes: ["empowered growth", "transformative ease", "depth", "personal power", "regeneration"],
    emotionalTone: "Powerfully engaged with one's own depths — transformation without crisis.",
    practicalExpression: "Deep personal transformation that comes with relative ease and empowerment. A period for psychological depth work, career transformation, and genuinely understanding your own power.",
    timingNote: "Several years.",
    caution: "Underestimating the depth of change available. This transit rewards profound investment.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Sun",
    aspect: "square",
    themes: ["power struggle", "identity crisis", "forced transformation", "confronting darkness", "breakdown before breakthrough"],
    emotionalTone: "Under siege — external and internal pressures intensify simultaneously.",
    practicalExpression: "Profound and often difficult identity transformation through confrontation with power. Career upheaval, authority conflicts, and deep inner reckoning. What emerges has survived something real.",
    timingNote: "Several years.",
    caution: "Destructive power dynamics, control struggles, and the shadow. Professional support is valuable during this transit.",
    domain: ["inner", "career"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Moon",
    aspect: "conjunction",
    themes: ["emotional transformation", "root healing", "family reckoning", "deep inner work", "shadow work"],
    emotionalTone: "Intensely deep and emotionally raw — old wounds are rising for transformation.",
    practicalExpression: "A profound period of emotional and psychological transformation. Family wounds, childhood patterns, and the deepest emotional defenses are being excavated and remade. Therapy and inner work are invaluable.",
    timingNote: "Several years.",
    caution: "Emotional destructiveness toward self or others. The intensity requires a container — therapy, spiritual practice, or trusted community.",
    domain: ["inner", "relationships"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Venus",
    aspect: "conjunction",
    themes: ["love transformation", "obsessive attraction", "value revolution", "deep relationship work", "financial upheaval"],
    emotionalTone: "Consumed by intense feelings in love — desire, longing, and transformation.",
    practicalExpression: "Relationships are radically transformed. Obsessive attractions, power dynamics in love, and deep excavation of what you truly value characterize this period. What survives is profoundly real.",
    timingNote: "Several years.",
    caution: "Obsession, jealousy, and toxic attachment. Pluto-Venus transits can draw deeply transformative but also highly intense relationship dynamics.",
    domain: ["love", "inner"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Mercury",
    aspect: "conjunction",
    themes: ["deep thinking", "mental transformation", "power of words", "investigative insight", "compulsive thinking"],
    emotionalTone: "Mentally intense and probing — the mind goes deep.",
    practicalExpression: "A period of deep research, investigative thinking, and psychological insight. Writing and communication can reach new depths. There may also be obsessive thinking patterns to examine.",
    timingNote: "Several years.",
    caution: "Compulsive thinking, paranoia, and using communication as a form of control.",
    domain: ["communication", "inner"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Saturn",
    aspect: "conjunction",
    themes: ["structure destruction", "authority transformation", "power over fear", "karmic clearing", "deep restructuring"],
    emotionalTone: "Deeply serious and in the grip of transformative structural change.",
    practicalExpression: "Long-standing structures, fears, and authority patterns are being dismantled and remade at the deepest level. Career and life structures are being stripped and rebuilt.",
    timingNote: "Several years.",
    caution: "The destruction of structures that still served. Discern carefully before releasing long-held commitments.",
    domain: ["career", "inner"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Ascendant",
    aspect: "conjunction",
    themes: ["total rebirth", "identity transformation", "power emergence", "regeneration", "life overhaul"],
    emotionalTone: "Profoundly altered — nothing about the old self remains untouched.",
    practicalExpression: "One of the most comprehensive personal transformation periods possible. Every area of life is being remade — body, identity, approach, relationships. The person who emerges is fundamentally different.",
    timingNote: "Several years.",
    caution: "The intensity of this transit can be traumatizing without support. Professional psychological support is strongly recommended.",
    domain: ["inner", "career", "expansion"],
  },
  {
    transitPlanet: "Pluto",
    natalTarget: "Midheaven",
    aspect: "conjunction",
    themes: ["career transformation", "power and ambition", "public evolution", "authority confrontation", "legacy work"],
    emotionalTone: "Intensely focused on life's work and legacy — driven from the depths.",
    practicalExpression: "A profound career transformation. Power dynamics with authority figures, radical changes in professional direction, and a confrontation with what you're actually meant to do with your life.",
    timingNote: "Several years.",
    caution: "Power corruption in professional settings and destructive confrontations with authority. Act with integrity — Pluto exposes what is hidden.",
    domain: ["career", "inner"],
  },
];
